### ISSUE TITLE
NVMe composite Order. The order is different.

### ISSUE THREAD

**Issue by hitobashira** [hakandundar34coding/system-monitoring-center#104]
The NVMe order is different??

For example, in my environment. temperature.
slot0 PCIe 4.0 WD
slot1 PCIe 3.0 SPC
`
echo -e "nvme0" $(sudo nvme smart-log /dev/nvme0 | grep temperature)"\n""nvme1" $(sudo nvme smart-log /dev/nvme1 | grep temperature)
`

![Screenshot from 2022-07-16 21-45-46](https://user-images.githubusercontent.com/12706780/179355739-0026a779-9f1a-47c7-8e97-3256a2c42807.png)
C

**Comment by hakandundar34coding** [comment]
Can you detect sensor data folder of each SSDs?

Sensor data is read from the folders in `/sys/class/hwmon/` folder.
There are some folders such as `hwmon0`, `hwmon1`, `hwmon2`, etc.
There are `device`  folders in these `hwmon#` folders. You can look into these `device` folders to learn nvme number.

Or:
You can look into this folder:
`/sys/class/block/[nvme_device_name]/device`
There may be `hwmon` folders. You can look into files with name `name` or names which contains `_label` to learn sensor details.

Which ones are nvme0 and nvme1?

**Comment by hakandundar34coding** [comment]
Currently there is no answer. I will close this issue.

I will try to fix the problems (if there are bugs) if you provide more information.

**Comment by hitobashira** [comment]
thank you.
I may have made a serious mistake.
my hope is ::
It is to distinguish between nvme0 and nvme1. Happy to add the nvme's number.

`echo -e "nvme0" $(sudo nvme smart-log /dev/nvme0 | grep temperature)"\n""nvme1" $(sudo nvme smart-log /dev/nvme1 | grep temperature)

nvme0 temperature : 31°C (304 Kelvin)

nvme1 temperature : 33°C (306 Kelvin)`

`
/sys/class/hwmon
❯ find -type d -execdir ls -l \; | grep nvme
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 hwmon0 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/hwmon0
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 hwmon1 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/hwmon1
`
`
/sys/class/block
find -type d -execdir ls -l \; | grep nvme
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1p1 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p1
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1p10 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p10
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1p2 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1p3 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p3
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1p6 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p6
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1p8 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p8
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme0n1p9 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p9
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p1 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p1
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p10 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p10
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p2 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p2
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p3 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p3
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p4 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p4
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p5 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p5
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p6 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p6
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p7 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p7
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p8 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p8
lrwxrwxrwx 1 root root 0 2023-01-17 10:40 nvme1n1p9 -> ../../devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:01.0/0000:04:00.0/nvme/nvme1/nvme1n1/nvme1n1p9
`


I had be absent because of poor physical condition.
![Screenshot from 2023-01-18 06-01-50](https://user-images.githubusercontent.com/12706780/213011687-2b000333-9f1c-48ff-a67f-74b0fdb44849.png)

**Comment by hakandundar34coding** [comment]
Can you write full output of ```sensors``` command?
```lm-sensors``` package is required for this command.

**Comment by hitobashira** [comment]
thank you . I put it.
[sesors.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/10455748/sesors.txt)

**Comment by hakandundar34coding** [comment]
The Sensors module is updated.
For testing:
Can you follow these steps?

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it
- Open terminal application in `src` folder
- Run this command: `python3 ./Main.py`
- Open `Sensors` tab
- Share screenshot of this tab.
- Write a comment here if there is an error on the terminal output.

**Comment by hitobashira** [comment]
$ python3 ./Main.py
(no errors)
also.
$ xsensors 
(there are not errors on the terminal output.)
![Screenshot from 2023-01-20 05-07-38](https://user-images.githubusercontent.com/12706780/213549198-2a116d01-f0c7-4245-a310-a2d5a825775d.png)
![Screenshot from 2023-01-20 05-08-39](https://user-images.githubusercontent.com/12706780/213549219-9932a248-f43d-4b89-993f-3563fa007509.png)

**Comment by hitobashira** [comment]
new.
![new_Screenshot from 2023-01-20 07-02-55](https://user-images.githubusercontent.com/12706780/213572242-e75c23a5-6f7a-4a5d-afaf-f0b7c80b2dbf.png)

**Comment by hakandundar34coding** [comment]
Detailed devices names added for Sensors tab. Sensor names of different NVMe disks are not same after the changes.
[Link](https://github.com/hakandundar34coding/system-monitoring-center/issues/141) for the issue.

Example [screenshot](https://user-images.githubusercontent.com/12706780/213776015-16a4da02-9743-46df-910f-ee0a37a9a907.png).
