### ISSUE TITLE
AppImage support

### ISSUE THREAD

**Issue by shuvashish76** [hakandundar34coding/system-monitoring-center#105]
If possible, please release as AppImage package.
[AppImage](https://github.com/AppImage/AppImageKit) is a community project & you could install without the need for a centralized store...

**Comment by hakandundar34coding** [comment]
As far as I know this package system is not safe as system packages (installed from repositories of the several distributions).

This is a system tool and requires root privileges for some actions. It may not be safe when this package type is used.

Python package of the application can be used for several systems.
