### ISSUE TITLE
Project Translation

### ISSUE THREAD

**Issue by shuvashish76** [hakandundar34coding/system-monitoring-center#106]
Integrate [Weblate](https://github.com/WeblateOrg/weblate) for translation purpose.

Features: https://weblate.org/en/features/
![Screenshot_2021-12-05-21-15-09](https://user-images.githubusercontent.com/48226312/144753433-4fc61e84-f12d-42d0-885e-1b9abd399061.jpeg)
https://weblate.org/en/hosting/

**Comment by hakandundar34coding** [comment]
Currently GitHub is used for translations. I do not want to spend time for additional integrations.
