### ISSUE TITLE
A question about Linux Mint support

### ISSUE THREAD

**Issue by ghost** [hakandundar34coding/system-monitoring-center#112]
Will this work for Linux Mint 20.3 Cinnamon edition based on Ubuntu? I did installed it and it works well and I have no issues

**Comment by hakandundar34coding** [comment]
The application works on Linux Mint and a lot of distributions.

- It can be installed on several distributions by using ```pip``` (Python package).
- It can be installed on Debian based systems by using .deb file.
- It can be installed on ArchLinux by using AUR repository.
