### ISSUE TITLE
Feature request: Display average value, also in selected time interval

### ISSUE THREAD

**Issue by drws** [hakandundar34coding/system-monitoring-center#116]
I/O and sometimes CPU load can have great variance so it is sensible to show average values as well. I propose two additions to System Monitoring Center:

1. Display the average value of the whole timespan that is on the graph. Since it's an overall value it's probably best it is shown under the graph.
2. Additionally provide an ability to freely select a timespan on the graph and dispay the average value in the selected interval. The resulting value could be shown under or in the graph.

Both values (overall average, selected average) should also be displayed with a simple horizontal line in the graph since this also helps to represent the instantaneuous value.

**Comment by hakandundar34coding** [comment]
Hello,

Adding these details would make the GUI more complex. Mostly, this application is used by desktop/home users. I do not want to design a denser and more complex GUI.

Drawing function for the charts is very long and complex. Adding interval selection feature would make this function more complex. And drawing performance may be lower. This application is also used on several ARM devices which have lower performance when compared to desktop computers. Additionally, Python is slower than the programming languages like C++/Rust on several cases.

I will close this issue. But you can write additional comments.

**Comment by drws** [comment]
I understand that the second suggestion with custom intervals would complicate the UI so it was put as an additional proposal.

However, the first suggestion (showing the average value somewhere) is still relevant given your input. The average value is very informative and even simplifies reading certain charts, making the software easier to use. Specifically I/O charts (disk and network speed) would benefit from showing average value.

As mentioned displaying average value (horizontal line) in the graph even helps with interpreting the current value (for all users). Again, most importantly with I/O data. One well-known example would be Windows 8+ copy dialog.

To sum everything up my final suggestion would be to display average values for disk (read/write) and network (upload/download) speed. Values could be displayed under the chart with the other ones, but I'm also encouraging you to think about displaying the relevant horizontal line to ease reading the chart in certain cases.

**Comment by hakandundar34coding** [comment]
I will think about average value and horizontal line features.

Currently development speed is low for this application. Reported bugs are fixed quickly. The features may be added after the evaluation.
