### ISSUE TITLE
Feature Request:  Remote Device Monitoring!

### ISSUE THREAD

**Issue by The-Real-Admin-Guy** [hakandundar34coding/system-monitoring-center#119]
First let me say this:  Amazing work, well done, useful and highly detailed functionality!

Any Plans to allow for remote monitoring of devices?

 I love this thing and would like to use it to monitor remote server instances...  
Remote task management would also be useful...

**Comment by hakandundar34coding** [comment]
There are no plans for remote monitoring of devices.
This feature is too detailed for this desktop application. I did not develop an application that works using networks and other computers. Also usage of the GUI of the application may not be practical for monitoring big servers that have large number of devices.

I will close this issue. But you can write additional comments.

**Comment by mikila85** [comment]
@hakandundar34coding  if you can sum up the info of the output in json i can build a server/client to visualize it remotely (user pass protected connection) and the community can help scale it up for all the visuals and later maybe remote actions.. think about it if it is possible

**Comment by hakandundar34coding** [comment]
Can you give more details?

- What are the details of the required information?
- What is required? Redirecting the information to terminal (printing) or a file?
- Is current GUI of the application enough (roughly) for your needs?
- How does it work?
