### ISSUE TITLE
[Feature Request] A graph for GPU Video memory.

### ISSUE THREAD

**Issue by dnkmmr69420** [hakandundar34coding/system-monitoring-center#124]
I think there should be a graph for video memory just like how there is a graph for GPU usage

**Comment by hakandundar34coding** [comment]
This feature may be added. Currently I have no new graphics card for testing this feature. The driver does not support this feature.

What is your graphics card model?
How did you install the application?
Can you test the updated module for this feature?

**Comment by hakandundar34coding** [comment]
It has been a long time since the last comment. I will close the issue.
