### ISSUE TITLE
PYPI ve dağıtım paketleri hakkında.

### ISSUE THREAD

**Issue by kurth4cker** [hakandundar34coding/system-monitoring-center#13]
Acaba bu program PYPI için paketlenebilir mi? Bu sayede dağıtım bağımsız kurulum yapılabilir diye umut ediyorum. Ve programın normal kurulum dosyalarıyla dağıtım paket dosyalarının birbirine bağlı olması sizce doğru mu? Normal build system dağıtım paket dosyalarına bağımlı olmayıp onlar olmadan da sorunsuz çalışabilse? Sonuçta paketleri sadece siz oluşturuyorsunuz ve kaynak koddan kurmak isteyen veya pip ile kurmak isteyen kişi onlara ihtiyaç duymayacak diye düşünüyorum. Ben python paketleme öğrenmeye çalışıyorum ve bu programı da pip için paketlemek için uğraşacağım. Program çok güzel olmuş ama ne yazık ki kaynak koddan kurulumdaki bazı aksaklıklar nedeniyle benim kullandığım dağıtıma kurulamadı. Bunları düzeltmeye çalışacağım. İyi günler..

PYPI ve dağıtım paketleri hakkındaki görüşlerinizi almak isterim.

**Comment by hakandundar34coding** [comment]
Daha önce Python paketi oluşturmadım. İsterseniz böyle bir paket oluşturabilirsiniz. Sistem Gözlem Merkezi uygulamasının Python paketi hakkında detaylı bilgi almak için mail attım.

Kurulumda karşılaştığınız sorunlar nelerdir?
Kullandığınız dağıtım ve paket sistemi nedir?

**Comment by kurth4cker** [comment]
karşılaştığım en büyük zorluk kullanıcı ev dizinine kurulamaması yani kurulum dizinlerinin değiştirilememesi oldu. pypi paketini bu kadar isteme sebebim de aslında bu. build system pip paketi yapar. sonra da pip ile kurarız diye düşündüm.

kullandığım dağıtım ise gentoo. ve sanırım o da pythonla yazılan programları pip'e uygun kuran bir yapıya sahip. çünkü pip ile kurulu paketleri listelediğimde paket sisteminden kurduğum python uygulamaları da gözüküyor. eğer pip paketlemede başarılı olursam size pull request atar veya bildiririm.

şu an için paketlenip kuruluyor ama data dosyaları için bir yol bulamadım henüz ve import ederken yerel modülleri `from . import modül` biçiminde import etmek gerekli sanırım. benim kendi forkumda yaptığım değişiklikler mevcut. bir bakıp yorumlayabilir misiniz?

https://github.com/kurth4cker/khello-py
kullanılacak sistem şuna benzer bir yapıya sahip. pyproject.toml dosyası olacak. khello klasörü yerine system_config_monitor olup kurulduğunda python paket dizinine o klasör içindekilerle birlikte kopyalanacak. setup.cfg yerine setup.py de kullanılabilir. hatta static veri setup.cfg komutlar ve fonksiyonlar ise setup.py olacak biçimde ikisi de kullanılabilir. bu konuda bir kısıtlama yok diye biliyorum. sizin projenizde kullandığınız `Main.py`'nin işini `__init__.py` ve `__main__.py` dosyaları yapıp onlar ilgili klasörün bir python modülü olduğunu belirtecek. PATH içine eklenecek scripti de yine build system oluşturabiliyor. şu an khello-py paketi test.pypi.org adresinde var. ordan kurmayı deneyebilirsiniz. eğer siz de uygun görürseniz ve sistem de sizin paketinizle uyum gösteriyorsa benim fikrim bu sistemi kullanmaktır. sanırım python için bu tavsiye ediliyor.

**Comment by hakandundar34coding** [comment]
Uygulamanın arayüz resimleri ```/usr/share/icons``` dizinine kopyalanıyor. Python paketi olunca nereye kopyanacak?
Bu dizinde olunca, sistem teması koyu/açık şeklinde değişince arayüzdeki resimlerinin renkleri de otomatik değişiyor. Ama yazdığım dizin dışında bu davranış korunacak mı?

Yazdığınız bazı detaylar hakkında bilgim yok. Yapacağınız paketin çalıştığını görüp, uygulama davranışını incelemek gerekli.

**Comment by kurth4cker** [comment]
ben de paket sistemini yeni öğreniyorum ne yazık ki. ama dediğiniz dizin tek standart değil. siz direkt `/usr` dizinini `PREFIX` olarak kabul edip oraya atıyorsunuz. gnu paketleri bunu sistem paket dosyalarıyla karışmaması için `/usr/local` içine atar. dolayısıyla ilgili iconları arayan kütüphaneler oraya da bakar diye tahmin ediyorum. kullanıcı ev dizinine de bakarlar hatta direk orayı data oluşturmak için kullanan yerler de var. `~/.local/share/icons` gibi bir kurulum olur kullanıcı kurulumunda. ama tabii bu özel bir durumda olur. sudo ile kurulunca yine /usr/ ve /usr/local içine atar.

**Comment by hakandundar34coding** [comment]
Şimdilik paket olarak deb, rpm ve pacman paketleri kullanılabilir. Belki PyPI paketi de düşünülebilir. PyPI paketi konusunda bazı sorunların da çözülmesi gerekli ama henüz bu konuda çalışmam olmadı.

**Comment by hakandundar34coding** [comment]
Uzun bir süre geçmiş ama PYPI paketi kullanılabilir durumda. Anasayfadan detaylarını okuyabilirsin.

Sonraki sürümler için sadece PYPI paketi planlanıyor.

Eksik varsa bildirebilirsin.
