### ISSUE TITLE
Wireless card detection (device subtype in modalias file: ssb)

### ISSUE THREAD

**Issue by hugok79** [hakandundar34coding/system-monitoring-center#131]
My wireless card **"Broadcom Inc. and subsidiaries BCM4312 802.11b/g LP-PHY (rev 01)"** is not detected/shown...

![Captura de ecrã_2022-11-29_14-41-11](https://user-images.githubusercontent.com/16929048/204561309-1e1a7bb6-1899-44e3-94a1-e38a39ca8732.png)

**Comment by hakandundar34coding** [comment]
Can you run ```lspci -nn``` command, find the line for your network card and write here?

**Comment by hugok79** [comment]
Broadcom Inc. and subsidiaries BCM4312 802.11b/g LP-PHY (rev 01)

**Comment by hakandundar34coding** [comment]
There is no device-vendor ids. An example: `[168c:002b]`.

Can you share outputs of these commands?
```cat /sys/class/net/wlan0/device/modalias```
```cat /sys/class/net/wlan0/device/uevent```

Is it an USB device?

**Comment by hugok79** [comment]
No, it is not an USB device.

* **cat /sys/class/net/wlan0/device/modalias**
pci:v000014E4d00004315sv0000105Bsd0000E003bc02sc80i00

* **cat /sys/class/net/wlan0/device/uevent**
DRIVER=wl
PCI_CLASS=28000
PCI_ID=14E4:4315
PCI_SUBSYS_ID=105B:E003
PCI_SLOT_NAME=0000:04:00.0
MODALIAS=pci:v000014E4d00004315sv0000105Bsd0000E003bc02sc80i00

**Comment by hakandundar34coding** [comment]
Vendor-model information is shown if the same modalias file data is used.
Can you run the application by using terminal and share the errors?
![network_card_test](https://user-images.githubusercontent.com/90193017/204715474-527ec625-36a3-44de-be36-2fc43a7947fc.png)

**Comment by hugok79** [comment]
Running from a terminal I don't get any errors....

**Comment by hugok79** [comment]
The Ethernet card shows up well but I don't get any info for **wlan0**...

**lspci | grep -i broadcom**

02:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetLink BCM5787M Gigabit Ethernet PCI Express (rev 02)
04:00.0 Network controller: Broadcom Inc. and subsidiaries BCM4312 802.11b/g LP-PHY (rev 01)

![Captura de ecrã_2022-11-30_12-18-12](https://user-images.githubusercontent.com/16929048/204794597-278eafea-0d7d-4b32-9ee8-b942b79630b4.png)

**Comment by hakandundar34coding** [comment]
Can you write the following code in to a file (`test.py`), run it (`python3 ./test.py`) and share the output?

```
#!/usr/bin/env python3

import os

selected_network_card = "wlan0"

device_vendor_name = "-"
device_model_name = "-"

if os.path.isdir("/sys/devices/virtual/net/" + selected_network_card) == False:
    print(1)
    if os.path.isfile("/sys/class/net/" + selected_network_card + "/device/modalias") == True:
        print(2)
        with open("/sys/class/net/" + selected_network_card + "/device/modalias") as reader:
            modalias_output = reader.read().strip()
        print(modalias_output)
        if device_vendor_name == "Unknown":
            device_vendor_name = "[" + _tr("Unknown") + "]"
        if device_model_name == "Unknown":
            device_model_name = "[" + _tr("Unknown") + "]"
    network_card_device_model_name = f'{device_vendor_name} - {device_model_name}'
    print(3)
else:
    print(4)
    if selected_network_card == "lo":
        print(5)
        network_card_device_model_name = "Loopback Device"
    else:
        print(6)
        network_card_device_model_name = "[" + _tr("Virtual Network Interface") + "]"

```

**Comment by hugok79** [comment]
$ python3 ./test.py
1
3

**Comment by hakandundar34coding** [comment]
Can you share output of these commands?
`ls /sys/class/net`
`ls /sys/devices/virtual/net`
`ls /sys/class/net/wlp3s0/device`

**Comment by hugok79** [comment]
Sure.
**$ ls /sys/class/net**
enp2s0  lo  wlan0
**$ ls /sys/devices/virtual/net**
lo
The last one shouldn't be **ls /sys/class/net/wlan0/device** instead?

**Comment by hakandundar34coding** [comment]
The last one is corrected:
` ls /sys/class/net/wlan0/device`

**Comment by hugok79** [comment]
**$ ls /sys/class/net/wlan0/device**
coreid    driver     irq   name  power     subsystem  vendor
core_num  ieee80211  leds  net   revision  uevent

**Comment by hakandundar34coding** [comment]
There is not a file with name `modalias`. How did you get the [output](https://github.com/hakandundar34coding/system-monitoring-center/issues/131#issuecomment-1331255622) of this file?

**Comment by hugok79** [comment]
Sorry, I was testing translations in another system! This is the correct output:

$ cat /sys/class/net/wlan0/device/modalias
cat: /sys/class/net/wlan0/device/modalias: Ficheiro ou pasta inexistente

$ cat /sys/class/net/wlan0/device/uevent
DRIVER=b43
MODALIAS=ssb:v4243id0812rev0F

**Comment by hugok79** [comment]
**Ficheiro ou pasta inexistente** means "Inexistent file or folder"

**Comment by hakandundar34coding** [comment]
Can you share content of ` vendor` file in the device folder?
and `cat /sys/class/net/wlan0/device/net/[the_folder_name]/uevent`

Uevent content of this device is different when compared to other PCI devices network card, GPU, etc.).

**Comment by hugok79** [comment]
Like this:
**$ cat /sys/class/net/wlan0/device/net/wlan0/uevent**
DEVTYPE=wlan
INTERFACE=wlan0
IFINDEX=3

**Comment by hugok79** [comment]
The vendor is: 0x4243

**Comment by hakandundar34coding** [comment]
Can you run the following command and share the output file (If you are not tired and bored. There may be one more question)?
`tree /sys/class/net/wlan0 -l -L 5 > wlan0_output.txt`

**Comment by hugok79** [comment]
[wlan0_output.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/10126856/wlan0_output.txt)

**Comment by hakandundar34coding** [comment]
Can you share output of these commands?

```
cat /sys/class/net/wlan0/device/name
cat /sys/class/net/wlan0/device/ieee80211/phy0/name
```

**Comment by hugok79** [comment]
IEEE 802.11
phy0

**Comment by hakandundar34coding** [comment]
Information for this device can be found by using the data in [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/131#issuecomment-1331255622) comment.

But there is no information for ` MODALIAS=ssb:v4243id0812rev0F`.

Both devices have the same vendor-model information but they are in different computers.

What type of device is this? Are there any special configurations for this device? Generally, wireless cards are named in different format. For example: `wlp3s0`. But your device is named as `wlan0`.

**Comment by hugok79** [comment]
The first information I gave you was from **MX-Linux 21**"running live".

The second one was from **Pardus 21.3**, the OS installed in this laptop.

The laptop is the same, an old **acer Extensa 5620Z**

The network card is something like this:

![Broadcom-BCM4312-BCM94312MCG-BCM4312-Mini-PCI-E-54M](https://user-images.githubusercontent.com/16929048/205024787-f8e3c476-1302-4cb1-85a8-5f6c0836fa62.jpg)

**Comment by hakandundar34coding** [comment]
Currently, vendor-model information for this old device is not supported.

There is no information for `ssb:v4243id0812rev0F` in the files written so far. There may be some changes for this type of devices in later versions. There is very little information for `ssb` devices (modalias files contains this information: pci, usb, ssb, etc.).

I will close this issue. But you can write comments.

**Comment by hugok79** [comment]
Ok, no worries.
Anyway thanks, this software/app is great.

**Comment by hugok79** [comment]
Running EndevourOS live with the same laptop the wireless network card is shown...

**Comment by hugok79** [comment]
Running EndeavourOS live

[wlan0_output.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/10132338/wlan0_output.txt)

**$ ls /sys/class/net
ls /sys/devices/virtual/net
ls /sys/class/net/wlan0/device**
enp2s0  lo  wlan0
lo
aer_dev_correctable       current_link_width  irq             numa_node     revision
aer_dev_fatal             d3cold_allowed      link            power         subsystem
aer_dev_nonfatal          device              local_cpulist   power_state   subsystem_device
ari_enabled               dma_mask_bits       local_cpus      remove        subsystem_vendor
broken_parity_status      driver              max_link_speed  rescan        uevent
class                     driver_override     max_link_width  reset         vendor
config                    enable              modalias        reset_method
consistent_dma_mask_bits  firmware_node       msi_bus         resource
current_link_speed        ieee80211           net             resource0

**Comment by hugok79** [comment]
$ python3 ./test.py
1
2
pci:v000014E4d00004315sv0000105Bsd0000E003bc02sc80i00
3

**Comment by hakandundar34coding** [comment]
It looks like modalias file contains information of this device for pci subtype.

This may be because of different kernel versions (or other components of the system).

You can delete MAC address of your devices in these comments (you can also delete the older versions of the edited comments):
https://github.com/hakandundar34coding/system-monitoring-center/issues/131#issuecomment-1333681945
https://github.com/hakandundar34coding/system-monitoring-center/issues/131#issuecomment-1332066652

**Comment by hugok79** [comment]
Ok, Thank you!

**Comment by hakandundar34coding** [comment]
I deleted some of your comments (previous versions) because of the MAC address.

--------------------------------------

Currently, there are no plans for application code changes because of [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/131#issuecomment-1333725973) reason.
