### ISSUE TITLE
Not an Issue - Into void

### ISSUE THREAD

**Issue by zen0bit** [hakandundar34coding/system-monitoring-center#139]
I am adding system-monitoring-center to void-linux

https://github.com/void-linux/void-packages/pull/40893 (Still waiting for approval)

If you want check/repair/comment/approve template for your excellent program...

Cheers

And thank you

Keep up good work :+1:

**Comment by hakandundar34coding** [comment]
I read the page for SMC packaging. I do not work with the accounts that have the six colored flag or things that are associated with it. I will not write on that page.

About the template file:
I do not know this packaging type. It looks like the required dependencies for the application are added to the template file.
