### ISSUE TITLE
Error displaying icons in the application.

### ISSUE THREAD

**Issue by Linuxoid85** [hakandundar34coding/system-monitoring-center#14]
Error displaying icons in the application.

![Снимок экрана от 2021-12-12 16-41-28](https://user-images.githubusercontent.com/71516578/145714702-47f807df-ebed-4939-acaa-7fb13d559d7d.png)

Working environment: GNOME 41
Distribution: Fedora 35
The reasons are unknown.

In addition, when switching to the "Users" tab, the following messages appear:
```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 222, in users_initial_func
    user_image_unset_pixbuf = Gtk.IconTheme.get_default().load_icon("system-monitoring-center-user-symbolic", 16, 0)
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Значок «system-monitoring-center-user-symbolic» не присутствует в теме Adwaita (0)
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 355, in users_loop_func
    user_account_image = user_image_unset_pixbuf
NameError: name 'user_image_unset_pixbuf' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 355, in users_loop_func
    user_account_image = user_image_unset_pixbuf
NameError: name 'user_image_unset_pixbuf' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 355, in users_loop_func
    user_account_image = user_image_unset_pixbuf
NameError: name 'user_image_unset_pixbuf' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 355, in users_loop_func
    user_account_image = user_image_unset_pixbuf
NameError: name 'user_image_unset_pixbuf' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 355, in users_loop_func
    user_account_image = user_image_unset_pixbuf
NameError: name 'user_image_unset_pixbuf' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 355, in users_loop_func
    user_account_image = user_image_unset_pixbuf
NameError: name 'user_image_unset_pixbuf' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Users.py", line 355, in users_loop_func
    user_account_image = user_image_unset_pixbuf
NameError: name 'user_image_unset_pixbuf' is not defined
```

Also, the application icon in the menu is not displayed.

![Снимок экрана от 2021-12-12 16-42-23](https://user-images.githubusercontent.com/71516578/145714761-37345a75-0a1f-4497-aaa1-f04aeb4a81f4.png)

Program release:
![Снимок экрана от 2021-12-12 16-43-51](https://user-images.githubusercontent.com/71516578/145714792-9a9b2075-f2ff-492a-96eb-bdb13afff7d3.png)

**Comment by hakandundar34coding** [comment]
The reason of this error:
icons can not be found by the application.

I think icons are not in these folders:
/usr/share/icons/hicolor/scalable/actions/        (GUI icons)
/usr/share/icons/hicolor/scalable/apps/            (application icon)

How did you install the application? 
1) Did you download and install RPM package?
or
2) Did you download the source code, prepare a RPM package and install the package?

**Comment by Linuxoid85** [comment]
From source code.
```bash
git clone ...
cd ...
./setup.py build; sudo ./setup.py install
```

The rpm package does not have such a problem.

**Comment by hakandundar34coding** [comment]
I have installed the application on virtual machine by using RPM package without problems.

You can prepare a RPM package by using ```/packaging_scripts/rpm_packaging.sh``` script file after downloading the source code. The script file should be run in the ```packaging_scripts``` folder in order to avoid errors. After that you can install the new RPM package.

**Comment by hakandundar34coding** [comment]
You can reopen the issue or open a new one if same problem continues when ```/packaging_scripts/rpm_packaging.sh``` is used.
I have updated the ```README.md``` file. Steps for generating packages from source code are added.
