### ISSUE TITLE
System Cleaning Feature (Turkish: Sistem Temizliği Özelliği)

### ISSUE THREAD

**Issue by mobilturka** [hakandundar34coding/system-monitoring-center#140]
Hocam öncelikle uygulama için sizi tebrik ediyorum. Gerçekten mükemmel. Sizden bir ricam olacak. Bu uygulamaya Stacer de olduğu gibi temizlik kategorisi (system cleaner) açarsanız tadından yenmez. Tabi bu sadece bir öneri. Artık siz bilirsiniz.

**Comment by hakandundar34coding** [comment]
Şimdilik sadece işlemlerin sonlandırılması gibi veya servislerin durdurulması gibi sistem değişiklikleri yapılıyor.

Sistem temizliği için ayrı bir uygulama yapılabilir. Bu haliyle daha odaklı bir uygulama. Farklı konulardaki özellikleri bir araya toplamak hem uygulama bakımını zorlaştırıyor hem de odaklılığı azaltıyor.

Konuyu kapatacağım. Bu konuya yeni yorum yazabilir veya başka özellik isteği için ve hata bildirimi için yeni konu açabilirsin.
