### ISSUE TITLE
Disk selection list size, disk model detection, sensor name and other improvements

### ISSUE THREAD

**Issue by hitobashira** [hakandundar34coding/system-monitoring-center#141]
The left sidebar is handy.
In addition, DISK is difficult to handle.

It seems to be a fixed width setting, but shouldn't it be variable width?

As for the number of display disks, it would be nice if all devices could be displayed according to the margin of the vertical screen.
(Is it 5,6 devices with standard font settings?)

As you can see in the image, I have it full screen in UHD for Testing. 

Still a little hard to see.
It's cumbersome. It is **difficult to select a target disk device**.

I probably don't need scrollbars in disk section. (for me)

The order of nvme is also a problem.
0n <1n.
Please follow the nvme number.

![Screenshot from 2023-01-18 06-45-10](https://user-images.githubusercontent.com/12706780/213019200-40489e1f-6709-4be0-b09b-937cbc8416f6.png)
![Screenshot from 2023-01-18 06-36-01](https://user-images.githubusercontent.com/12706780/213019934-9ed3a20a-b399-47d8-a4e6-4fb2b12f65f6.png)

this(nvme0n1) in not Sandisk?? it is WesternDigital SN770.
![Screenshot from 2023-01-18 07-03-48](https://user-images.githubusercontent.com/12706780/213023208-ea9f9c80-bb4e-48cb-8243-92a4b09c11d6.png)
[lsblk.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/10439785/lsblk.txt)

**Comment by hakandundar34coding** [comment]
Resizable device list feature may be added in the next version of the application.

--------------------------------

How did you install the application? Flatpak or other repositories?
Can you write output of these commands?
```
cat /sys/class/block/nvme0n1p3/device/device/modalias
cat /sys/class/block/nvme0n1/device/device/modalias
df --output=source,fstype,size,used,avail,pcent,target
cat /proc/partitions
```

**Comment by hitobashira** [comment]
install :: with pacman, aur.

NG:: cat /sys/class/block/nvme0n1p3/device/device/modalias

cat: /sys/class/block/nvme0n1p3/device/device/modalias: No such file or directory

OK::cat /sys/class/block/nvme0n1/device/device/modalias
pci:v000015B7d00005017sv000015B7sd00005017bc01sc08i02
OK::df --output=source,fstype,size,used,avail,pcent,target
OK::cat /proc/partitions
[center.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/10447332/center.txt)

**Comment by hakandundar34coding** [comment]
About disk list ordering:

System Monitoring Center lists CPU cores, disks, network cards by using the order which system provides.
In the output of the ```cat /proc/partitions``` command, ```nvme1n1``` disks are listed before ```nvme0n1``` disks.

--------------------------------

About device vendor-model name:

PCI database (which is used by several programs) does not include a device with WD name for ```v000015B7``` ID. Also there is no information for ```SN770``` disk.

You can send your device vendor and model to [this](https://pci-ids.ucw.cz/) website. The database may be updated and your device-vendor may be shown by System Monitoring Center.

Can you share output of this command?
```lsblk -o NAME,KNAME,VENDOR,MODEL```

--------------------------------

About sensors:

Can you write output of the command in [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/104#issuecomment-1386729564) comment.

**Comment by hitobashira** [comment]
❯ lsblk -o NAME,KNAME,VENDOR,MODEL | grep -P 'nvme\d'
nvme1n1      nvme1n1             SPCC M.2 PCIe SSD
├─nvme1n1p1  nvme1n1p1
├─nvme1n1p2  nvme1n1p2
├─nvme1n1p3  nvme1n1p3
├─nvme1n1p4  nvme1n1p4
├─nvme1n1p5  nvme1n1p5
├─nvme1n1p6  nvme1n1p6
├─nvme1n1p7  nvme1n1p7
├─nvme1n1p8  nvme1n1p8
├─nvme1n1p9  nvme1n1p9
└─nvme1n1p10 nvme1n1p10
nvme0n1      nvme0n1             WD_BLACK SN770 1TB << this!!
├─nvme0n1p1  nvme0n1p1
├─nvme0n1p2  nvme0n1p2
├─nvme0n1p3  nvme0n1p3
├─nvme0n1p4  nvme0n1p4
├─nvme0n1p6  nvme0n1p6
├─nvme
[sensors.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/10455842/sensors.txt)

[lsblk-o.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/10455836/lsblk-o.txt)
0n1p8  nvme0n1p8
├─nvme0n1p9  nvme0n1p9
└─nvme0n1p10 nvme0n1p10

**Comment by hakandundar34coding** [comment]
Can you find vendor and model files for NVMe disks and share content of them?

```
/sys/class/block/nvme0n1/device/vendor
/sys/class/block/nvme0n1/device/model

/sys/class/block/nvme1n1/device/vendor
/sys/class/block/nvme1n1/device/model
```

You can use the following command if the files above are not found:
`grep -rnwsR '/sys/class/block/' -e 'SN770'`

**Comment by hitobashira** [comment]
root04:54:13~
➜ cat /sys/class/block/nvme1n1/device/vendor
cat: /sys/class/block/nvme1n1/device/vendor
No such file or directory
❯ cat /sys/class/block/nvme0n1/device/model
WD_BLACK SN770 1TB

❯ cat /sys/class/block/nvme1n1/device/model
SPCC M.2 PCIe SSD
➜ cat /sys/class/block/nvme1n1/device/vendor
No such file or directory

root04:54:43~ vailid composison?  no return.
➜ grep -rnwsR '/sys/class/block/' -e 'SN770'

**Comment by hakandundar34coding** [comment]
Disk module is updated.
There is no change for Sensors tab. I saw the [screenshots](https://github.com/hakandundar34coding/system-monitoring-center/issues/104#issuecomment-1397538009). It looks like the latest source code is not run. The GUI is not changed. For example, `Sensor Group` column title is changed as `Device`.

For testing:
Can you follow these steps?

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) and extract it
- Open terminal application in `src/` folder
- Run this command: `python3 ./Main.py`
- Open `Disk` tab
- Select disks one-by-one and check vendor-model indormation
- Share a screenshot for the WD disk.
- Open `Sensors` tab
- Share a screenshot of this tab ([issue](https://github.com/hakandundar34coding/system-monitoring-center/issues/104) for the Sensors tab).
- Write a comment here if there is an error on the terminal output.

**Comment by hitobashira** [comment]
python3 ./Main.py > no message.
great. 
nvme0 WD SN770  have 2 sensors. 
nvme1 SP SP001TBP34A80M28 have not sensours.it is correct.
![Screenshot from 2023-01-20 16-20-28](https://user-images.githubusercontent.com/12706780/213641246-a51e12b7-2702-4b98-ada9-2fc085d05cd1.png)
![Screenshot from 2023-01-20 16-21-30](https://user-images.githubusercontent.com/12706780/213641250-f7aa7fec-b41d-407e-8296-0458dfbb748b.png)

**Comment by hitobashira** [comment]
gnome-disks
![Screenshot from 2023-01-20 16-44-29](https://user-images.githubusercontent.com/12706780/213644483-56b4555a-e72d-4135-97a8-5f4ebba1e62e.png)
gparted
![2023-01-20_16-49](https://user-images.githubusercontent.com/12706780/213644587-5a31d9f9-ecae-4f0c-aaf3-c9afd2ccc765.png)

**Comment by hitobashira** [comment]
Is it related to the fact that wd received OEM supply before acquiring sandisc?
https://investor.wdc.com/news-releases/news-release-details/western-digital-acquisition-sandisk-receives-approval-chinas

**Comment by hakandundar34coding** [comment]
Disk tab is updated again.

**Comment by hakandundar34coding** [comment]
Disk tab code is updated again. In hardware databases it is listed as Sandisk.
But in the device folder it is shown as WD.

-------------------------------

Sensors tab code is updated for preventing devices names starting with `0000:`.

Can you download and run the code again?

**Comment by hitobashira** [comment]
done! excellent.
Thanks a lot.

By the way,
nvme1n1p = SPCC M.2 PCIe SSD (ECFM12.2)= Phison Electronics Corporation - E12 NVMe Controller

The name of the integrated controller is more convenient for this device (SPCC). It may be limited to me.

Anyway, I'm very happy because the numbers are easier to understand.

However, there may be a demand to match the display of gnome-disks, gparted and UEFI BIOS eventually.
![gnome-disks_en_US_2023-01-20_23-44](https://user-images.githubusercontent.com/12706780/213726559-4cacb072-47a9-4a22-b1fe-1f6a2823c4d1.png)
![Screenshot from 2023-01-20 23-28-04](https://user-images.githubusercontent.com/12706780/213726585-95c21ff9-d04e-4e0a-976d-e893a519889a.png)

**Comment by hakandundar34coding** [comment]
Are there any bugs for vendor-models of other disks?
What is shown for nvme1n1p?

------------------------------------------

A lot of disks are connected to your system. Are there any performance problems when Disk tab is opened?

------------------------------------------

Can you share a screenshot of the Sensors tab?

------------------------------------------

About the sidebar (tab-device names) width:
For text size:
What settings do you use?
Font size or scaling (DPI)?

**Comment by hitobashira** [comment]
>Are there any bugs for vendor-models of other disks?

Team HDD. no problem.

 >What is shown for nvme1n1p?

Phison Electronics Corporation - E12 NVMe Controller
nvme1n1p1  (Partition) .
same nvme1n1  (Disk).

>A lot of disks are connected to your system. Are there any performance problems when Disk tab is opened?

no problem. with 7HDD, 2NVMe , and USB thumb.

sda sdg : ZFS raid
sdb sdc sdd sde : btrfs raid
sdf : btrfs on bcache
last week , I deleted XFS.

No app performance degradation issues on any filesystem.

ZFS seems to be unsupported.
I would be happy if you could support ZFS someday.  

>Can you share a screenshot of the Sensors tab?

![Screenshot from 2023-01-21 03-14-30](https://user-images.githubusercontent.com/12706780/213776015-16a4da02-9743-46df-910f-ee0a37a9a907.png)

>About the sidebar (tab-device names) width:For text size:
>What settings do you use?
>Font size or scaling (DPI)?

basefontsize: 10 or 11

Resolution::3840x2160
font:: 1.2
scale::1.2
Used for almost 5 years.
**UI 100%.**
No fractional scaling.
∴ about:: 1.2x1.2


Currently for testing purposes for your app.
scaling 200%
font size::0.7
**UI 200%**
No fractional scaling.
∴ about:: 2.0x0.7


I think my usual setting is quite unusual.

So, I think that the impression is quite different from the UHD screen capture before yesterday.

**Comment by hitobashira** [comment]
Also, I have some hopes for bcache.

bcache0 tab::
About this tab
It would be nice to see the status of the hanging HD.

in particular,
Dirty 🐰Data 0B (0%)
 State 🐰 clean|dirty

python::bcache-status.py
https://gist.github.com/visvirial/22513f28671752962f71c75a758a00f6/revisions

Note the rabbit.

![Screenshot from 2023-01-21 03-59-50](https://user-images.githubusercontent.com/12706780/213784551-a738b5fa-7b03-4a83-842f-09eea5d9f156.png)

![Screenshot from 2023-01-21 04-05-11](https://user-images.githubusercontent.com/12706780/213784740-833ec5b9-477e-4936-92d4-5d733a33ce3a.png)

**Comment by hakandundar34coding** [comment]
About ZFS filesystem support:
In the df [command output](https://github.com/hakandundar34coding/system-monitoring-center/issues/141#issuecomment-1387167977):
There is one disk with ZFS filesystem. Its name does not contain `/dev/`. Why?

-------------------------------------

About bcache disk support:
In the lsblk [command output](https://github.com/hakandundar34coding/system-monitoring-center/issues/141#issuecomment-1396753001):
There are 2 bcache disks.
But in the df [command output](https://github.com/hakandundar34coding/system-monitoring-center/issues/141#issuecomment-1387167977):
There is 1 bcache disk.
Are the 2 bcache disks same?

**Comment by hitobashira** [comment]
about bcache. 
same. 2 man cell. set . in my this case.
sdf            8:80   0   2.7T  0 disk
└─bcache0    252:0    0   2.7T  0 disk /media/SHAMBLEAU -->bcache **backing** device **HDD/sdf** 

└─nvme1n1p10 259:10   0 110.6G  0 part
  └─bcache0  252:0    0   2.7T  0 disk /media/SHAMBLEAU  --->bcache **cashing** device **NVMe1**

/etc/fstab
**/dev/bcache0**	/media/SHAMBLEAU	btrfs	defaults,noatime,space_cache=v2,compress=zstd,inode_cache,autodefrag,discard=async,auto	0	0

**Comment by hakandundar34coding** [comment]
Is caching device `nvme1n1` (whole disk)? Or `nvme1n1p10` (partition)?

Can you share output of these commands (screenshot for colors of files/folders)?
```
ls /sys/class/block/bcache0/device
ls /sys/class/block/bcache0
```

**Comment by hitobashira** [comment]
about ZFS.
>There is one disk with ZFS filesystem. Its name does not contain /dev/. Why?
I dont know . however,
ZFS It's like that .  no /dev/ and no fstab.

$ mount | grep zfs
ZETTON on **/media/ZETTON** type zfs (rw,noatime,xattr,noacl)

$ zpool status
  pool: ZETTON
 state: ONLINE
  scan: scrub repaired 0B in 06:36:16 with 0 errors on Sat Jan 14 04:03:02 2023
config:

	NAME                                                 STATE     READ WRITE CKSUM
	ZETTON                                               ONLINE       0     0     0
	  **wwn-0x5000c500bab99acb****1)**                       ONLINE       0     0     0 <--sda
	  **ata-WDC_WD40EZRZ**-00WN9B0_WD-WCC4E4YRV6Y9           ONLINE       0     0     0<---sdg
	logs	
	  nvme-WD_BLACK_SN770_1TB..-part9  ONLINE       0     0     0 <--zil nvme0 part9
	  nvme-SPCC_M.2_PCIe_SSD_27...part6  ONLINE       0     0     0 <--zil nvme1 part6

1) I just made a specification method that is inadvertently difficult to understand.but right.

for example.
❯ ls -lh **/dev/disk/by-id/** | head -20 | perl -alnE 'say @F[7..12] '

ata-ST6000DM003-2CY186_->../../sda
ata-ST6000DM003-2CY186_-part1->../../sda1
ata-ST6000DM003-2CY186_-part9->../../sda9
ata-TOSHIBA_DT01ACA300_->../../sde
ata-TOSHIBA_DT01ACA300_->../../sdc
ata-WDC_WD30EZRX-00DC0B0_->../../sdb
ata-WDC_WD30EZRZ-00Z5HB0_->../../sdf
ata-WDC_WD30EZRZ-00Z5HB0_->../../sdd
ata-WDC_WD40EZRZ-00WN9B0_WD-->../../sdg
nvme-SPCC_M.2_PCIe_SSD_->../../nvme1n1

**Comment by hitobashira** [comment]
``
 $ zpool iostat -v ZETTON
                                                       capacity     operations     bandwidth 
pool                                                 alloc   free   read  write   read  write
---------------------------------------------------  -----  -----  -----  -----  -----  -----
ZETTON                                               4.51T  4.57T      0      0    323    473
  wwn-0x5000c500bab99a                             3.07T  2.38T      0      0    154    149 HDD/sda
  ata-WDC_WD40EZRZ-00WN9B0_           1.44T  2.19T      0      0    105    197      HDD/sdg
logs                                                     -      -      -      -      -      -
  nvme-WD_BLACK_SN770_1TB_-part9          128K  7.50G      0      0     31     63 <-zil
  nvme-SPCC_M.2_PCIe_SSD_-part6      0  7.50G      0      0     31     63                 <-zil 
``

So the list if I want to exclude ZFS.
``
❯ lsblk -fs -s -p | grep zfs_member
/dev/sda1         zfs_member 5000             ZETTON           17085054960486466774                                
/dev/sdg1         zfs_member 5000             ZETTON           17085054960486466774                                
/dev/nvme1n1p6    zfs_member 5000             ZETTON           17085054960486466774                                
/dev/nvme0n1p9    zfs_member 5000             ZETTON           17085054960486466774  
``
In my case.
exclude device.
swap partiton. zram[swap] /dev/zram0 
NTFS(not mounted)
iso9660

**Comment by hakandundar34coding** [comment]
You may not have seen [this comment](https://github.com/hakandundar34coding/system-monitoring-center/issues/141#issuecomment-1399196019).

**Comment by hitobashira** [comment]
< Is caching device nvme1n1 (whole disk)? Or nvme1n1p10 (partition)?
I can not make out your comennt. Is this alright?

As you indicated.
nvme1n1  = whole disk
nvme1n1p10 =partition (bcache caching ) :: made with sudo make-bcache -C /dev/nvme1n1p10

![Screenshot from 2023-01-21 18-53-24](https://user-images.githubusercontent.com/12706780/213861812-f24be61f-c272-4653-a13d-588b452b826c.png)

![Screenshot from 2023-01-21 18-52-35](https://user-images.githubusercontent.com/12706780/213861820-1c740e05-8222-4922-b04b-67524fb892ec.png)

``
❯ LANG=C
❯ ls /sys/class/block/bcache0/device
ls: cannot access '/sys/class/block/bcache0/device': No such file or directory
❯ ls /sys/class/block/bcache0/      
alignment_offset  capability	     diskseq	   events_poll_msecs  holders	 power	removable  slaves     trace
bcache		  dev		     events	   ext_range	      inflight	 queue	ro	   stat       uevent
bdi		  discard_alignment  events_async  hidden	      integrity  range	size	   subsystem

``
![Screenshot from 2023-01-21 19-06-30](https://user-images.githubusercontent.com/12706780/213862092-95e42e62-2505-4008-9bd6-17cf6ef9147f.png)

**Comment by hitobashira** [comment]
little defect.
![2023-01-21_18-48](https://user-images.githubusercontent.com/12706780/213862707-27261c99-95b2-4fe7-92b1-5ecd1166c512.png)

my zram0 is swap.
my zram1 is not swap. /tmp ext4 .
via this init script. https://github.com/vaeth/zram-init

It's a matter of notation only. 
I feel that there are many cases where other major zram initialization scripts are used.

MEMORY > SWAP > SHOW 
![Screenshot from 2023-01-21 19-52-22](https://user-images.githubusercontent.com/12706780/213863697-b0de0040-c70f-4981-add9-37da3bdd7e3f.png)
It's correct.
``
Name :    /dev/zram0
Type :    Partition
Capacity :    15.6 GiB
Used :    5.0 GiB
Priority :    16383

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Name :    /dev/nvme1n1p2
Type :    Partition
Capacity :    16.6 GiB
Used :    0 B
Priority :    100

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Name :    /dev/nvme0n1p1
Type :    Partition
Capacity :    16.6 GiB
Used :    0 B
Priority :    100
``

**Comment by hakandundar34coding** [comment]
There are changes for device list width and disk tab code for zram disks.
There may be mode design changes for disk name list.

Can you follow these steps?

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) and extract it
- Open terminal application in `src/` folder
- Run this command: `python3 ./Main.py`
- Open Disk tab
- Check (swap) information near the big Disk label for both zram disks.
- Also check disk names on the unified tab name-device name list (share a screenshot).

**Comment by hitobashira** [comment]
can check zram0.
can not check zram1.

``
/home/Running/system-monitoring-center-master/src
❯ python ./Main.py
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/MainWindow.py", line 971, in on_row_activated
    Disk.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/MainWindow.py", line 971, in on_row_activated
    Disk.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 441, in disk_loop_func
    self.disk_initial_func()
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 417, in disk_initial_func
    disk_device_model_name = self.disk_device_model_name_func(selected_disk, disk_type, disk_parent_name)
  File "/home/Running/system-monitoring-center-master/src/Disk.py", line 621, in disk_device_model_name_func
    if line.split()[0].split("/")[-1] == selected_disk:
IndexError: list index out of range
Traceback (most recent call last):
``

**Comment by hakandundar34coding** [comment]
Can you refresh the page and download the code again?

-----------------------------------

About disk list length:
Can you share a screenshot of the Disk tab?

-----------------------------------

About ZFS support:
Can you share output of this command?
`cat /proc/diskstats`

This command is used for getting disk read and write speeds.

-----------------------------------

Update: Resizable device list feature is added. The list can be resized by dragging the line below the Sensors button.

![smc_device_list](https://user-images.githubusercontent.com/90193017/213905071-62cf6899-cc8d-46d9-ac10-7c4aee0b7273.png)

**Comment by hakandundar34coding** [comment]
It has been about one month since the last comment. I will close this issue. But you can write comments.
