### ISSUE TITLE
Feature request: Process with highest CPU usage in CPU usage graph mouseover display

### ISSUE THREAD

**Issue by BujuArena** [hakandundar34coding/system-monitoring-center#142]
In the CPU usage graph, there is already a feature showing the CPU usage of the system at the point in the graph which is being hovered by the mouse cursor.  I am requesting an addition to this small display showing the process with the highest CPU usage at the time in the CPU usage graph being hovered.

This feature would match the same feature present in the Windows tool, Process Explorer, which I have found valuable to determine the cause of a lag spike when using a different program.  I have not found another tool for Linux which can already do this, so if this feature was added to SMC, SMC would have something more which is valuable that no similar Linux tool has.

Thank you for writing SMC and for reading this.

**Comment by hakandundar34coding** [comment]
It is an interesting feature. But this feature requires tracking CPU usages of the all processes when CPU tab is opened. As a result of this, CPU usage of SMC would be higher. SMC is developed by using Python language. Python is slower on several cases when compared to the languages like C, C++ and Rust. This application may be run for long times during usage of the computer. Nearly all tabs are designed for automatically reloding the data and low CPU usage of the application. Only a few tabs are not loaded automatically. For example: Services tab and System tab.

For seeing the high CPU usages of the applications for short times, you can use Processes tab and sort the processes by CPU usages. You can set update interval as 0.5 seconds (from general settings). You can see graphics of CPU, memory and disk usage of the processes by opening process details of the each process (double click on a process or right click and click on Details). Probably you discovered this usage type for SMC.

I will close the issue but you can write additional comments or open a new issue for different features requests/bug reports.

**Comment by BujuArena** [comment]
Thank you for your response.  I'm not 100% sure I understand exactly what you mean, so I will try to discern here.

Is this what you're saying?  Because SMC is written in Python, gathering this information costs too much performance and therefore you consider the feature to not be worth implementing in SMC.

If my understanding is correct, I have an amendment to my request which might meet in the middle and act as a viable compromise.

If it was optional, disabled by default, and the option was labelled something like "Track process with highest usage in CPU graph for mouseover. Warning: costs additional CPU overhead while viewing the CPU usage graph",  would that be acceptable?

Note that you do not have to sort the entire list by CPU usage for this feature to work.  Instead, you would have to find the highest value, which is much less intensive than sorting.  SMC would have to iterate through all CPU usage values in the list and check whether the current iteration is higher than the previous highest, and if so, mark it.  This should be less CPU-intensive than the full sorting performed in the process list tab.

I personally have been wanting some way to retroactively check the cause of a CPU usage spike, and seeing it in the list exactly when it happens is not a reliable way to check it, so any reconsideration is appreciated.

**Comment by hakandundar34coding** [comment]
As you understand, computational cost is higher during gathering this information.

An option (disabled by default) may be added for this feature.

For getting the highest CPU usage, CPU usages of the all processes have to be get. Most of the work is getting and calculating the CPU usages. Currently, this information is not get for CPU tab. System-wide CPU usage is get in a very short way. There is no summation operation.

**Comment by BujuArena** [comment]
Hi.  I still have no way of retroactively determining the cause of a CPU usage spike.  Is there some way of getting that information?

**Comment by hakandundar34coding** [comment]
I saw your comment today. Probably, this feature will be added in about 2-3 weeks.

**Comment by hakandundar34coding** [comment]
An option for showing processes that consume max CPU sources is added to CPU tab customizations menu.

The application may be updated in Flathub in about 4 hours. The version number did not change.

Addidionally, there will be a new version (v2.20.0) in several repositories in about a few days. This version of the application will include this feature.

A few screenshots:
![smc_max_cpu_process](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/8d63b3be-d72c-4bd6-a0db-33ce367e6b2f)
![smc_max_cpu_process_menu](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/9a1057e8-6f99-4bf0-8fe9-9c02f77d0893)

**Comment by BujuArena** [comment]
Thanks a lot!  I updated from flathub and I have the new feature!  However, while it's amazing that we can finally have something that shows which process is using the most CPU, there is a minor issue affecting the efficiency of tracking down the source of the issue.  Here are some screenshots and descriptions describing what I mean.

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/601517/94b0b47f-bf59-4027-8134-fb6233adce12)

Here, I'm looking at process `electron` with process ID `3214` which exhibited a CPU usage spike.  However, when trying to search for process ID `3214`, I get no results.  However, when I manually sort the process list by process ID, there is a process with process ID `3214`!  It seems the search function is incomplete and does not search the process ID field.

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/601517/4bd8c205-832e-4f0f-96b8-bbd436dd4bb6)

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/601517/ee8ab0ef-0dc5-429b-8be5-d573985264e9)

Here's a screenshot showing ksysguard with process ID `3214` narrowed down.  It allows filtering by process ID.

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/601517/8b643cf5-2a4a-4172-a4f1-6c007cc931a6)

Other than this minor issue, having this feature is amazing for tracking down the cause of lag spikes in the Linux desktop.  Thank you so much!

**Comment by hakandundar34coding** [comment]
An option for searching processes by PID is added.

The application will be updated in Flatpak repository after one day. There was a new update yesterday. The version number is not changed. For other repositories, this feature will be usable in SMC v2.20.0 in about 3-4 days.

A screenshot of the option:

![smc_process_search_menu](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/bf1918b1-93be-4d15-8fa5-c65d9d38d003)


You can open new issues for bugs, new features, etc.

**Comment by BujuArena** [comment]
Thanks!  I think it should intuitively search all of those fields like other similar software (Process Explorer, ksysguard), but at least this option exists now!  I will open new tickets for new feature requests in the future.

**Comment by hakandundar34coding** [comment]
A new option (All) is added for searching processes by using their name + command line + PID information. It is the default option.

There will be an update in Flatpak repository in about 4 hours and this feature will be usable. The version number did not change.

A screenshot of the menu:

![smc_process_search](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/3dbb9f1b-34eb-4671-94d0-f68cce7b60fc)
