### ISSUE TITLE
Feature Request (Process Search by Command Line) & Bugs (Window Position and Encrypted Disk Information)

### ISSUE THREAD

**Issue by amiga-500** [hakandundar34coding/system-monitoring-center#153]
Brilliant app.  However, i notice an oversight.  Similar monitoring tools show processes and allow searching, however, unlike virtually all other monitoring apps, your app only searches processes by their name.  

Could you have the search not only search the process name but also the prcoess' command line too?

Right now, in Ubuntu, because i know my script is running i have a tough time finding it in your app which forces me to use Ubuntu's built-in System Monitor to find it (via its own search field that automatically search by command line).  

Please, if you can allow searching by command line too that will be great!

**Comment by hakandundar34coding** [comment]
Another user wrote about this feature some time ago. I did not added this feature because of some reasons ([Details](https://github.com/hakandundar34coding/system-monitoring-center/issues/62#issuecomment-1106585951)).

It looks like more users need this feature. Also some time ago, there were some code changes for getting process information. Because of that, command line information is get even if it is not shown as column. Performance impact would be very small in this case.

It may be added but there may be a search customization menu for selecting between process name (default) and command line options. You may select command line option for every search operation if the program is restarted.

**Comment by amiga-500** [comment]
Hi there.  Wow thanks for the reply.  Yea that will be fantastic if it returns!   Loving ur app!

Btw, are you able to also store the windows position?  I know u already store the window size (as an option).  But because the window position isnt stored too you get side effects like the gif shown below...

![position](https://user-images.githubusercontent.com/5191497/231505357-34347a1c-96dd-4649-9604-d24a76e734eb.gif)

The app always assumes the same center position despite the resize causing it to always be off-center.

A solution would be to recalculate the center taking into consideration the new saved size or allow the user to also store the window position.

**Comment by hakandundar34coding** [comment]
Window position does not change on my system if `remember window size` option is enabled. The behavior may be different on systems with different window managers.

The code is updated for fixing the window position problem. Can you follow these steps for testing?

If you are using System Monitoring Center v2:

- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code.
- Extract it
- Copy `MainWindow.py` file into the `src` folder in the installation directory
- Test the application for the window position problem update

If you are using System Monitoring Center v1:

- Write here. There will be a bug fix update for this version. But there are no new features for SMC v1.

**Comment by hakandundar34coding** [comment]
Process search customization feature (search by process name or command line) is added. There may be a new version that includes this feature in about 1 week. Example screenshot of the menu:

![smc_process_search_options](https://user-images.githubusercontent.com/90193017/232321560-35fc6d4a-de1f-4c5c-abeb-45f0983f16c6.png)

**Comment by amiga-500** [comment]
> If you are using System Monitoring Center v1:
> 
>     * Write here. There will be a bug fix update for this version. But there are no new features for SMC v1.

Yea i am using v1 😭.  I will look into upgrading my gtk to v4,  Will try later today and get back to you.


> ![smc_process_search_options](https://user-images.githubusercontent.com/90193017/232321560-35fc6d4a-de1f-4c5c-abeb-45f0983f16c6.png)

Hey WOW that was quick!  Really awesome! 🎉

**Comment by amiga-500** [comment]
Question:

Right now, at present, if i want to see the amount of unused (free) disk space on my system's mounted devices (e.g. my root is on **`sda6`** > **`/dev/mapper/vgubuntu-root`** mounted as **`/`**) I jump to terminal and use ```df -h``` or use Ubuntu's default system monitor's _File Systems_ tab...

![5](https://user-images.githubusercontent.com/5191497/232721837-12ddf00e-76a7-4bc2-8bba-49eb374e8e53.jpg)

![4](https://user-images.githubusercontent.com/5191497/232721960-ed64fa19-ad9d-4e43-a336-3d82f6ec955a.jpg)

In SMC,  under _Performance > Disk_, i notice Free, Used, and Capacity are shown as "Not Mounted" for my system drive **`sda6`** because i figure that disk is encrypted.  Makes sense.

![1](https://user-images.githubusercontent.com/5191497/232721195-aa0766a8-53d5-40bd-a680-11cd5e770a38.jpg)

Interestingly, "**_Show.._**" is able to reveal sda6's real capacity (isnt "Not Mounted")...
![3](https://user-images.githubusercontent.com/5191497/232721373-c17879a9-3e1b-4fa5-bc10-d5c0ebbbed72.jpg)

Is there a way in SMC to get free+used+capacity disk space for mounted devices so i don't have to leave SMC to find that out?

**Comment by amiga-500** [comment]
> Window position does not change on my system if `remember window size` option is enabled. The behavior may be different on systems with different window managers.
> 
> The code is updated for fixing the window position problem. Can you follow these steps for testing?
> 
> If you are using System Monitoring Center v2:
> 
>     * Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code.
> 
>     * Extract it
> 
>     * Copy `MainWindow.py` file into the `src` folder in the installation directory
> 
>     * Test the application for the window position problem update

Confirmed.  Yay it re-centers to the screen relatively to the size i make the window so it's working correctly now.  Awesome!  :)
(i didnt realize there was a v2 until you mentioned it 🤭)

**Comment by hakandundar34coding** [comment]
You can install SMC v2 by using Flatpak. In this case, you do not have to install GTK4 on your system as a .deb package.
You can install application updates by using Flatpak or a application store that supports Flatpak.

---------------------------------------

About the disk feature:
Can you share output of this command?
`df --output=source,fstype,size,used,avail,pcent,target`

**Comment by amiga-500** [comment]
> About the disk feature:
> Can you share output of this command?
> `df --output=source,fstype,size,used,avail,pcent,target`

Here you go

![image](https://user-images.githubusercontent.com/5191497/232838083-08262125-bf6b-4b5b-85d6-89f49605d722.png)


> You can install SMC v2 by using Flatpak

Ahh thx for the heads up!  Learned something new 👍🏾

**Comment by amiga-500** [comment]
> Process search customization feature (search by process name or command line) is added. There may be a new version that includes this feature in about 1 week. Example screenshot of the menu:
> 
> ![smc_process_search_options](https://user-images.githubusercontent.com/90193017/232321560-35fc6d4a-de1f-4c5c-abeb-45f0983f16c6.png)

Thanks again for search by Command Line feature.  Just tried it.  Works like a charm too!

**Comment by hakandundar34coding** [comment]
> Thanks again for search by Command Line feature. Just tried it. Works like a charm too!

I will add support for encrypted disks too. But this may be in one version later (in about 1 week). Currently, fixing the process tree expanding/collapsing problem has higher priority.

----------------------------------

Which parts of the `/dev/mapper/vgubuntu-root` path is defined/renamed by you? Is it only the last part (`vgubuntu-root`)?

**Comment by amiga-500** [comment]
> > Thanks again for search by Command Line feature. Just tried it. Works like a charm too!
> 
> I will add support for encrypted disks too. But this may be in one version later (in about 1 week). Currently, fixing the process tree expanding/collapsing problem has higher priority.

Wow you've gotta be the  fastest and most active developer ever!  Awesome! 🏍️

> Which parts of the `/dev/mapper/vgubuntu-root` path is defined/renamed by you? Is it only the last part (`vgubuntu-root`)?

Actually the entire path name: `/dev/mapper/vgubuntu-root` was generated by Ubuntu, not me, when i first installed.  I wonder if it's a default naming convention when encrypting the system on fresh installs?  I notice some others online having the exact same full path.   Now i wish i was more observant during install cuz that default name is terrible. 😢

When checking my other vm (also Ubuntu), also a fresh install but without encryption, it's root path is: `/dev/sda5`
(i also had let Ubuntu decide its naming for me).  Here is a snapshot of that other ubuntu install (not encrypted)

![other](https://user-images.githubusercontent.com/5191497/233169826-2ede0f1a-a658-4308-af9d-0f578573111e.jpg)

**Comment by hakandundar34coding** [comment]
> default name is terrible.

I tried to determine that how the disk path can be used for detecting an encrypted disk. There was no message about your disk name preference.

I will use a virtual machine for detecting more details.

**Comment by hakandundar34coding** [comment]
Can you share output of the following command and a screenshot of the File Systems tab of the default system monitor of your system?

`cat /proc/diskstats`

**Comment by amiga-500** [comment]
Here you go...

**Note:** Both systems are running as a VM in Ubuntu:

**My Non-Encrypted System:**

```bash
[/home/test]> cat /proc/diskstats
   7       0 loop0 14 0 34 0 0 0 0 0 0 12 0 0 0 0 0 0 0
   7       1 loop1 48 0 720 8 0 0 0 0 0 24 8 0 0 0 0 0 0
   7       2 loop2 43 0 698 14 0 0 0 0 0 24 14 0 0 0 0 0 0
   7       3 loop3 459 0 12364 134 0 0 0 0 0 732 134 0 0 0 0 0 0
   7       4 loop4 1438 0 32278 259 0 0 0 0 0 848 259 0 0 0 0 0 0
   7       5 loop5 54 0 2146 9 0 0 0 0 0 32 9 0 0 0 0 0 0
   7       6 loop6 615 0 5394 21 0 0 0 0 0 132 21 0 0 0 0 0 0
   7       7 loop7 45 0 698 9 0 0 0 0 0 24 9 0 0 0 0 0 0
   8       0 sda 32826 11889 2714796 15328 29378 88964 9906706 32472 0 43556 47800 0 0 0 0 0 0
   8       1 sda1 169 1013 13062 11 2 0 2 0 0 48 12 0 0 0 0 0 0
   8       2 sda2 2 0 4 0 0 0 0 0 0 12 0 0 0 0 0 0 0
   8       5 sda5 32546 10876 2697482 15309 29376 88964 9906704 32472 0 43548 47781 0 0 0 0 0 0
   7       8 loop8 43 0 696 13 0 0 0 0 0 24 13 0 0 0 0 0 0
   7       9 loop9 672 0 19912 344 0 0 0 0 0 1408 344 0 0 0 0 0 0
   7      10 loop10 768 0 55056 163 0 0 0 0 0 2292 163 0 0 0 0 0 0
   7      11 loop11 11 0 28 0 0 0 0 0 0 4 0 0 0 0 0 0 0
```
![image](https://user-images.githubusercontent.com/5191497/233953668-03ab8af1-8f5e-4d5e-ba77-747d94ffe904.png)

**My Encrypted System:**
```bash
[/home/test]> cat /proc/diskstats
   7       0 loop0 14 0 34 4 0 0 0 0 0 16 4 0 0 0 0 0 0
   7       1 loop1 356 0 12474 172 0 0 0 0 0 652 172 0 0 0 0 0 0
   7       2 loop2 48 0 720 50 0 0 0 0 0 68 50 0 0 0 0 0 0
   7       3 loop3 319 0 26518 191 0 0 0 0 0 1184 191 0 0 0 0 0 0
   7       4 loop4 462 0 14362 143 0 0 0 0 0 968 143 0 0 0 0 0 0
   7       5 loop5 61 0 2182 108 0 0 0 0 0 56 108 0 0 0 0 0 0
   7       6 loop6 1785 0 10764 204 0 0 0 0 0 512 204 0 0 0 0 0 0
   7       7 loop7 1548 0 37368 393 0 0 0 0 0 1112 393 0 0 0 0 0 0
   8       0 sda 1034356 81866 39230997 1203477 882398 414999 49319185 515099 0 1983292 1718577 0 0 0 0 0 0
   8       1 sda1 101 1013 6798 21 1 0 1 0 0 64 21 0 0 0 0 0 0
   8       2 sda2 2 0 4 0 0 0 0 0 0 8 0 0 0 0 0 0 0
   8       5 sda5 103 28 5250 56 20 15 280 2 0 80 59 0 0 0 0 0 0
   8       6 sda6 1034040 80825 39214193 1203381 882377 414984 49318904 515097 0 1983240 1718478 0 0 0 0 0 0
 253       0 dm-0 1114704 0 39212722 1444980 1292836 0 49318904 15843548 0 1992956 17288528 0 0 0 0 0 0
 253       1 dm-1 1085135 0 38969074 1432668 1169923 0 48380392 13288540 0 1981084 14721208 0 0 0 0 0 0
 253       2 dm-2 29525 0 241808 13232 117314 0 938512 1159412 0 23996 1172644 0 0 0 0 0 0
   7      10 loop10 1691 0 126492 639 0 0 0 0 0 5620 639 0 0 0 0 0 0
   7       9 loop9 1080 0 27842 268 0 0 0 0 0 1784 268 0 0 0 0 0 0
   7       8 loop8 58 0 2194 84 0 0 0 0 0 68 84 0 0 0 0 0 0
   7      11 loop11 62 0 2162 110 0 0 0 0 0 76 110 0 0 0 0 0 0
   7      12 loop12 12 0 36 7 0 0 0 0 0 24 7 0 0 0 0 0 0
```
![image](https://user-images.githubusercontent.com/5191497/233954535-9150ebbf-79ef-44a1-80b2-336b4441976b.png)

Note,: By default it seems the default system monitor's File Systems tab doesn't show all.  There is an option in its preferences to "Show all File Systems" which is by default unchecked.  If you want me to enable it let me know and i will give u another image.

**Comment by hakandundar34coding** [comment]
Support for encrypted disk names is added and the source code is updated. Can you test the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code?
There will be a new package (v2.12.0) that contains the latest changes in 1-2 days.

On the test system (virtual machine) there was only one encrypted disk. One of your systems (in the screenshots) also has an encrypted swap partition.

Can you select all disks that starts with `dm-...` and share Disk tab + Disk Details window screenshots for all of these disks?
Are there any errors on the terminal application?

For running the application from source code you can run the following command in `src` folder:
`python3 ./run_from_source.py`

**Comment by hakandundar34coding** [comment]
Package of SMC v2.12.0 is prepared. It may be downloadable from Flathub in about 4 hours.

I will close this issue. But you can write comments if there are problems after testing.

**Comment by amiga-500** [comment]
Apologies for the delay.  I checked out the Flathub update and yup my encrypted root drive now shows the free/avail values now.   Awesome!  🥇 

As for your question about the dm devices here is a recording of me running 2.12.0 from the terminal (if im not too late), if im understanding what you're asking...

![saa gif](https://user-images.githubusercontent.com/5191497/234607677-15813671-28d2-4cb9-9c12-5e9bfb58ced3.gif)

Hope the above answered ur question correctly.  

And as a refresher, my encrypted test system via the command: `lsblk --output NAME,KNAME,TYPE,SIZE,MOUNTPOINT`:

![image](https://user-images.githubusercontent.com/5191497/234613193-f3d9042e-ae1d-4822-9990-29898c62c4d5.png)

Btw, i had some clicking drama (seen in video) when selecting dm-2, the last entry, because the horiz scroll bar was in the way.  I believe it's because  dm-1 shows the name of the drive "vgubuntu-root" which triggers the horiz bar to show.  I had to just precisely click a few pixels to select at dm-2 eventually with my mouse.  The cursor keys plus enter worked though.   I figure a solution around this would be, if it detects the horiz scroll bar is showing, then add a few empty vertical pixels after the last entry so when scrolling down to select the last entry one can select it easier with their mouse.

Also, notice in the recording when i click any entry the view right-justifies.  It's because the drive name (vgubuntu-root) is present and so i figure this GUI element just assumes one wants to see things right-justified on each click.  Is it possible to prevent this from happening so when clicking on any entry the view remains left-justified.  Meaning, when the horiz scroll bar is present it would be up to me as a user to scroll to the right to see the full name of the drive?

Regards

**Comment by hakandundar34coding** [comment]
These 2 bugs (on the tab-device selection list) will be fixed in about 1 week. But there was a bug about treeview column order and it had higher priority. The latest version (v2.12.0) has code changes for fixing this bug.

**Comment by hakandundar34coding** [comment]
The bugs on the tab-device selection list are fixed and the application can be updated from Flatpak.
The behavior for horizontal scrolling is different on several systems. It may be fixed on your system. Can you write the result?

**Comment by amiga-500** [comment]
> The bugs on the tab-device selection list are fixed and the application

Yup, i can confirm both bugs in the tab are fixed.  Awesome!
The horizontal scrolling now works the way i want it (ie, it stays left-justified when i click).

**Comment by hakandundar34coding** [comment]
Additionally, you can resize the device-tab selection list by dragging the handle at the bottom if the list is very long.

A screenshot:

![smc_resize](https://user-images.githubusercontent.com/90193017/235287867-766ccdb6-a77b-4e20-ba6e-6cd78ba273c3.png)

**Comment by amiga-500** [comment]
Ahh thanks for pointing that out.  Didn't realize.  Just tried.  Works fantastically!  Great job!
