### ISSUE TITLE
Computer Type says "Other" for Virtual Machine

### ISSUE THREAD

**Issue by amiga-500** [hakandundar34coding/system-monitoring-center#155]
![Virtual Machines](https://user-images.githubusercontent.com/5191497/232274649-6b81c6bf-f866-4066-bae6-6becf3cefd87.jpg)

This is so a non-issue but i am loving the care to detail your app has in every thing it does so i figured to point this out.   Under the "System" tab you have a section showing the Computer info.  I am using a Virtual Machine to run my linux box.  I am not sure what normally shows for "Computer Type" but at least when running Ubuntu within a VM environment it shows as "Other".  Are you able to add an entry that recognizes the type as "Virtual Machine" since as you can see your other fields seem to correctly identify Vender and Model.

**Comment by hakandundar34coding** [comment]
Some virtual machine systems (VMWare, Qemu, etc.) reports is type as `Other`. I did not change the information. This information is read from `/sys/devices/virtual/dmi/...` directory. But additional information may be added. For example: `Other (Virtual Machine)`.

You can write more bugs.

Did you test the changes for window position [problem](https://github.com/hakandundar34coding/system-monitoring-center/issues/153)?

**Comment by hakandundar34coding** [comment]
Some virtual machine systems (VMvare, Qemu, etc.) reports is type as `Other`. I did not change the information. This information is read from `/sys/devices/virtual/dmi/...` directory. There are other type [examples](https://github.com/hakandundar34coding/system-monitoring-center/blob/ab336e43b797362eb7aa843c828400b9f71b97ac/src/System.py#L498).

`Virtual Machine` information is added after `Other` information for Computer Type. This change will be available in the newer version. Screenshot:

![smc_computer_type](https://user-images.githubusercontent.com/90193017/232755945-ed047b13-8436-40a3-9dbe-bbc2d690943e.png)


You can write more bugs.

Did you test the changes for window position [problem](https://github.com/hakandundar34coding/system-monitoring-center/issues/153)?

**Comment by amiga-500** [comment]
Wow much appreciated as always!  
Ahh thanks for the heads up regarding the window position.  Going to check it now :)
