### ISSUE TITLE
SMC1 Stores Column Orders / SMC2 Doesn't Always Store Column Orders

### ISSUE THREAD

**Issue by amiga-500** [hakandundar34coding/system-monitoring-center#156]
This is a very minor bug i discovered.

In SMC1 i can re-order the columns in any way i like then when i shutdown and relaunch SMC1 the orders are maintained.  See below recording.  

_**Note:** When dragging a column ur app normally shows white arrows to indicate where the column will be placed.  You can see it in the recording shown well below the column heading.  This is **NOT** a bug in your app, but something wrong with my test OS cuz in my other test OS (also Ubuntu) SMC1's white arrows are placed correctly on the column heading area.  So ignore the white arrows u see in this recording._

![SMC1-working](https://user-images.githubusercontent.com/5191497/233348566-7c7e0804-025c-454b-90ad-b72c5a9b0220.gif)

In SMC2, however, it seems when i re-arrange a column SMC2 usually wont store the new position and so on relaunch it goes back to its orgiinal spot.  I did discover if i add then remove a column from the settings area SMC2 will correctly store the column position.  See below recording.

_**Note 1:** It appears the white arrows that help show where the column will be placed is no longer shown in SMC2.  Is this a gtk4 thing? Meaning, u have no control if its shown on this gui element vs SMC1 which has it shown?_

_**Note 2:** I have no clue why SMC2 blanks out the entire Services area (as seen in the video) when i dragged the column the 2nd time.  It does that from time to time.  Never occurs in SMC1.   IjJust assume this is a gtk4 refresh thing.  Not a big deal but thought i'd point that out._

![SMC2-order-bug](https://user-images.githubusercontent.com/5191497/233348600-c27cccc4-e9aa-4775-8703-a33d2a635d7e.gif)

**Comment by hakandundar34coding** [comment]
About the dragging indicator (SMC v1):
It is drawn by the GUI toolkit (GTK3). There may be a bug. What is your GTK3 version? You can check it from the System tab of the application.

About the dragging indicator (SMC v2):
It is also drawn by the GUI toolkit (GTK4). Its design is changed for the new toolkit. I did not change it.

About the blank list on the Processes tab (SMC v2):
It may be a GTK4 bug. GTK4 is a new toolkit and has several bugs. For example: If you click on a combobox (dropdown menu) on a customization popover menu, it is not closed by clicking outside of the menu.

About the column order bug (SMC v2):
I noticed it in this morning. I did not have time to investigate the details.

Can you share a screenshot of the System tab? You can hide the computer name. Is the SMC v2 installed by using Flatpak? This version has newer dependencies (GTK4, etc.). You can update them by using Flatpak.

**Comment by amiga-500** [comment]
SMC1
![image](https://user-images.githubusercontent.com/5191497/233370656-adb1e69f-d33c-40d9-a9df-a5f54c86afa2.png)

SMC2
(Oh i still have it  running via this git source, but yea  I will try Flatpak too today)
![image](https://user-images.githubusercontent.com/5191497/233369849-54ac7d09-dfff-44b3-8512-d98f76f4fda0.png)


> About the dragging indicator (SMC v1):
> It is drawn by the GUI toolkit (GTK3). There may be a bug. What is your GTK3 version? You can check it from the System tab of the application.

The drag indicator works fine in my other vm using SMC v1.  They are using the same GTK3 version.  So i doubt its an issue in your app.  I think its something off about this other VM im using.

> About the dragging indicator (SMC v2):
> It is also drawn by the GUI toolkit (GTK4). Its design is changed for the new toolkit. I did not change it.

Ahh that answers it!  Thanks for the heads up!

**Comment by amiga-500** [comment]
I installed SMC2 via Flatpak now.  Here is the system page...yup you're right the GTK4 version is updated:

![image](https://user-images.githubusercontent.com/5191497/233378164-44aaafaa-d30a-4b4a-89fc-11adb1aca562.png)

So far, i no longer see the blank list issue under Processes or Services anymore.  So yea i think u r right about GTK4 bugs being the culprit.  So that's cool its gone now :)

**Comment by hakandundar34coding** [comment]
Both GTK3 and GTK4 (4.6.6) versions are old. Several bugs are fixed after these versions.

About SMC v1:
There is no control for this indicator. I did not write code for this.

-----------------------------------

Flatpak version is a bit slower but you can update it if updates are available. Also several dependencies are separate from the system packages.

**Comment by hakandundar34coding** [comment]
The column ordering/width remembering bug is fixed. The source code and the application (currently it is updated only on Flathub) are updated. Probably, the update on Flathub will be available after 4 hours.

Can you test the application by using the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code or the Flatpak version?

Are there other bugs?

**Comment by amiga-500** [comment]
Fixed! Works flawlessly now after thorough testing. Much appreciated as always.
So far i cant find any more bugs 🥇

**Comment by amiga-500** [comment]
Hey one last thing...

I noticed when the "Command Line" is too long (e.g. it is a java line with many parameters) then there is no way to see the full path and arguments.  One would have to open the column as large as possible just to get an idea of what it is.  

Could you have it so the tooltip for Command Line is able to show the entire command line?  Since the command line can be really large due to arguments i would imagine also having page breaks would be useful instead of a really, really long tooltip.

**Comment by amiga-500** [comment]
Oh another heads up...i found a bug...

For the fun of it i decided to do a test upgrade of Ubuntu.  In Ubuntu 22.10  SMC2 worked.  But in 23.04 this is what was shown...

![23 04](https://user-images.githubusercontent.com/5191497/233802979-093e8821-80cd-4cb9-ba94-e14dd4a71cc3.gif)

I dont plan to use Ubuntu 23.04 since ive discovered other apps are broken in it too. But i thought i would let you know.
(Note: i didn't click on the "Processes" and "User" tabs.  I only hovered over them.  All the tabs were clickable)

**Comment by hakandundar34coding** [comment]
Can you open new issues for newer bug reports and features?

-----------------------------------------------

Can you run the application by using the following command and share the errors?
`flatpak run io.github.hakandundar34coding.system-monitoring-center`

**Comment by amiga-500** [comment]
> Can you run the application by using the following command and share the errors? `flatpak run io.github.hakandundar34coding.system-monitoring-center`

My bad...when u mentioned to try "flatpak" above, i realized at that moment i was using SMC2 via wget directly from your latest source and running it from the command line.  When i run it via a flatpak install on Ubuntu 22.10 and 23.04 SMC2 works perfectly.

However, when running the latest source in 22.10 and 23.04 it shows the empty tabs you see above (in Ubuntu 22.04LTS and lower, SMC2 works fine via the latest source code), if that is important to know.

I will be using Flatpak from now on and not directly from your latest source files.  Thanks 👍🏾
