### ISSUE TITLE
Can you add an easy way to remove files installed using python3 ./setup.py install

### ISSUE THREAD

**Issue by pinbuck** [hakandundar34coding/system-monitoring-center#158]
it would be really convenient instead of manually removing files mentioned during install, similar to what's provided in other python projects:
![image](https://user-images.githubusercontent.com/96911866/233821169-362071ea-d905-4ae8-ba56-e744eff09885.png)

the other alternative is something like
python3 install.py uninstall

**Comment by hakandundar34coding** [comment]
How did you install the application?
Which version is installed on your system?

System Monitoring Center can be uninstalled by using these methods:

SMC v1 (if it is installed by using PyPI):
`pip uninstall system-monitoring-center`

SMC v2 (if it is installed by using Flatpak)
By using an application store that supports Flatpak or this command:` flatpak uninstall io.github.hakandundar34coding.system-monitoring-center`

SMC v1/v2 (if it is installed by using system package manager):
It can be uninstalled by using the system package manager (apt, dnf, pacman, etc.)

**Comment by pinbuck** [comment]
as it goes I'll just read and delete the files that were uninstalled, I'm assuming this was my mistake and I only just now figured out how to run it from the folder:
For SMC v1.x.x, in ```src/``` folder, run: ```python3 ./Main.py```.

Which version is installed on your system?

1.43.0

How did you install the application?

I did
`sudo python3 ./setup.py install`
using the source code in releases which I tend not to do, but I didn't figure out how to do the wiser above decision in time

```
pip uninstall system-monitoring-center
WARNING: Skipping system-monitoring-center as it is not installed.
```
im going to try to undo the installation using pip, maybe it just didnt appear in pip packages yet if thats where its going..?

I used to install and update previous versions through pip:
https://github.com/hakandundar34coding/system-monitoring-center/blob/master/docs/uninstall_pypi_package.md
but followed the instructions and changed over to installing it the way above. I prefer not to use the flatpak or pip. I didn't use to understand that pip is iffy and chose to install things that way.

Feel free to close this as solved.

**Comment by hakandundar34coding** [comment]
The setup.py file is used by package systems such as apt, pacman, pip, etc.
It was not prepared for direct usage.

You can remove the installed files manually. These files are:
```
/usr/share/applications/io.github.hakandundar34coding.system-monitoring-center.desktop
/usr/share/polkit-1/actions/io.github.hakandundar34coding.system-monitoring-center.policy
/user/share/system-monitoring-center/
/usr/share/icons/hicolor/scalable/apps/system-monitoring-center.svg
/usr/share/man/man1/system-monitoring-center.1.gz
/usr/bin/system-monitoring-center

/home/[USERNAME]/.local/share/applications/io.github.hakandundar34coding.system-monitoring-center.desktop
/home/[USERNAME]/.local/share/icons/hicolor/scalable/apps/system-monitoring-center.svg
/home/[USERNAME]/.local/share/icons/hicolor/scalable/actions/   (.svg files that start with system-monitoring-center-)
/home/[USERNAME]/.config/system-monitoring-center/config.txt
```

I did not use the setup.py file directly. I do not know if there are additional files in the system.

**Comment by hakandundar34coding** [comment]
I will close this issue. But you can write additional comments. You can also open new issues for new features or bug reports.
