### ISSUE TITLE
System-monitoring-center & touch screens

### ISSUE THREAD

**Issue by JimZix** [hakandundar34coding/system-monitoring-center#161]
I love your app, and would like to report one issue.  For most options and tabs, a single touch (one finger, one touch) is all that is needed to select the item.  The SENSORS option, though, requires that I touch the on-screen button with two fingers to select (two fingers, one touch simultaneously).

Not sure if this was intentional, or a design oversight.  I am using SMC with Zorin OS 16 Pro, with an Acer TL-23 touch screen. 

Thanks again for a great app.

**Comment by hakandundar34coding** [comment]
Do you touch the Sensors tab button (number 1 on the screenshot) or one of the sensors/rows (number 2 on the screenshot) with two fingers?
![smc_sensors](https://user-images.githubusercontent.com/90193017/235308465-cf0d5c96-6297-42bc-bde0-56f28cd5727f.png)

**Comment by JimZix** [comment]
#1 only
Hakan Dündar wrote:
Do you touch the Sensors tab button (number 1 on the screenshot) or one of the sensors/rows (number 2 on the screenshot) with two fingers?

**Comment by hakandundar34coding** [comment]
- What is the System Monitoring Center version?
- How is it installed (by using Flatpak or other)?
- If it is installed by using Flatpak, is the latest version of the platform dependency installed?
- Can you share a screenshot of the System tab of SMC?
- What is the mouse button equivalent of double finger single click on your system (middle click or right click)?

**Comment by JimZix** [comment]
Good day, Hakan. Here is the info you requested.
SMC version is: 2.12.0 (screen shot attached)
Installed via Flatpak, using the Zorin Software utility. 
Latest platform dependency is installed and updated daily as revisions are released
Screenshot of System Tab of is attached
I believe (but I may be mistaken) that the mouse equivalent of Double Finger Single Click is a double left click. In SMC, to trigger the sensor button with the mouse, all I do is a single left click (just like the other tabs.) 
I ran into this quite by accident, as I was getting the touch screen going on Zorin. So far, it is the only app I've run into this behavior on. It is very consistent, though -- and always, only on that button. 
Obviously, you don't have many users implementing SMC with a touch screen, and it is not something that is critical to my application. I pass it along as a point of reference for you. 
I have also tested other apps with the screen to see if it is perhaps position sensitive (ie: last item on the list.) Have not found another yet. I've tested it with GNOME FILES, the complete Google Office Suite and the complete Libre Suite. Also tested rather extensively with GNOME DESKTOP and the Zorin Software Center as well as the Software Updater.
Thanks!
Jim 
Get BlueMail <https://bluemail.me> for Desktop
Hakan Dündar wrote:
What is the System Monitoring Center version?
How is it installed (by using Flatpak or other)?
If it is installed by using Flatpak, is the latest version of the platform dependency installed?
Can you share a screenshot of the System tab of SMC?
What is the mouse button equivalent of double finger single click on your system (middle click or right click)?

**Comment by hakandundar34coding** [comment]
The screenshot is not shared. Because you replied to the e-mail that is sent by github. Can you share the screenshot by using github? These comments/messages are sent to you by using github.

There is no difference between the tab buttons. It is an interesting behavior.

Can you test the SMC v1 by using source code?

- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/smc_v1.zip) source code for SMC v1
- Extract it and open terminal in `src` folder
- Run this command: `python3 ./Main.py`
- Check the `Sensors` tab button behavior


>Obviously, you don't have many users implementing SMC with a touch screen, and it is not something that is critical to my application. I pass it along as a point of reference for you.

I fixed several bugs that are reported by several users. Some bugs may be specific to certain systems. But you can close the issue if you are bored because of these steps.

**Comment by JimZix** [comment]
I will in the morning. Thanks!

**Comment by amiga-500** [comment]
@JimZix 
>  _I will in the morning. Thanks!_

And i was so looking forward to more details too 😭

**Comment by JimZix** [comment]
sorry, I am under the weather today and have had very few minutes screen
time. UGH!

**Comment by JimZix** [comment]
![Screenshot from 2023-04-29 14-42-19](https://user-images.githubusercontent.com/132145212/235473646-4fcaa2fb-826d-4bc7-9cee-f25a02833d96.png)

![Screenshot from 2023-04-29 14-43-05](https://user-images.githubusercontent.com/132145212/235473739-c70a7849-ca3b-4281-b30b-76a92923558c.png)

I am starting to check out Release 1 from github.  Thanks for the clear directions, they will be very useful, as my experience with github is somewhat limited.  

jim

**Comment by JimZix** [comment]
Works fine in Release 1.   Thank you for your patience in my getting back to you.

**Comment by hakandundar34coding** [comment]
Can you follow these steps for testing a modified code?

- Open the following folder:
- `/var/lib/flatpak/app/io.github.hakandundar34coding.system-monitoring-center/current/active/files/share/system-monitoring-center/systemmonitoringcenter`
- Open `MainWindow.py` file
- Go to line `869`
- Add this line: `        return` (there will be 8 empty spaces at the beginning)
- Run System Monitoring Center v2 (device selection list will be hidden because of the changes)
- Test `Sensors` tab button
- After this, you can **remove** the added line (`        return`)

The code should be like the one in the screenshot (`        return` is added):
![smc_code](https://user-images.githubusercontent.com/90193017/235484678-e1bf487c-694c-4334-9a18-f42820000944.png)

**Comment by JimZix** [comment]
While I can read the referenced file in the repository, I do not yet have
enough experience in Github to open the file for editing.  I am so
sorry....I've been working on it for about 90 minutes.

jim

**Comment by hakandundar34coding** [comment]
The file is in your file system. It is in the following folder:
`/var/lib/flatpak/app/io.github.hakandundar34coding.system-monitoring-center/current/active/files/share/system-monitoring-center/systemmonitoringcenter`


> I've been working on it for about 90 minutes.

You can ask if you have questions.

**Comment by amiga-500** [comment]
@JimZix 
> _I do not yet have enough experience in Github to open the file for editing. I am so sorry..._

Actually, i think you misunderstood his request.  It's not hard.  Just do the following in your terminal (see recording below).  You already have everything you need on your end.  So, there is no Github editing involved. 

(Note: the 8 spaces before "return" is important).


![this](https://user-images.githubusercontent.com/5191497/235513234-797985d5-2154-4958-8730-ed30486d2769.gif)

**Comment by JimZix** [comment]
Ok, I will do that, once I get back home.

**Comment by amiga-500** [comment]
> Ok, I will do that, once I get back home.

bumped as a friendly reminder ☺️

**Comment by hakandundar34coding** [comment]
Currently, there is no additional information about this problem. It may be because of the GUI toolkit. I did not write code for touch screen behavior of the buttons.

I will close this issue. But you can write additional comments.

**Comment by JimZix** [comment]
Sorry for not getting back to everyone. I have had surgery on my hand and have been very limited in my typing abilities. Slowly mending. I apologize.
jim
Hakan Dündar wrote:
Closed #161 <https://github.com/hakandundar34coding/system-monitoring-center/issues/161> as completed.
