### ISSUE TITLE
CPU usage is 0 for all processes in the Processes tab

### ISSUE THREAD

**Issue by Mr-Blue-Sky-Candy** [hakandundar34coding/system-monitoring-center#164]
Version: 2.12.0
![Screenshot_20230508_113419](https://user-images.githubusercontent.com/131680576/236795076-9126ee41-802a-4b3a-97fe-c14c57726141.png)

My system is:
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.3.1-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 6800H with Radeon Graphics
Memory: 14.9 GiB of RAM
Graphics Processor: AMD Radeon Graphics 680M / NVIDIA GeForce RTX 3070 Laptop GPU
System Version: 1.0

**Comment by hakandundar34coding** [comment]
Did you checked CPU usages of all of the processes by scrolling to the end of the list?

Can you sort the processes by CPU usages and share a screenshot?

**Comment by hakandundar34coding** [comment]
Did you checked CPU usages of all of the processes by scrolling to the end of the list?

Can you run the application from terminal and share the output?

Commands:
If the application is installed by using pacman:
`system-monitoring-center`

If the application is installed by using Flatpak:
`flathub run io.github.hakandundar34coding.system-monitoring-center`

**Comment by GANs-and-roses** [comment]
Thanks for the help!

The command line output is:
```
$ system-monitoring-center

(python:37902): Gtk-WARNING **: 12:18:30.488: Unknown key gtk-modules in /home/mrbluesky/.config/gtk-4.0/settings.ini

(python:37902): Adwaita-WARNING **: 12:18:30.529: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
```

I just discovered some thing. When I order them according to memory, they are now ordered correctly in CPU:
![image](https://user-images.githubusercontent.com/131680576/236800737-aa24468f-ed53-4da3-8bb2-ae0225c0207b.png)
When I order them according to read speed, they are ordered according to memory and so on.

Still most of them 0, though. I guess System monitoring centre normalises the usage according to the number of threads. This becomes a major problem, especially when I check the server. A single threaded programme's usage may be 100% in that core but it will have 0% usage in a 128 thread server.

**Comment by hakandundar34coding** [comment]
There is a bug on v2.12.0. It is fixed. There will be a new version (v2.13.0) today. It may be updated in the repository in a few days. But the bug is fixed in Flatpak version. The version number is same but latest code changes are added to the Flatpak version.

An option for dividing CPU usages by CPU core count may be added for Processes tab in one of the newer versions of the application.

There are some warnings about GTK libraries. Can you share a screenshot of System tab of the application?

**Comment by GANs-and-roses** [comment]
Sağol, dostum;)

![image](https://user-images.githubusercontent.com/131680576/236804089-08d27906-d445-451e-b451-6b93b63c5241.png)

**Comment by hakandundar34coding** [comment]
Some users read the previous issues. I will write in English. 

You CPU has a lot of cores and its cores have high performance. CPU usages of some processes may be shown as 0% if they have low CPU usages. You can use tab customization menu for changing precision of CPU usage percentages. This menu changes if current tab changes. You can use the menu button on the left side of the main menu button for opening this menu.
Screenshot of the menu:

![smc_processes_menu](https://user-images.githubusercontent.com/90193017/236833529-32598bfe-14d0-4f31-b47c-40ed79d8385c.png)


The application is updated and it contains the code changes for fixing the column sorting bug. The latest version is v2.13.0. It may be downloaded by using Flatpak in about 4 hours. It may be updated by using pacman in about 1-4 days.

**Comment by hakandundar34coding** [comment]
> The application is updated and it contains the code changes for fixing the column sorting bug. The latest version is v2.13.0. It may be downloaded by using Flatpak in about 4 hours. It may be updated by using pacman in about 1-4 days.

The application can be updated by using the two ways. I will close this issue.
