### ISSUE TITLE
[Feature Request] Total CPU time column and CPU usage percentage division by CPU core count in the processes tab

### ISSUE THREAD

**Issue by Mr-Blue-Sky-Candy** [hakandundar34coding/system-monitoring-center#165]
When one wants to debug the most resource consuming application, total CPU time gives a good insight into the this.

**Comment by hakandundar34coding** [comment]
This feature may be added in the newer version of the application.

**Comment by hakandundar34coding** [comment]
About the CPU usage percentage division by core count feature: [link](https://github.com/hakandundar34coding/system-monitoring-center/issues/164#issuecomment-1538143640).

**Comment by hakandundar34coding** [comment]
The following features are added:

- Total CPU time column
- Option for CPU usage percentage division by CPU core count (Processes tab)

There may be a new version (v2.14.0) that contains these changes in about 1-2 weeks.
