### ISSUE TITLE
[Feature Request] Option to show total memory of multi process applications

### ISSUE THREAD

**Issue by JoeJoeTV** [hakandundar34coding/system-monitoring-center#166]
**Description:**
Applications like chromium based browsers use multiple processes, which are shown seperately, but it would be nice, to easily see, what the total memory usage of the application is, instead of only the usage of each child process.

**Comment by hakandundar34coding** [comment]
Total memory usage (cumulative memory usage) of the application feature may be added in new version of the application. This may not be before 1-2 months because of the other changes of the application.

**Comment by hakandundar34coding** [comment]
Following columns are added:

- CPU - Recursive
- Memory - Recursive
- Memory (RSS) - Recursive

Recursive data columns show performance data (CPU or memory usage) summation of the process and its all child processes.

The application may be updated by using:

- Flatpak in about 1-2 hours.
- Other repositories in about 1-2 weeks.
