### ISSUE TITLE
Not an Issue But VM's "GPU" Doesnt show anything

### ISSUE THREAD

**Issue by amiga-500** [hakandundar34coding/system-monitoring-center#167]
Please close this ticket if it is indeed not possible.

This is unlikely to be possible to fix seeing as how i am using a VM with hardware acceleration turned on but inside the VM it calls my GPU an "SVGA II Adapter".   But i figured to share the snapshot anyway in case it was of any use.

I don't care that most of the information for this video card is missing because i just assume its a VM thing and VMWare probably doesnt make those details known for this app to then use.

(SMC 2.13.0 via FlatPak)
![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5191497/31b9f7a2-2f03-4b1c-b376-49a66defb3ce)

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5191497/b6419dab-504c-4b37-82bc-0a4786c78fc7)
(same result in X11 and Wayland -- above is in Wayland)

```
>> sudo lshw -c video

  *-display                 
       description: VGA compatible controller
       product: SVGA II Adapter
       vendor: VMware
       physical id: f
       bus info: pci@0000:00:0f.0
       logical name: /dev/fb0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=vmwgfx latency=64 resolution=1280,800
       resources: irq:16 ioport:1070(size=16) memory:e8000000-efffffff memory:fe000000-fe7fffff memory:c0000-dffff

```

**Comment by hakandundar34coding** [comment]
`SVGA II Adapter` is GPU of the virtual machine. It does not provide information such as frequency, GPU usage, memory, etc. It is a virtual device.
