### ISSUE TITLE
Process list empty in the flatpak edition on NixOS

### ISSUE THREAD

**Issue by iopq** [hakandundar34coding/system-monitoring-center#168]
[log.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/11478339/log.txt)

I get this error when I click the process list, no processes show up

**Comment by hakandundar34coding** [comment]
Can you share output (smc_fp_command_output.txt file) of the following command?

You can write it to a file by changing it:
`ps -eo comm:96,pid,user:80,s,rss,vsz,sz,nice,thcount,ppid,uid,gid,group:800,command=CMDLINE > smc_fp_command_output.txt`

**Comment by iopq** [comment]
it says
```
ps: bad -o argument 'comm:96', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,nice,rgroup,ruser,time,tty,vsz,sid,stat,rss
```

**Comment by hakandundar34coding** [comment]
What is the version number of `coreutils` package?

**Comment by iopq** [comment]
coreutils (GNU coreutils) 9.1

**Comment by hakandundar34coding** [comment]
I tested the application on virtual machine. There was no error on Processes tab. But there was an error on System tab. There will be improvements.

System: NixOS 22.11 on virtual machine.

Can you write OS version and desktop envrionment?

--------------------------------

Can you try the following command?
`ps -eo comm,pid,user,s,rss,vsz,sz,nice,thcount,ppid,uid,gid,group,command=CMDLINE > smc_fp_command_output.txt`

**Comment by iopq** [comment]
I'm on NixOS unstable github revision "44f30edf5661d86fb3a95841c35127f3d0ea8b0f", Gnome

I ran this and I got

```
[iopq@laptop:~]$ ps -eo comm,pid,user,s,rss,vsz,sz,nice,thcount,ppid,uid,gid,group,command=CMDLINE > smc_fp_command_output.txt
ps: bad -o argument 's', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,nice,rgroup,ruser,time,tty,vsz,sid,stat,rss
```

**Comment by hakandundar34coding** [comment]
Why there are problems when using `ps` command parameters? SMC uses this command for getting process information.

Are there errors when other tabs are opened?

**Comment by iopq** [comment]
Yes, Users, Services, System all throw a ton of errors

**Comment by hakandundar34coding** [comment]
System Monitoring Center uses `ps` command for Processes and Users tabs. `ps` command does not work on your system if some parameters are used. `ps` command is part of `coreutils` package. There may be a bug of the system/package or some configurations may cause this problem. I do not know details about your system.

There was no error on Processes and Users tabs during the test on stable version of the OS on virtual machine.

I will close this issue. There may be improvements for Services and System tabs.

**Comment by iopq** [comment]
ps command is actually running BusyBox, so when you have BusyBox installed, it won't call the `ps` you think it's calling

**Comment by hakandundar34coding** [comment]
Is there a way (environment variable or other) to run `ps` command without using BusyBox?

**Comment by iopq** [comment]
I guess, but why not just use `psutil` Python package instead of the `ps` program in the first place? Then there's no compatibility worry

**Comment by hakandundar34coding** [comment]
It does not work for SMC in Flatpak environment. Additionally, it is slower. 

---------------------

Is it your modification? Is BusyBox installed on your OS by default?

**Comment by iopq** [comment]
I installed BusyBox because i wanted to use BusyBox programs, I uninstalled it now to make the system monitor work

you can parse `/proc` directly because that's what all these programs do anyway
