### ISSUE TITLE
Desktop environment version detection problem

### ISSUE THREAD

**Issue by fthaltun** [hakandundar34coding/system-monitoring-center#170]
![1](https://github.com/hakandundar34coding/system-monitoring-center/assets/5893400/f89a7ef4-ff86-474e-a193-ee6306a49598)

**Comment by hakandundar34coding** [comment]
Can you share output of the following command?
`xfce4-panel --version`

**Comment by fthaltun** [comment]
```
xfce4-panel 4.18.2 (Xfce 4.18)

Copyright (c) 2004-2023
	The Xfce development team. All rights reserved.

Please report bugs to <https://gitlab.xfce.org/xfce/xfce4-panel/-/issues>.
```

**Comment by hakandundar34coding** [comment]
The bug is fixed and the source code is updated. There may be a new version in about 1 week.
