### ISSUE TITLE
[Feature Request]  Temps on summary screen

### ISSUE THREAD

**Issue by BetaQuasi** [hakandundar34coding/system-monitoring-center#178]
Hey there.  Fantastic app you have here!  I was wondering if you'd consider (or have already considered) adding temps (CPU package/GPU) to the summary UI somehow?  Perhaps with a similar popout to the left, as used for disk reads/writes and download speeds on the right?

My use case is probably very selfish, however I have this running on a little 13" tablet-style screen and it'd be great to see those temps on the summary UI.  I know GPU temp is in the GPU section of course, and the sensors area has a nice summary of the other temps.

Thanks again for a great application and I hope I'm not being too presumptuous popping a feature request in!

**Comment by hakandundar34coding** [comment]
There is a technical problem:
Getting sensors information requries reading several files and these files are files on disk. They are not virtual filesystem files. This feature would increase CPU usage when Summary tab is open. But system-wide CPU usage, disk speeds are get by reading virtual filesystem files that are not on disk. They are read faster.

**Comment by BetaQuasi** [comment]
I understand, thank you for the response!

**Comment by hakandundar34coding** [comment]
I will close this issue. But you can open a new issue for new features or bug reports.
