### ISSUE TITLE
Update Loop (Flatpak)

### ISSUE THREAD

**Issue by MicHaeL-MonStaR** [hakandundar34coding/system-monitoring-center#181]
I'm on Pop!_OS and it keeps showing up in the Pop!_Shop with the same update every day or multiple times a day.
It's version 2.14.0 of May 19. - No matter how often I let it update, it keeps coming back every day.

**Comment by hakandundar34coding** [comment]
Latest code changes are added for Flatpak update. In other words, the application is updated on Flathub if some new features, performance improvements and bug fixes are added without waiting new version.

What do you think about this update frequency?

**Comment by MicHaeL-MonStaR** [comment]
I see. - I just thought it was stuck in a loop, like I've seen before.
The problem is that the descriptions of the version and "what's new" don't change, so it seems like nothing has changed and it it simply installs the same thing again.

Honestly, I feel it's a bit spammy, because it's pretty much every day. - And while I appreciate the updates, perhaps once a week is enough? - Perhaps you could make it an option in the settings (as in, "check for updates daily/weekly/monthly), but I don't know if the update-check depends on the application or Pop!_Shop/Flathub.

Thanks for clarifying.

**Comment by hakandundar34coding** [comment]
The application is updated (v2.15.0).
The update frequency may be lower for newer versions.

Updates are checked by using Flatpak.
I will close this issue. But you can write additional comments.
