### ISSUE TITLE
The application is not run after the last update

### ISSUE THREAD

**Issue by dCo3lh0** [hakandundar34coding/system-monitoring-center#183]
I did install the latest update by Flatpak and its not launching anymore, here is the terminal error log

> Traceback (most recent call last):
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Main.py", line 18, in on_activate
    from .MainWindow import MainWindow
  File "/app/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 15, in <module>
    from .Performance import Performance
  File "/app/share/system-monitoring-center/systemmonitoringcenter/Performance.py", line 9, in <module>
    from . import Libsysmon
ImportError: cannot import name 'Libsysmon' from 'systemmonitoringcenter' (/app/share/system-monitoring-center/systemmonitoringcenter/__init__.py)

**Comment by dCo3lh0** [comment]
My System is LMDE5 based on Debian 11

**Comment by fstjohn** [comment]
Same problem  I'm running Mint Cinnamon 21.1.  Same error. Removed and reinstalled the app from flathub:
ImportError: cannot import name 'Libsysmon' from 'systemmonitoringcenter' (/app/share/system-monitoring-center/systemmonitoringcenter/__init__.py)

**Comment by dCo3lh0** [comment]
My temporary solution is the flatpak downgrade so installed the second latest commit using the command below.

`sudo flatpak update --commit=61489d6b54712f7b2cea2e093d62d7d94d0f81a7872ccdd2e1d3595659af4ef9 io.github.hakandundar34coding.system-monitoring-center`

**Comment by fstjohn** [comment]
Thanks!  Your solution worked.  Hope it's fixed with the next update.

-----

"There is no need for climate change protests in China because China is already communist."
Powerline



Jun 16, 2023, 11:18 PM by ***@***.***:

**Comment by dCo3lh0** [comment]
in Mint Update Manager, right click the system monitor and select ignore this version

**Comment by hakandundar34coding** [comment]
The latest changes are reverted. It will be installable from Flatpak in about 3-4 hours.

Additionally, the bug will be fixed today.
@dCo3lh0, @fstjohn,
What are the model names of your graphics cards? Did GPU tab worked on your systems (previous versions)?

--------------------------------------

**Update:** The problem is fixed and the application is updated again (Flatpak only). It may be installable in about 4 hours.

**Comment by fstjohn** [comment]
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics vendor: Dell driver: i915
    v: kernel ports: active: DP-1,HDMI-A-2 empty: DP-2,HDMI-A-1,VGA-1 bus-ID: 00:02.0
    chip-ID: 8086:0152
 Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 2966x900 s-dpi: 96
  Monitor-1: DP-1 pos: primary,left model: Acer P186H res: 1366x768 dpi: 85 diag: 470mm (18.5")
  Monitor-2: HDMI-2 mapped: HDMI-A-2 pos: right model: Hannspree HL203DPB res: 1600x900 dpi: 92
    diag: 508mm (20")
  OpenGL: renderer: Mesa Intel HD Graphics 2500 (IVB GT1) v: 4.2 Mesa 22.2.5 direct render: Yes

**Comment by hakandundar34coding** [comment]
@fstjohn,
There is no AMD or NVIDIA GPU on your system.
There is an Intel integrated GPU on my system. There was no errors during tests.

**Comment by fstjohn** [comment]
I installed this morning's update via Update Manager:
Old Version 2.15.1 (bd51ed986a)
New Version 2.15.1 (ba37od6686)
The problem returned.

Jun 17, 2023, 3:42 AM by ***@***.***:

**Comment by fstjohn** [comment]
It occurred to me that a full System Info report might be of assistance, so here it is :
[code]
System:
  Kernel: 5.15.0-75-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.8
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Dell product: OptiPlex 7010 v: 01 serial: <superuser required> Chassis:
    type: 6 serial: <superuser required>
  Mobo: Dell model: 0GY6Y8 v: A02 serial: <superuser required> UEFI: Dell v: A28
    date: 02/22/2018
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse serial: <filter>
    charge: 55% (should be ignored) status: Discharging
CPU:
  Info: quad core model: Intel Core i5-3470 bits: 64 type: MCP arch: Ivy Bridge rev: 9 cache:
    L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 3500 high: 3544 min/max: 1600/3600 cores: 1: 3491 2: 3544 3: 3498 4: 3469
    bogomips: 25540
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics vendor: Dell driver: i915
    v: kernel ports: active: DP-1,HDMI-A-2 empty: DP-2,HDMI-A-1,VGA-1 bus-ID: 00:02.0
    chip-ID: 8086:0152
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 2966x900 s-dpi: 96
  Monitor-1: DP-1 pos: primary,left model: Acer P186H res: 1366x768 dpi: 85 diag: 470mm (18.5")
  Monitor-2: HDMI-2 mapped: HDMI-A-2 pos: right model: Hannspree HL203DPB res: 1600x900 dpi: 92
    diag: 508mm (20")
  OpenGL: renderer: Mesa Intel HD Graphics 2500 (IVB GT1) v: 4.2 Mesa 22.2.5 direct render: Yes
Audio:
  Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1b.0 chip-ID: 8086:1e20
  Sound Server-1: ALSA v: k5.15.0-75-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e v: kernel port: f080
    bus-ID: 00:19.0 chip-ID: 8086:1502
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Realtek RTL88x2bu [AC1200 Techkey] type: USB driver: rtl88x2bu bus-ID: 3-4:3
    chip-ID: 0bda:b812
  IF: wlx54ef33f861df state: up mac: <filter>
  IF-ID-1: wgpia0 state: unknown speed: N/A duplex: N/A mac: N/A
Bluetooth:
  Device-1: Broadcom BCM20702A0 Bluetooth 4.0 type: USB driver: btusb v: 0.8 bus-ID: 1-1.4:5
    chip-ID: 0a5c:21e8
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 2.1 lmp-v: 4.0
    sub-v: 220e
Drives:
  Local Storage: total: 2.95 TiB used: 1.61 TiB (54.7%)
  ID-1: /dev/sda vendor: Kingston model: SV300S37A240G size: 223.57 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-2: /dev/sdb vendor: Hitachi model: HUA722010ALA330 size: 931.51 GiB speed: 3.0 Gb/s
    serial: <filter>
  ID-3: /dev/sdc vendor: Western Digital model: WD1003FBYX-01Y7B1 size: 931.51 GiB
    speed: 3.0 Gb/s serial: <filter>
  ID-4: /dev/sdd type: USB vendor: Samsung model: HD103SI size: 931.51 GiB serial: <filter>
Partition:
  ID-1: / size: 218.51 GiB used: 81.97 GiB (37.5%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 1024 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Full speed or root hub ports: 3 rev: 2.0 speed: 480 Mb/s chip-ID: 1d6b:0002
  Hub-2: 1-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 speed: 480 Mb/s
    chip-ID: 8087:0024
  Hub-3: 1-1.1:3 info: Terminus FE 2.1 7-port Hub ports: 7 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1a40:0201
  Hub-4: 1-1.1.1:6 info: Terminus Hub ports: 4 rev: 2.0 speed: 480 Mb/s chip-ID: 1a40:0101
  Device-1: 1-1.1.1.3:8 info: Logitech Unifying Receiver type: Mouse,HID
    driver: logitech-djreceiver,usbhid rev: 2.0 speed: 12 Mb/s chip-ID: 046d:c52f
  Device-2: 1-1.1.5:7 info: HP OfficeJet 4650 series type: Printer driver: usblp rev: 2.0
    speed: 480 Mb/s chip-ID: 03f0:d911
  Device-3: 1-1.2:4 info: Dell Keyboard SK-8115 type: Keyboard driver: hid-generic,usbhid
    rev: 1.1 speed: 1.5 Mb/s chip-ID: 413c:2003
  Device-4: 1-1.4:5 info: Broadcom BCM20702A0 Bluetooth 4.0 type: Bluetooth driver: btusb
    rev: 2.0 speed: 12 Mb/s chip-ID: 0a5c:21e8
  Hub-5: 2-0:1 info: Full speed or root hub ports: 3 rev: 2.0 speed: 480 Mb/s chip-ID: 1d6b:0002
  Hub-6: 2-1:2 info: Intel Integrated Rate Matching Hub ports: 8 rev: 2.0 speed: 480 Mb/s
    chip-ID: 8087:0024
  Hub-7: 3-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002
  Hub-8: 3-3:2 info: VIA Labs USB2.0 Hub ports: 4 rev: 2.1 speed: 480 Mb/s chip-ID: 2109:2817
  Device-1: 3-3.2:4 info: Iomega USB to ATA/ATAPI bridge type: Mass Storage driver: usb-storage
    rev: 2.0 speed: 480 Mb/s chip-ID: 059b:0475
  Hub-9: 3-3.3:5 info: VIA Labs USB2.0 Hub ports: 4 rev: 2.1 speed: 480 Mb/s chip-ID: 2109:2817
  Device-1: 3-4:3 info: Realtek RTL88x2bu [AC1200 Techkey] type: Network driver: rtl88x2bu
    rev: 2.1 speed: 480 Mb/s chip-ID: 0bda:b812
  Hub-10: 4-0:1 info: Super-speed hub ports: 4 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
  Hub-11: 4-3:2 info: VIA Labs USB3.0 Hub ports: 4 rev: 3.2 speed: 5 Gb/s chip-ID: 2109:0817
  Hub-12: 4-3.3:3 info: VIA Labs USB3.0 Hub ports: 4 rev: 3.2 speed: 5 Gb/s chip-ID: 2109:0817
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2618 apt: 2543 flatpak: 52 snap: 23
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/alessandro-strada-ppa-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/alessandro-strada-ppa-jammy.gpg] https: //ppa.launchpadcontent.net/alessandro-strada/ppa/ubuntu <http://ppa.launchpadcontent.net/alessandro-strada/ppa/ubuntu> jammy main
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [arch=amd64] https: //brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/brostrend.list
    1: deb https: //linux.brostrend.com stable main previous
  Active apt repos in: /etc/apt/sources.list.d/flatpak-stable-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/flatpak-stable-jammy.gpg] https: //ppa.launchpadcontent.net/flatpak/stable/ubuntu <http://ppa.launchpadcontent.net/flatpak/stable/ubuntu> jammy main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ <http://dl.google.com/linux/chrome/deb/> stable main
  Active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list
    1: deb [arch=amd64] http: //dl.google.com/linux/earth/deb/ <http://dl.google.com/linux/earth/deb/> stable main
  No active apt repos in: /etc/apt/sources.list.d/linuxbabe.list
  Active apt repos in: /etc/apt/sources.list.d/megasync.list
    1: deb [signed-by=/usr/share/keyrings/meganz-archive-keyring.gpg] https: //mega.nz/linux/repo/xUbuntu_22.04/ <http://mega.nz/linux/repo/xUbuntu_22.04/> ./
  Active apt repos in: /etc/apt/sources.list.d/microsoft-edge.list
    1: deb [arch=amd64] https: //packages.microsoft.com/repos/edge/ <http://packages.microsoft.com/repos/edge/> stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //mirror.metrocast.net/linuxmint-packages <http://mirror.metrocast.net/linuxmint-packages> vera main upstream import backport
    2: deb http: //mirror.cc.vt.edu/pub2/ubuntu <http://mirror.cc.vt.edu/pub2/ubuntu> jammy main restricted universe multiverse
    3: deb http: //mirror.cc.vt.edu/pub2/ubuntu <http://mirror.cc.vt.edu/pub2/ubuntu> jammy-updates main restricted universe multiverse
    4: deb http: //mirror.cc.vt.edu/pub2/ubuntu <http://mirror.cc.vt.edu/pub2/ubuntu> jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ <http://security.ubuntu.com/ubuntu/> jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/opera-stable.list
    1: deb https: //deb.opera.com/opera-stable/ <http://deb.opera.com/opera-stable/> stable non-free
  No active apt repos in: /etc/apt/sources.list.d/plexmediaserver.list
  Active apt repos in: /etc/apt/sources.list.d/protonvpn-stable.list
    1: deb [arch="all", signed-by=/usr/share/keyrings/protonvpn-stable-archive-keyring.gpg] https: //repo.protonvpn.com/debian <http://repo.protonvpn.com/debian> stable main
  Active apt repos in: /etc/apt/sources.list.d/sebastian-stenzel-cryptomator-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/sebastian-stenzel-cryptomator-jammy.gpg] https: //ppa.launchpadcontent.net/sebastian-stenzel/cryptomator/ubuntu <http://ppa.launchpadcontent.net/sebastian-stenzel/cryptomator/ubuntu> jammy main
  Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https: //updates.signal.org/desktop/apt <http://updates.signal.org/desktop/apt> xenial main
  Active apt repos in: /etc/apt/sources.list.d/team-xbmc-ppa-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/team-xbmc-ppa-jammy.gpg] https: //ppa.launchpadcontent.net/team-xbmc/ppa/ubuntu <http://ppa.launchpadcontent.net/team-xbmc/ppa/ubuntu> jammy main
  Active apt repos in: /etc/apt/sources.list.d/teejee2008-ppa-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/teejee2008-ppa-jammy.gpg] https: //ppa.launchpadcontent.net/teejee2008/ppa/ubuntu <http://ppa.launchpadcontent.net/teejee2008/ppa/ubuntu> jammy main
  Active apt repos in: /etc/apt/sources.list.d/teejee2008-timeshift-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/teejee2008-timeshift-jammy.gpg] https: //ppa.launchpadcontent.net/teejee2008/timeshift/ubuntu <http://ppa.launchpadcontent.net/teejee2008/timeshift/ubuntu> jammy main
  Active apt repos in: /etc/apt/sources.list.d/teejeetech-aptik.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/teejeetech-aptik-keyring.gpg] https: //packages.teejeetech.com/aptik/0/lFQRFOa22d/ubuntu/jammy/amd64 <http://packages.teejeetech.com/aptik/0/lFQRFOa22d/ubuntu/jammy/amd64> stable main
  Active apt repos in: /etc/apt/sources.list.d/teejeetech-baqpaq.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/teejeetech-baqpaq-keyring.gpg] https: //packages.teejeetech.com/baqpaq/qhUl8BW9gD/ubuntu/jammy/amd64 <http://packages.teejeetech.com/baqpaq/qhUl8BW9gD/ubuntu/jammy/amd64> stable main
  No active apt repos in: /etc/apt/sources.list.d/teejeetech-lpt-service-manager.list
  Active apt repos in: /etc/apt/sources.list.d/ubuntu-mozilla-daily-ppa-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu-mozilla-daily-ppa-jammy.gpg] https: //ppa.launchpadcontent.net/ubuntu-mozilla-daily/ppa/ubuntu <http://ppa.launchpadcontent.net/ubuntu-mozilla-daily/ppa/ubuntu> jammy main
Info:
  Processes: 285 Uptime: 1d 3h 28m Memory: 15.53 GiB used: 2.93 GiB (18.9%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11/12 Client: Unknown python3.10 client inxi: 3.3.13
[/code]


Jun 17, 2023, 8:44 AM by ***@***.***:

**Comment by hakandundar34coding** [comment]
@fstjohn,
The bug is fixed. There is a new update and it contains the latest changes.

@dCo3lh0,
Is your graphics card AMD or NVIDIA? Does the GPU tab works?

**Comment by fstjohn** [comment]
Update worked.  Thanks for being on it so swiftly.
You've created a really great app.  

-----

"There is no need for climate change protests in China because China is already communist."
Powerline



Jun 17, 2023, 9:42 AM by ***@***.***:

**Comment by dCo3lh0** [comment]
@fstjohn
My GPU is a Nvidia RTX 2060 (Normal) and The GPU tab is working correctly. Your patch solved with this new version and is working fine.

**Comment by hakandundar34coding** [comment]
@dCo3lh0,
Can you share a screenshot of the GPU tab?

Additionally,
Are there any errors on the terminal window if you run the application by using the following command?
`flatpak run io.github.hakandundar34coding.system-monitoring-center`

**Comment by dCo3lh0** [comment]
![systemmonitorgpu](https://github.com/hakandundar34coding/system-monitoring-center/assets/21119505/bec7f6b3-1d9e-46b5-827b-50ae6594a487)

The application is in portuguese since its my main language, but you can see its working flawlessly, no issues in terminal, not even one.
