### ISSUE TITLE
No GPU usage for amdgpu since version 2.16.0

### ISSUE THREAD

**Issue by kaos-55** [hakandundar34coding/system-monitoring-center#185]
I recently upgraded to version 2.16.1 but I noticed that the gpu usage is not displayed. I downgraded to version 2.15.1 and in that version the gpu usage is displayed. 
I leave the images showing the problem.

Version 2.15.1
![desktop-1](https://github.com/hakandundar34coding/system-monitoring-center/assets/86812371/f0f17b25-53b7-4a2a-aa01-7b25857c0f02)

Version 2.16.1
![desktop-2](https://github.com/hakandundar34coding/system-monitoring-center/assets/86812371/aaba12da-a483-42a8-a837-7c7a07ababfc)

**Comment by hakandundar34coding** [comment]
Can you run the application by using the following command, open GPU tab and share the output?
For Flatpak:
`flatpak run io.github.hakandundar34coding.system-monitoring-center`
For non-Flatpak:
`system-monitoring-center`

**Comment by kaos-55** [comment]
Sure here is.
![monitor2](https://github.com/hakandundar34coding/system-monitoring-center/assets/86812371/c281b4d8-8ae5-4c34-b15b-5a7915d73216)

**Comment by hakandundar34coding** [comment]
I have no AMD GPU.
In the installation directory, in Gpu.py file, at the line 293:
Can you remove this code:
```
            try:
                self.gpu_load_amd_func()
                gpu_load = f'{(sum(self.amd_gpu_load_list) / len(self.amd_gpu_load_list)):.0f} %'
            except Exception:
                gpu_load = "-"
```

and add this code:
```
            self.gpu_load_amd_func()
            gpu_load = f'{(sum(self.amd_gpu_load_list) / len(self.amd_gpu_load_list)):.0f} %'
```

After that can you run the application by using `system-monitoring-center` command and share the output?

**Comment by kaos-55** [comment]
Shows this

`Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 602, in on_main_gui_togglebuttons_toggled
    self.main_gui_tab_switch()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 711, in main_gui_tab_switch
    from .Gpu import Gpu
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Gpu.py", line 293
    self.gpu_load_amd_func()
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 1117, in main_gui_tab_loop
    Gpu.loop_func()
    ^^^
NameError: name 'Gpu' is not defined
`

**Comment by hakandundar34coding** [comment]
There are problems with spaces. Did you copy all of the code in the previous comment?
There have to be 8 spaces at the beginning of the new lines.

Result (after the changes: Line 292, 293, 294):
![smc_gpu](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/4bc14b89-95dd-4689-82da-19146da7b1df)

Here is the modified file. You can change its extension (.txt to .py) and replace the one in the installation directory.
[Gpu.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/11918565/Gpu.txt)

**Comment by kaos-55** [comment]
I use de txt file and change it to py, but i get the same result like the first time

![monitor4](https://github.com/hakandundar34coding/system-monitoring-center/assets/86812371/a05c139c-8da3-455c-ae6c-a69135417fe3)

**Comment by hakandundar34coding** [comment]
I found the problem.

Can you rename and use the attached file?
[Gpu.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/11918628/Gpu.txt)

**Comment by kaos-55** [comment]
Works, now gpu usage is already displayed with the latest fix.

![monitor-fix-1](https://github.com/hakandundar34coding/system-monitoring-center/assets/86812371/50ad7e2f-555a-4007-8cf5-1f522e7beeda)

**Comment by hakandundar34coding** [comment]
Did you compared the GPU usage (v2.15.0 or another versions) with other GPU tools?

**Comment by hakandundar34coding** [comment]
Did you compare the GPU usage (v2.15.0 or another versions) with other GPU tools?

**Comment by kaos-55** [comment]
Yes with radeontop

**Comment by hakandundar34coding** [comment]
Do they show similar results?

---------------------------------

Is it integrated GPU or discrete GPU?
What is shown for Physical RAM size on Memory tab? Is any part of the memory reserved by the GPU?

**Comment by kaos-55** [comment]
Its a integrated GPU with 2GB of memory reserved for the GPU.
And the tests showed a similar result with radeon top 11% of usage with System-monitoring-center 10%

**Comment by hakandundar34coding** [comment]
You have the required changes for the bug.
The application will be updated tomorrow.

**Comment by kaos-55** [comment]
Thanks for fix it.

**Comment by hakandundar34coding** [comment]
v2.17.0 can be installable in about:
- 4 hours from Flatpak
- A few days to a few weeks from other repositories

I will close this issue. But you can open new issues for other bugs.
