### ISSUE TITLE
Not showing system ram or swap ram

### ISSUE THREAD

**Issue by Mereira1** [hakandundar34coding/system-monitoring-center#187]
when i switch to memory tab info about ram was missing
![Screenshot_20230705_185913](https://github.com/hakandundar34coding/system-monitoring-center/assets/138728993/558b569d-e040-4f75-b296-c7f5b5b1d9c3)
![Screenshot_20230705_190051](https://github.com/hakandundar34coding/system-monitoring-center/assets/138728993/416d823d-d236-4108-a6c7-8274aa12d70a)

**Comment by hakandundar34coding** [comment]
The bug is fixed and the application is updated (2.17.2).

It may be downloadable by using:
- Flatpak in about 4 hours
- Other repositories in about 1-2 days or weeks


You can close this issue after testing SMC v2.17.2.
