### ISSUE TITLE
Some python warnings opening the settings/about 3 dots menu...

### ISSUE THREAD

**Issue by dasnoopy** [hakandundar34coding/system-monitoring-center#190]
Hi, just a not critical bug report:

not sure if this is an error generated by the app , but starting it from console terminal , this warning is displayed multiple times when **you open the settings/about menu (3 dots menu)**:

`(python:4660): Gtk-CRITICAL **: 09:46:48.982: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed` 

..btw apparently,  everything seems works fine...

Some system info:

![Screenshot from 2023-07-15 09-54-02](https://github.com/hakandundar34coding/system-monitoring-center/assets/296922/e01ac29a-ecba-468f-b241-5cddabdc10a1)

- system-monitor-center  2.17.3 manually compiled from source ( latest commit)
- Default adwaita  gtk3/4 and gnome shell themes
- no extensions enabled

Regards

**Comment by hakandundar34coding** [comment]
It is printed by GTK on some systems. It may be a bug of GTK4 or its language binding.

The commits after the latest tag contains changes for GPU tab. Currently, these feature are not available in a new version. Are there problems on GPU tab?

**Comment by dasnoopy** [comment]
thanks for your reply ...

About opened bug , after some google search, .it is definitively  a [GTK4 bug](https://discourse.gnome.org/t/menu-button-gives-error-messages-with-latest-gtk4/15689/3),  so I guess issue could be close...

About your related GPU tab question not sure about my answer : my Lenovo T480 has an Intel UHD 620 :  I don't known  if it is supported by the app, because some info are reported but e.g. GPU usage and GPU memory graphs don't display any useful data. 

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/296922/b1576ae8-b153-4f01-ab4d-6aaf9943705d)

App compiled from the [latest commit](https://github.com/hakandundar34coding/system-monitoring-center/commit/f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab)

**Comment by hakandundar34coding** [comment]
Integrated Intel GPUs provide limited information unless intel_gpu_top CLI program (it requires root privileges) is used.

I will close this issue. But you can open a new one for bug reports, new features, etc.
