### ISSUE TITLE
GPU tab provides no stats after GPU memory, encoding, decoding load graphics are added

### ISSUE THREAD

**Issue by yochananmarqos** [hakandundar34coding/system-monitoring-center#192]
I just updated to 2.18.0 and the GPU tab shows nothing for both my integrated Intel graphics and decidated NVIDIA graphics on a hybrid laptop. Note that I have external monitors connected, so the Intel graphics are not used at all.

<details>
<summary>inxi -Gazy</summary>

```
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics vendor: CLEVO/KAPOK
    driver: i915 v: kernel arch: Gen-12.2 process: Intel 10nm built: 2021-22+
    ports: active: DP-2 off: eDP-2 empty: DP-3,DP-4,DP-5 bus-ID: 00:02.0
    chip-ID: 8086:46a6 class-ID: 0300
  Device-2: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q]
    vendor: CLEVO/KAPOK driver: nvidia v: 535.54.03 alternate: nouveau,nvidia_drm
    non-free: 535.xx+ status: current (as of 2023-07) arch: Ampere code: GAxxx
    process: TSMC n7 (7nm) built: 2020-22 pcie: gen: 2 speed: 5 GT/s lanes: 8
    link-max: gen: 4 speed: 16 GT/s lanes: 16 ports: active: none
    off: DP-1,HDMI-A-1 empty: eDP-1 bus-ID: 01:00.0 chip-ID: 10de:2520
    class-ID: 0300
  Device-3: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
    rev: 2.0 speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 3-1.1:4
    chip-ID: 046d:0825 class-ID: 0102 serial: <filter>
  Device-4: Chicony USB2.0 Camera driver: uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 3-8:5 chip-ID: 04f2:b729
    class-ID: fe01 serial: <filter>
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.2
    compositor: gnome-shell v: 44.3 driver: X: loaded: modesetting,nvidia
    alternate: fbdev,nouveau,nv,vesa dri: iris gpu: i915,nvidia,nvidia-nvswitch
    display-ID: :1 screens: 1
  Screen-1: 0 s-res: 5760x1080 s-dpi: 96 s-size: 1524x286mm (60.00x11.26")
    s-diag: 1551mm (61.05")
  Monitor-1: DP-1 note: disabled pos: primary,center model: MSI G27C4
    serial: <filter> built: 2020 res: 1920x1080 dpi: 82 gamma: 1.2
    size: 598x336mm (23.54x13.23") diag: 686mm (27") ratio: 16:9 modes:
    max: 1920x1080 min: 640x480
  Monitor-2: DP-2 mapped: DP-1-2 pos: right model: HP X24ih serial: <filter>
    built: 2021 res: 1920x1080 dpi: 93 gamma: 1.2 size: 527x297mm (20.75x11.69")
    diag: 605mm (23.8") ratio: 16:9 modes: max: 1920x1080 min: 720x400
  Monitor-3: HDMI-A-1 mapped: HDMI-0 note: disabled pos: left model: HP X24ih
    serial: <filter> built: 2021 res: 1920x1080 dpi: 93 gamma: 1.2
    size: 527x297mm (20.75x11.69") diag: 605mm (23.8") ratio: 16:9 modes:
    max: 1920x1080 min: 640x480
  Monitor-4: eDP-2 mapped: eDP-1-2 note: disabled model: AU Optronics 0xaf90
    built: 2020 res: 1920x1080 dpi: 142 gamma: 1.2 size: 344x193mm (13.54x7.6")
    diag: 394mm (15.5") ratio: 16:9 modes: 1920x1080
  API: OpenGL v: 4.6.0 NVIDIA 535.54.03 renderer: NVIDIA GeForce RTX 3060
    Laptop GPU/PCIe/SSE2 direct-render: Yes
```

</details>

```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 950, in on_row_activated
    Gpu.loop_func()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Gpu.py", line 609, in loop_func
    gpu_load_memory_frequency_power_dict = Libsysmon.get_gpu_load_memory_frequency_power(gpu_pci_address, device_vendor_id, selected_gpu_number, gpu_list, gpu_device_path_list, gpu_device_sub_path_list)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 2641, in get_gpu_load_memory_frequency_power
    Thread(target=gpu_load_nvidia_func, daemon=True).start()
    ^^^^^^
NameError: name 'Thread' is not defined
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 1127, in main_gui_tab_loop
    Gpu.loop_func()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Gpu.py", line 609, in loop_func
    gpu_load_memory_frequency_power_dict = Libsysmon.get_gpu_load_memory_frequency_power(gpu_pci_address, device_vendor_id, selected_gpu_number, gpu_list, gpu_device_path_list, gpu_device_sub_path_list)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 2641, in get_gpu_load_memory_frequency_power
    Thread(target=gpu_load_nvidia_func, daemon=True).start()
    ^^^^^^
NameError: name 'Thread' is not defined
```

**Comment by hakandundar34coding** [comment]
Can you add `threading.` at the beginng of the line and try again?
Line:
`Thread(target=gpu_load_nvidia_func, daemon=True).start()`

**Comment by hakandundar34coding** [comment]
Can you add `threading.` at the beginng of the line and try again?
But do not remove empty spaces at the beginning of the line.
Line 2641 in Libsysmon.py file:
`Thread(target=gpu_load_nvidia_func, daemon=True).start()`

Can you share screenshots for both GPUs if it works?

Note: Integrated Intel GPUs provide limited information in its directories.

**Comment by yochananmarqos** [comment]
Like this?

```
threading.Thread(target=gpu_load_nvidia_func, daemon=True).start()
```

That produces no output, however there are still no stats at all.

**Comment by hakandundar34coding** [comment]
What about Intel GPU?

**Comment by yochananmarqos** [comment]
>  there are still no stats at all.

:wink:

**Comment by hakandundar34coding** [comment]
Can you share output of this command?
`nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,utilization.encoder,utilization.decoder,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics,clocks.current.memory,clocks.max.memory,power.draw,power.limit --format=csv`

**Comment by yochananmarqos** [comment]
```
name, pci.bus_id, driver_version, utilization.gpu [%], utilization.memory [%], utilization.encoder [%], utilization.decoder [%], memory.total [MiB], memory.free [MiB], memory.used [MiB], temperature.gpu, clocks.current.graphics [MHz], clocks.max.graphics [MHz], clocks.current.memory [MHz], clocks.max.memory [MHz], power.draw [W], power.limit [W]
NVIDIA GeForce RTX 3060 Laptop GPU, 00000000:01:00.0, 535.54.03, 0 %, 1 %, 0 %, 0 %, 6144 MiB, 4821 MiB, 1116 MiB, 42, 472 MHz, 2100 MHz, 6000 MHz, 7001 MHz, 22.82 W, [N/A]
```

**Comment by hakandundar34coding** [comment]
Can you follow these steps?

- Download [this](https://github.com/hakandundar34coding/system-monitoring-center/archive/f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab.zip) source code (before some code changes)
- Extract it and open terminal in `src` folder
- Run this command: `python3 ./run_from_source.py`
- Share the result

The last version may be deleted.

**Comment by yochananmarqos** [comment]
There are some stats now, however GPU & Memory usage is not populating:

card1 (Intel):

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/4abf5c18-81a8-4dc2-a9b9-afb4329797f0)

card0 (NVIDIA):

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/000bbff4-1d5d-4bf1-aae4-0e090e7073ff)



Output clicking on card0 (NVIDIA):

```
Traceback (most recent call last):
  File "/home/yochanan/tmp/system-monitoring-center-f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab/src/MainWindow.py", line 950, in on_row_activated
    Gpu.loop_func()
  File "/home/yochanan/tmp/system-monitoring-center-f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab/src/Gpu.py", line 253, in loop_func
    gpu_load_memory_frequency_power_dict = Libsysmon.get_gpu_load_memory_frequency_power(gpu_pci_address, device_vendor_id, selected_gpu_number, gpu_list, gpu_device_path_list, gpu_device_sub_path_list)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yochanan/tmp/system-monitoring-center-f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab/src/Libsysmon.py", line 2641, in get_gpu_load_memory_frequency_power
    Thread(target=gpu_load_nvidia_func, daemon=True).start()
    ^^^^^^
NameError: name 'Thread' is not defined
Traceback (most recent call last):
  File "/home/yochanan/tmp/system-monitoring-center-f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab/src/MainWindow.py", line 1127, in main_gui_tab_loop
    Gpu.loop_func()
  File "/home/yochanan/tmp/system-monitoring-center-f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab/src/Gpu.py", line 253, in loop_func
    gpu_load_memory_frequency_power_dict = Libsysmon.get_gpu_load_memory_frequency_power(gpu_pci_address, device_vendor_id, selected_gpu_number, gpu_list, gpu_device_path_list, gpu_device_sub_path_list)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yochanan/tmp/system-monitoring-center-f3e6fc0c2492f7c7c090ce4158f0d7a72f5eccab/src/Libsysmon.py", line 2641, in get_gpu_load_memory_frequency_power
    Thread(target=gpu_load_nvidia_func, daemon=True).start()
    ^^^^^^
NameError: name 'Thread' is not defined
```

**Comment by hakandundar34coding** [comment]
Finally, can you add `threading.` again?
Line:
`Thread(target=gpu_load_nvidia_func, daemon=True).start()`

**Comment by hakandundar34coding** [comment]
Can you test SMC v2.18.1?

**Comment by yochananmarqos** [comment]
card1 (Intel):

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/6ec257f2-3773-4509-99b7-b114f431e0a8)
![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/795efff4-e2a1-4b27-8160-e5117918d25a)

card0 (NVIDIA):
![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/b76f47c9-9862-4bb4-a313-456cf6d3037b)
![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/a81c99cf-7713-40d4-9022-062661071ed3)



Output clicking on card0 (NVIDIA):

```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 950, in on_row_activated
    Gpu.loop_func()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Gpu.py", line 609, in loop_func
    gpu_load_memory_frequency_power_dict = Libsysmon.get_gpu_load_memory_frequency_power(gpu_pci_address, device_vendor_id, selected_gpu_number, gpu_list, gpu_device_path_list, gpu_device_sub_path_list)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 2649, in get_gpu_load_memory_frequency_power
    gpu_load_memory_frequency_power_dict = process_gpu_tool_output_nvidia(gpu_pci_address)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Libsysmon.py", line 3117, in process_gpu_tool_output_nvidia
    if gpu_tool_output != "-":
       ^^^^^^^^^^^^^^^
NameError: name 'gpu_tool_output' is not defined
```

**Comment by hakandundar34coding** [comment]
> [Note:](https://github.com/hakandundar34coding/system-monitoring-center/issues/192#issuecomment-1637165753) Integrated Intel GPUs provide limited information in its directories.

There will not be improvements for integrated Intel GPUs.

---------------------------------------------

[This bug](https://github.com/hakandundar34coding/system-monitoring-center/issues/192#issuecomment-1637204322) is also fixed. Currently, there is no new version. Probably, the error is printed one time. But it does not affect the GPU information shown.

---------------------------------------------

But Max GPU power is not shown. Only current power consumption is shown.

Can you share output of these commands?

`nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,utilization.encoder,utilization.decoder,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics,clocks.current.memory,clocks.max.memory,power.draw,power.limit,power.limit.enforced --format=csv`


`nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,utilization.encoder,utilization.decoder,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics,clocks.current.memory,clocks.max.memory,power.draw,power.limit,enforced.power.limit --format=csv`

**Comment by yochananmarqos** [comment]
```
Field "power.limit.enforced" is not a valid field to query.
```

```
name, pci.bus_id, driver_version, utilization.gpu [%], utilization.memory [%], utilization.encoder [%], utilization.decoder [%], memory.total [MiB], memory.free [MiB], memory.used [MiB], temperature.gpu, clocks.current.graphics [MHz], clocks.max.graphics [MHz], clocks.current.memory [MHz], clocks.max.memory [MHz], power.draw [W], power.limit [W], enforced.power.limit [W]
NVIDIA GeForce RTX 3060 Laptop GPU, 00000000:01:00.0, 535.54.03, 3 %, 2 %, 0 %, 0 %, 6144 MiB, 4777 MiB, 1160 MiB, 39, 465 MHz, 2100 MHz, 6000 MHz, 7001 MHz, 21.95 W, [N/A], 80.00 W
```

**Comment by hakandundar34coding** [comment]
Can you test the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code?

Can you share this information?

- GPU tab and GPU details window screenshots (NVIDIA)
- Is there increase on Video Decoding graph if a video is played?
- Terminal output (if there are errors)

**Comment by yochananmarqos** [comment]
There were no errors.

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/96c87091-0eb7-4aa7-9c1c-f34e65e8fc9d)

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/4751cce7-a79d-4091-8bdd-fbee2fa083b0)

**Comment by hakandundar34coding** [comment]
Can you try again?

**Comment by yochananmarqos** [comment]
:+1: 

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/efba69b7-3594-4aaa-a103-34712023a851)

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/5437803/633b048d-b640-473e-9828-21e0bc526dee)

**Comment by hakandundar34coding** [comment]
What about decoding engine during a video playing?

**Comment by yochananmarqos** [comment]
The Video Encoder / Decoder graphs do not show anything while nvtop does.

**Comment by hakandundar34coding** [comment]
Can you share output of the following commands?
You can share only elapsed time output parts (last 3-4 lines) of them.

A lot of new parameters added. I do not know if running the command requires long time.
I did not learn the result from [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/189) thread.


- For elapsed time value:

`time nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,utilization.encoder,utilization.decoder,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics,clocks.current.memory,clocks.max.memory,power.draw,power.limit --format=csv`

- For elapsed time value:

`time nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics,power.draw --format=csv`

**Comment by hakandundar34coding** [comment]
You can write here if you are bored. Decoding/encoding load bugs may be fixed in another version when another user provides outputs. My GPU is very old and it does not support lots of features because of the driver. GPU tab changes very rare. Because it is one of the hardest part of the application. There were very detailed changes this time. There are a lot of GPUs, models.

**Comment by yochananmarqos** [comment]
```
name, pci.bus_id, driver_version, utilization.gpu [%], utilization.memory [%], utilization.encoder [%], utilization.decoder [%], memory.total [MiB], memory.free [MiB], memory.used [MiB], temperature.gpu, clocks.current.graphics [MHz], clocks.max.graphics [MHz], clocks.current.memory [MHz], clocks.max.memory [MHz], power.draw [W], power.limit [W]
NVIDIA GeForce RTX 3060 Laptop GPU, 00000000:01:00.0, 535.54.03, 8 %, 11 %, 0 %, 0 %, 6144 MiB, 4923 MiB, 1014 MiB, 42, 390 MHz, 2100 MHz, 810 MHz, 7001 MHz, 18.32 W, [N/A]
nvidia-smi  --format=csv  0.00s user 0.01s system 54% cpu 0.013 total
```

```
name, pci.bus_id, driver_version, utilization.gpu [%], utilization.memory [%], memory.total [MiB], memory.free [MiB], memory.used [MiB], temperature.gpu, clocks.current.graphics [MHz], clocks.max.graphics [MHz], power.draw [W]
NVIDIA GeForce RTX 3060 Laptop GPU, 00000000:01:00.0, 535.54.03, 1 %, 1 %, 6144 MiB, 4907 MiB, 1030 MiB, 42, 510 MHz, 2100 MHz, 22.97 W
nvidia-smi  --format=csv  0.00s user 0.00s system 48% cpu 0.011 total
```

**Comment by hakandundar34coding** [comment]
> 0.013 total

vs

> 0.011 total

There is no big change.

--------------------------

What is reported if you use this command during video playback?

`nvidia-smi --query-gpu=utilization.encoder,utilization.decoder --format=csv`

--------------------------

Does nvtop require root privileges for getting Intel GPU information?

**Comment by yochananmarqos** [comment]
> What is reported if you use this command during video playback?
> 
 > nvidia-smi --query-gpu=utilization.encoder,utilization.decoder --format=csv

Sorry, turns out I'm not seeing any Encoder / Decoder activity at all. If I remember correctly, MPV needs to be configured manually to use GPU acceleration. I used to have it working in Chromium based browsers, but I've given up on fiddling. Any suggestions?

> Does nvtop require root privileges for getting Intel GPU information?

No.

**Comment by hakandundar34coding** [comment]
There may be problems about nvidia-smi. Video decoding load changes if a video it watched (by using hardware acceleration from web browser, from HDD, etc.). Maybe other GPU is used. I do not know.

Currently there is no code change. nvidia-smi decoding/encoding information is directly shown on the GUI. It looks like it is get as 0.

You can close this issue. Or you can keep it opened if you want to listen different suggestions about this decoding load issue.

---------------------------

Additionally, after some time, a tool like nvtop may be used for getting more detailed GPU information. This depends on popularity of the application.

**Comment by yochananmarqos** [comment]
As far as this issue is concerned, it was addressed and working well, thank you.

**Comment by hakandundar34coding** [comment]
You can open new issues for bugs, new features, etc.

After adding another GPU tool for getting GPU information, fixing GPU releated problems may not be that difficult.
Currently, Sytem Monitoring Center uses its code for these features.

----------------------------------------------------

`xrandr` dependency is not required for SMC v2.
