### ISSUE TITLE
Summary with a little history: second summary view with graphs

### ISSUE THREAD

**Issue by w-sky** [hakandundar34coding/system-monitoring-center#193]
Hi, I especially like the Summary view of System Monitoring Center because of its nice graphics, but I really miss from this view a quick insight about what happened during the last 30 seconds or so – like all graph views do.

I suggest to add a second Summary view with a smaller speedometer and also 1 CPU graph that shows all cores in different colors, 1 Disk usage graph that shows R+W usage of all drives in different colors, same for network and temperature.

So it would be 4 intense graphs with legends and a speedometer in one view. Is it possible?

**Comment by hakandundar34coding** [comment]
I thought about adding usage history graphs to the Summary tab. But this would require a lot of space. Additionally, Summary tab graphics would be very complex.

There may be changes for adding usage histories (maybe 10-20 data points). A second summary tab would be confusing.
But there may be an option for selecting different gauges. Another gauge design may contain usage histories.
Adding this feature may not be in a short time. Designing these graphics and coding it is not easy.

You can write here if you have design ideas for a new Summary tab graphics.
I asked a similar question to @cassiofb-dev in this [comment](https://github.com/hakandundar34coding/system-monitoring-center/issues/189#issuecomment-1637159902). It was for a GPU load indicator.

**Comment by BujuArena** [comment]
Having all the graphs visible while looking at the process list like Process Explorer has would be nice.  Also having graph columns for per-process graphs in the process list, also like Process Explorer, would be good.  If you haven't tried Process Explorer on Windows, I think it's worthwhile to be able to see the GUI design of the most useful system monitoring tool that's available for any system I've used.  Any effort spent to move toward Process Explorer's design is effort well-spent.

Edit: To clarify, I'm referring to [this tool](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer).

**Comment by hakandundar34coding** [comment]
Graphs per-process on the Processes tab would require high CPU usage. Python language would require more CPU usage when compared to some other languages. There are no plans for this feature.

But CPU, memory, disk and network usage information of system is shown on the window titlebar.

**Comment by BujuArena** [comment]
They wouldn't require high CPU usage.  Process Explorer has had that feature since at least 2005.

**Comment by hakandundar34coding** [comment]
> They wouldn't require high CPU usage. Process Explorer has had that feature since at least 2005.

As you know, there are some factors such as Python, Flatpak, etc.
Another user wrote about the same feature (graphs per-process) in one of the issues. I wrote about CPU consumption of the application.

SMC may be rewritten in another language and by using another GUI toolkit. But this requires some time.

**Comment by hakandundar34coding** [comment]
Details are written in [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/193#issuecomment-1640209518) comment.

I will close this issue. You can write additional comments or open new issues for bugs, new features, etc.
