### ISSUE TITLE
@systemd "user" services not included in the impressions

### ISSUE THREAD

**Issue by badcast** [hakandundar34coding/system-monitoring-center#196]
I may not have noticed these settings, please tell me how to do it, I will be grateful. And then some user services work for me and I found out about it later.
I noticed that the Services tab does not display user services. I use systemd and when calling
```
systemctl list-units --user
```
shows the services started by the user.

NOTICE: User services located at 
```$HOME/.config/systemd/user```

**Comment by badcast** [comment]
Previews
![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/8d83b7b2-d8c0-4ef1-844a-c956ee1274eb)
![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/164291c9-b56e-4e6f-a8a6-b871eb6255a9)

**Comment by hakandundar34coding** [comment]
There will be improvements for user services.
Can you share output of the following commands?
```
ls  $HOME/.config/systemd/user
ls  $HOME/.config/systemd
```

**Comment by badcast** [comment]
> There will be improvements for user services. Can you share output of the following commands?
> 
> ```
> ls  $HOME/.config/systemd/user
> ls  $HOME/.config/systemd
> ```
I am providing you with the data
```
ls -la  $HOME/.config/systemd/user

lrwxrwxrwx 9 badcast 21 Jul 23:52 app-org.kde.discover.notifier@autostart.service -> /dev/null
drwx------ - badcast 28 Jun 00:18 default.target.wants
lrwxrwxrwx 9 badcast 22 Jul 00:00 gpg-agent.service -> /dev/null
lrwxrwxrwx 9 badcast 22 Jul 00:00 kde-baloo.service -> /dev/null
drwx------ - badcast 28 Jun 00:18 sockets.target.wants
```
```
ls -la $HOME/.config/systemd

drwx------ - badcast 22 Jul 00:00 user
```

**Comment by hakandundar34coding** [comment]
There will be improvements for this feature after some time. Because I will be away from my computer for a week.
You can write additional comments.

**Comment by hakandundar34coding** [comment]
Can you follow these steps?

- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open terminal in `src` folder
- Run this command: `python3 ./run_from_source.py`
- Open Services tab and check user services
- Share errors in the terminal output

**Comment by badcast** [comment]
Yes. User services have appeared. Now, as I believe, the program is close to ideal and monitoring.
Errors and log is empty from terminal source.

**Comment by hakandundar34coding** [comment]
🚀
> Yes. User services have appeared.

You can open new issues for bugs, new features, etc.
