### ISSUE TITLE
An Option For Showing Running Applications In A Group On Processes Tab

### ISSUE THREAD

**Issue by docop** [hakandundar34coding/system-monitoring-center#20]
Hi  First, need to say this is a very very great soft ! To get full detail of process and the description of service is very nice.
 I would like to know if maybe a small button or option could be add in order to get : all open soft group together ?  Like instead of scrolling in all the list to finally find/see the icon of the soft.  That could be quite great.

Thanks in advance

**Comment by hakandundar34coding** [comment]
Do you want to see something like that?

On the ```Processes``` tab:
- A group of working applications together (on the top of the list).
- And other processes after this applications group.

**Comment by docop** [comment]
Heyy your the man. indeed well explain. this could be very great to see quickly .. if we got like a flatpak soft frozen.

**Comment by hakandundar34coding** [comment]
You can read the answer on this link which is about Flatpak release of the application:
```https://github.com/hakandundar34coding/system-monitoring-center/issues/15#issuecomment-999478673```

About grouping the applications:
I have thought about this feature before. But all working applications may not be listed in this group.
To do that the working applications should have ```.desktop``` files under ```/usr/share/applications``` directory. Several user applications have these files.
Grouping them may consume additional CPU resources.

Maybe a filtering button can be added for this feature. This button can show only running processes.

**Comment by docop** [comment]
or simply a filter with the <icon>  as all running soft on the user are with an icon, the rest is kind of back-end. but opening terminal and it frooze.. or other app.. it's faster to get all together.
  As the flatpak, i only used Appimage that is working fine and need to kill most of time bad flatpak. Having an Appimage can made your soft fully portable too.

**Comment by hakandundar34coding** [comment]
Using ```.desktop``` files is not enough for this feature. Some system applications will be shown as user applications in this situation.

All opened windows should be get by using ```Wnck``` library and  running appplications can be matched with these windows. But there is another problem. As far as I know, opened windows can not be get on systems with ```Wayland``` windowing system. It works on systems with ```X11``` windowing system. I do not know if others support this feature.

I will not add this feature because it will not work on several systems if this method is used.

I am closing this issue but you can write comment if you want to write something about this feature or you can open another issue if you want to write something different.

**Comment by docop** [comment]
Hi i see, but was it it more easier just to get <group> by the icon. As open software do have icon show in the process list. like firefox show the firefox logo, not a gear like all other process.
 So if icon detect = group them at top of list , or with a filter button..

**Comment by hakandundar34coding** [comment]
If this feature relies on only icons also some of the system applications will be shown near firefox, etc. This is same as reading ```.desktop``` files. This method does not work accurately. 
Some users may say that:
"Show only applications option/filter" also shows some system programs."

Some examples for the applications will be shown as applications with opened windows (like firefox):
```
evolution-alarm-notify
ibus-extension-gtk3
NetworkManager
nm-applet
```

These programs also have icons. On some systems there are more running system programs which have icons.

Currently, System Monitoring Center does not show icons of some of the some system applications/programs. This number may be increased in the newer releases.


Have you tried to ```disable/uncheck``` this option?

![system_monitoring_center_all_processes](https://user-images.githubusercontent.com/90193017/152736163-f31c1964-e09c-40bd-b352-099ec47ec06d.png)

Number of listed processes will be reduced. For example there are 216 processes but 62 of the are owned by the current user.

Or you can use another filtering button ```Show processes from this user```. This change is not saved.
![system_monitoring_center_all_processes2](https://user-images.githubusercontent.com/90193017/152738445-d2a8b4a1-0db2-4b80-be6a-59eaf8eb39be.png)

Also you can use ```search``` feature to find a specific application.

They are not the same thing but currently there are some difficulties to show only running applications or group them together.

**Comment by docop** [comment]
Thanks, i will follow your update. But still, having the list grouping all icon together can be nice to quickly filter.. like win8,win10. Like app process, open firefox, mousepad, gimp ,, and all see by icon and not with 8-13 other process. Or perhaps Collapse by group. like : gvfsd alone bring about 20 process with same start name. Have a kind of sub level tree could be something maybe.
