### ISSUE TITLE
Processes are not shown if the sorting column is removed

### ISSUE THREAD

**Issue by BujuArena** [hakandundar34coding/system-monitoring-center#201]
## Steps to reproduce

1. View the process list.
2. Click a column to sort by that column.
3. Disable that column in the "Add/Remove Columns" editor.
4. Enable that column in the "Add/Remove Columns" editor.

## Observed behavior

- After step 3 in the steps to reproduce, the list of processes became blank.
- After step 4 in the steps to reproduce, the list of processes was restored, but the entire list was no longer being updated with new information at regular intervals.
- The only workaround found was to restart the entire program.

## Expected behavior

Removing the column that is being used for sorting is expected to:

- leave all processes visible in the process list,
- pick any other column for sorting (no preference on how to decide which column), and
- continue to update the processes with new information at regular intervals.

**Comment by hakandundar34coding** [comment]
The bug is fixed and the source code is updated. SMC v2.20.0 will include this change.

**Comment by hakandundar34coding** [comment]
The bug is fixed and the source code is updated. SMC v2.20.0 may be downloadable from:

- Flathub in about 4 hours
- Other repositories in about a few days/weeks
