### ISSUE TITLE
After changing CPU precision, settings menu can no longer be closed by using mouse input

### ISSUE THREAD

**Issue by BujuArena** [hakandundar34coding/system-monitoring-center#202]
## Steps to reproduce

1. Navigate to the CPU menu.
2. Open the settings menu by clicking its button in the bar near the top of the GUI.
3. Change the CPU precision by opening the dropdown list and selecting a different option.
4. Try to close the options menu by using only mouse input.
  - Some attempted ways:
    - focusing a different program
    - clicking the settings menu button again
    - clicking inside the program's visual GUI boundaries but outside the settings menu's visual GUI boundaries
    - clicking the "Reset" button inside the settings menu

## Observed behavior

- After changing the CPU precision by opening the dropdown list and selecting a different option, the settings menu can no longer be closed by using mouse input.
- Other parts of the program were only partially responsive to mouse input.
  - Hovering over various GUI elements and even clicking on GUI buttons reacted with color-changing animations, but did not navigate to other menus or close the settings menu.
- Even changing focus to another program left the settings menu visible, above the other focused program, as shown in a screenshot below this.
- Only pressing the escape key on the keyboard could close the settings menu.

![image](https://github.com/hakandundar34coding/system-monitoring-center/assets/601517/6608505f-e233-4429-864b-e78da459aa29)

## Expected behavior

- The settings menu is expected to close if a mouse button is pressed while the cursor is pointing anywhere outside the settings menu's visual GUI boundaries.
- Clicking on other GUI elements outside the settings menu while it is open is expected to cause those GUI elements to react in the same way as if the settings menu was already closed.

**Comment by hakandundar34coding** [comment]
It is a GTK4 bug. As far as I know it affects some other applications. There was a GTK4 issue for this bug.

Other menus of SMC are also affected.

Popover menus are not closed by using mouse buttons if DropDown widgets on these menus are used.

You can use `Esc` button for closing them in this situation.

I will close this issue. But you can open new issues for new features, bugs, etc.

**Comment by BujuArena** [comment]
Is [this](https://gitlab.gnome.org/GNOME/gtk/-/issues/5568) the issue ticket you mean?

**Comment by hakandundar34coding** [comment]
> Is [this](https://gitlab.gnome.org/GNOME/gtk/-/issues/5568) the issue ticket you mean?

It maybe the issue you wrote or a linked issue in the same issue. I found the issue when SMC v2 was new.

**Comment by hakandundar34coding** [comment]
> Is [this](https://gitlab.gnome.org/GNOME/gtk/-/issues/5568) the issue ticket you mean?

It maybe the issue you wrote or a linked issue in the same issue. I found the issue when SMC v2 was new (several months ago).

There were some new GTK4 versions for fixing bugs. But this bug is not fixed. Currently, GTK v4.10.4 is used for Flatpak version of SMC.
