### ISSUE TITLE
CPU graph does not change when different CPU cores are selected

### ISSUE THREAD

**Issue by alr888rav** [hakandundar34coding/system-monitoring-center#205]
All the CPUs (cpu0, cpu1…) has the same CPU usage graph. I doubt that it's correct.
It seems to me that several versions earlier it was correct.
PS version 2.20.1

**Comment by badcast** [comment]
Could you please tell us more or offer a link to how it could be. So that we can imagine it better. 
Thank you in advance.

**Comment by hakandundar34coding** [comment]
Selecting CPU cores does not affect CPU usage graph. It affects CPU frequencies and cache values. Currently, some new CPU models have different CPU cache values.

You can use `CPU Usage (Per Core)` option for viewing CPU usages of all cores.

Screenshots:

![smc_cpu_menu](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/e9812831-4abb-474d-9f1a-649df50742e0)

![cpu_tab_per_core_dark_system_theme](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/0605f492-1c46-4be0-9dce-4834030de7f2)


--------------------------------

@badcast,
A issue about GPU bugs is deleted. There was a lot of users and new comments are written to this issue. Asking questions, writing answers may confuse some users. A lot of users get notifications of different bugs.

About Intel GPU information problem:
Currently, getting GPU performance of integrated Intel GPUs require root privileges. It looks like there are other ways to get information of these GPUs on some new kernels. There may be improvements for this feature in new versions of the application.

--------------------------------

You can open new issues for new features, bugs, etc.
