### ISSUE TITLE
When "Show processes using max CPU" is enabled and a tab other than "Performance" is focused, the process with the highest CPU is not recorded

### ISSUE THREAD

**Issue by BujuArena** [hakandundar34coding/system-monitoring-center#207]
## Steps to reproduce

1. Navigate to the "Performance" tab.
2. Enable "Show processes using max CPU".
3. Hover over the CPU usage graph to view which process was using the highest CPU at that time in the graph.
4. Navigate to another tab, like "Processes".
5. Wait a few seconds, like 5 to 10.
6. Navigate back to the "Performance" tab.
7. Hover over various parts of the CPU usage graph, especially near the right side, to find which processes were using the highest CPU at the times hovered in the graph.

## Observed behavior

- When "Show processes using max CPU" is enabled and a tab other than "Performance" is focused, the process with the highest CPU is not recorded.
  - When this happens, the process with the highest CPU usage is shown as "-" instead of the process name.

## Expected behavior

- When "Show processes using max CPU" is enabled, the process with the highest CPU usage is expected to always be recorded for retroactive troubleshooting.
  - The whole point of that feature is to be able to figure out retroactively which process may have caused a spike in the CPU usage, so if there are times when it's not recorded, the feature does not work.

## Additional commentary

A program which has the same feature as this, but for Microsoft Windows, is Process Explorer.  That program always records which process has the highest usage in any of its graphs, even if the program is minimized to the system tray.

**Comment by hakandundar34coding** [comment]
The behavior of this feature will be changed in the next version. Alternatively, there may be a second option for tracking processes in the background.

**Comment by hakandundar34coding** [comment]
The source code is updated. Max. CPU using processes are tracked in background after the latest changes. The application may be updated in Flatpak repository in about 4 hours. The version number did not change. There may be a new version in about one week.

You can write additional comments if there are problems about this feature.
