### ISSUE TITLE
Option to export the system information to social media compatible format

### ISSUE THREAD

**Issue by TerohsLab** [hakandundar34coding/system-monitoring-center#213]
I was wondering if it would be possible to add buttons to the System tab that exports the system information in a format that could be easily posted on reddit for example. With reddit markup applied.

Use case would be : People asking what your specs are.

Basically like a more in depth neofetch.

Would personally love to see a "short" version for reddit ( with reddit markup option ) and a option to full dump to pastebin ( with an option to remove privacy critical parts like IP addresses and such ).

Keep up the good work. Love this little app!

**Comment by hakandundar34coding** [comment]
Currently, there are no plans for features that require internet connection because of security reasons.

I will close this issue. But you can open new issues for bugs, new features, etc.

**Comment by BujuArena** [comment]
I'm not the person who made this feature request, but I can see that this feature request does not require an internet connection.  It is a request for formatting data into a text-based format, optionally including or excluding markdown formatting.

**Comment by hakandundar34coding** [comment]
Adding a window for system summary may be evaluated for one of the new versions of the application.
This window can be accessed from main menu of the application.
Text on this window may be selectable.
Probably, text formatting options will not be added because of additonal complexity.

**Comment by TerohsLab** [comment]
The big problem is that this information showed in the system window can not be shared easily.

And people on internet forums need to know your system components to help you with problems.

So a easy way to get all the information in the system window into text form would be nice.

**Comment by BujuArena** [comment]
>Adding a window for system summary may be evaluated for one of the new versions of the application.
>This window can be accessed from main menu of the application.
>Text on this window may be selectable.
>Probably, text formatting options will not be added because of additonal complexity.

Just putting the text directly into the clipboard would suffice for most users.  That way, you wouldn't have to design and maintain a new GUI menu for a text preview of this, as clipboard managers like CopyQ already have that.

**Comment by hakandundar34coding** [comment]
A window for previewing the information will also be added if the feature is added.
There may be a button for copying the information to the clipboard.

**Comment by hakandundar34coding** [comment]
More details (CPU, memory, GPU, resolution) are added to System tab. Users can take screenshot of this tab for system summary. A screenshot button is not added. It looks like there are some changes for pixbuf library (it is a dependency of GTK) for getting window screenshot. Some methods are not usable for GTK4.

Screenshot of the System tab:
![smc_system](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/3738d004-6239-4bec-8efe-f2d1ea56aaf2)
