### ISSUE TITLE
Disk - SSD TBW Info

### ISSUE THREAD

**Issue by h1ght** [hakandundar34coding/system-monitoring-center#215]
Hello,

i like the gui, but i miss the TBW count for ssd's. thats the missing thing in all gui's ive meat so far.

regards

**Comment by hakandundar34coding** [comment]
This feature requires `smartmontools` package. It requires root privileges. There may be more detailed disk SMART information in one of the new versions of the application. It may be added to disk details window as a new tab (SMART).

I will close this issue. But you can write additional comments.
