### ISSUE TITLE
[Bug] Missing Processes (Flatpak)

### ISSUE THREAD

**Issue by hbednar** [hakandundar34coding/system-monitoring-center#219]
When comparing this to GNOME System Monitor not all processes seem to be displayed, even when show all processes is selected.

**Comment by hakandundar34coding** [comment]
Can you write names of the processes that are not listed by System Monitoring Center?

Are there any errors when the application is run by using terminal?

**Comment by hbednar** [comment]
I am using flatpak on Debian sid and these are the errors I am getting:
https://pastebin.com/raw/wnhydRzL

**Comment by hakandundar34coding** [comment]
The link did not work.
Can you share the screenshot of the errors directly (attach them to the comment)?

**Comment by hbednar** [comment]
If the below link doesn't work either, do you know of an alternative to pastebin that works for you.
https://pastebin.com/wnhydRzL

**Comment by hakandundar34coding** [comment]
Can you use the comment feature of Github for attaching image files?

A screenshot:

![screenshot_share](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/25552ca1-36d0-4609-97ef-6f91d25f2152)

**Comment by hbednar** [comment]
See attached
[error.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/12588480/error.txt)

**Comment by hakandundar34coding** [comment]
Is there an ISO file of the distribution that you use? I will test the application on a virtual machine.
Did you changed some packages of the system such as coreutils?

**Comment by hakandundar34coding** [comment]
I tested the application on Debian unstable version on virtual machine. There was no error when Processes tab is opened.

Did you change some packages of the system such as coreutils?

**Comment by hbednar** [comment]
I am using Debian sid with i3 and i have only install the flatpak package nothing else.

i have also spotted the below error when first opened using `flatpak run io.github.hakandundar34coding.system-monitoring-center`

```
/home/user/.local/share:/home/user/.local/share/flatpak/exports/share
is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

dconf-WARNING:  Unable to open /usr/bin/dconf/profile/user: Not a directory
```

**Comment by hakandundar34coding** [comment]
I used the same distribution on virtual machine.

The warning is printed by Flatpak. It may be removed after restarting your system. Can you test the application after restarting your system?

**Comment by hbednar** [comment]
As you said before that this is a flatpak issue i have tested the deb vershon and i only get the below error instead.
Also, the process icons are now showing where the were not before.
If i had to guess i think this may be related to missing environment variables used by Flatpak.

`(python3:2259144): dconf-WARNING **: Unable to open /usr/bin/dconf/profile/user: Not a directory`

Update:
After enabling the process tree i now get this error with the deb package:

```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/ProcessesMenu.py", line 566, in on_show_processes_as_tree_cb_toggled
    Common.save_tab_settings(Processes)
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 49, in save_tab_settings
    TabObject.loop_func()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Processes.py", line 1365, in loop_func
    Common.update_treestore_rows(self, rows_data_dict, deleted_rows, new_rows, updated_existing_row_index, pid_list, self.pid_list_prev, self.show_processes_as_tree, self.show_processes_of_all_users)
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 1108, in update_treestore_rows
    piter_list.append(treestore.append(piter_list[row_id_list.index(parent_row)], tab_data_rows[pid_index]))
```

**Comment by hakandundar34coding** [comment]
Can you follow these steps?

- Close System Monitoring Center
- Delete the `config.txt` file in `/home/[USERNAME]/.config/system-monitoring-center`
- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open terminal in `src` folder
- Run the following command: `python3 ./run_from_source.py`
- Open the Processes tab and share the result

Note: Share the errors including the first lines if there are lots of errors in terminal output.

**Comment by hbednar** [comment]
> Can you follow these steps?
> 
> * Close System Monitoring Center
> * Delete the `config.txt` file in `/home/[USERNAME]/.config/system-monitoring-center`
> * Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
> * Extract it and open terminal in `src` folder
> * Run the following command: `python3 ./run_from_source.py`
> * Open the Processes tab and share the result
> 
> Note: Share the errors including the first lines if there are lots of errors in terminal output.

[error.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/12620812/error.txt)

**Comment by hakandundar34coding** [comment]
Are there any errors for other tabs?

For example;
Can you open Users tab and add/remove columns?

**Comment by hbednar** [comment]
> Are there any errors for other tabs?
> 
> For example; Can you open Users tab and add/remove columns?

`Gdk-CRITICAL **: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed`

**Comment by hakandundar34coding** [comment]
Can you follow these steps for sharing process information on your system?

- Open `Processes.py` file in `src` folder (You downloaded the [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip)).
- Go to line `1239`
- Write the following code: `        import json;print(json.dumps(rows_data_dict))`    (There are 8 spaces at the beginning of the code)
- Save file
- In the `src` folder, run the application by using the following command: `python3 ./run_from_source.py > smc_processes_output.txt`
- Open processes tab and close the application after  1 seconds.
- Share the `smc_processes_output.txt` output file.

Screenshot after the code change:
![smc_code](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/cd8df72f-6ffc-4130-ac28-559da884368c)

**Comment by AtomicRobotMan0101** [comment]
JFYI - I had the problem of where I was not getting ANYTHING in the Process list. Nada. Blank.

Running the app from the terminal it was throwing a huge bunch of errors. 

Turns out it could not connect to `/usr/share/applications/libreoffice7.5-impress.desktop`

I recently updated to 7.6 LibreOffice. I'd also done an `apt purge` on 7.5 but it left the links in `/usr/share/applications`... which clagged up the menu, but seems to have also caused this mysterious error.  I hadn't cleaned the old links up as it didn't bother me too much.... (and nor could they be removed via Cinnamon Menus `menu editor` either, they were missing there)

**Once the offending dead LibreOffice links were removed (deleted), the app behaves perfectly.**

**Comment by hakandundar34coding** [comment]
@AtomicRobotMan0101,

It is a different bug. It is fixed in SMC v2.22.1. The application can be updated from:

- Flatpak in about 4 hours
- Other repositories in about a few days/weeks

**Comment by hbednar** [comment]
I have done some testing on different Linux OS and it seems to only be happening for me.
When i have a chance, i will do an OS reinstall and update here if it still continues.

**Comment by hbednar** [comment]
I have made some adjustments to my environment variables and have now managed to get it working.
But i am getting the below error but it doesn't seem to stop it from working:

`(system-monitoring-center:26149): Gtk-WARNING **: Negative content height -4 (allocation 1, extents 2x3) while allocating gadget (node button, owner GtkButton)`

**Comment by hakandundar34coding** [comment]
The warning in [this](https://github.com/hakandundar34coding/system-monitoring-center/issues/219#issuecomment-1725874642) comment is printed by GTK. There may be other problems on your system.

There may be Flatpak installation problems on your system.
The errors/warnings in this issue were not printed during tests on virtual machine. Setting environment variables for System Monitoring Center is not required.

I will close this issue. But you can write additional comments. You can also open new issues for bugs, new features, etc.

**Comment by hbednar** [comment]
Thanks for the help
