### ISSUE TITLE
Summation of CPU, Memory, etc. when multiple processes are selected

### ISSUE THREAD

**Issue by badcast** [hakandundar34coding/system-monitoring-center#220]
![изображение](https://github.com/hakandundar34coding/system-monitoring-center/assets/70087152/7cb09dc5-5f56-412d-a588-3f199077aa23)

Hello! 
Are you planning to add a general information element for selected and non-selected objects?
As for me, it would be convenient, and statistics (like me) will help

**Comment by hakandundar34coding** [comment]
This feature will probably be added.

**Comment by hakandundar34coding** [comment]
The feature is added. You can test it by using the latest source code.

Steps:
- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it
- Run the following command in `src` folder: `python3 ./run_from_source.py`
- Open Processes tab and select more than one process

There may be a new version in a few days. This version will include this feature.

A screenshot:
![smc_processes](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/9126790b-8a57-47db-88d0-ad3777fc5672)

**Comment by badcast** [comment]
It's perfect version. The perfect solution.
:D 

I checked everything and launched it.

**Comment by hakandundar34coding** [comment]
>  Are you planning to add a general information element for selected and non-selected objects?

You can open new issues if you think unique features. They may be evaluated.
All features that are written may not be added because of high CPU usage, complex GUI, etc.
