### ISSUE TITLE
Text rendering problems when Chinese language and big5 encoding are selected

### ISSUE THREAD

**Issue by spiderman16888** [hakandundar34coding/system-monitoring-center#221]
<img width="541" alt="2023-09-20 下午3 46 07" src="https://github.com/hakandundar34coding/system-monitoring-center/assets/34176915/2510af8e-6228-4ef7-b584-c4c7334cb3ee">

**Comment by hakandundar34coding** [comment]
What is the version of the application?

Can you run the ollowing command and share the output?
`system-monitoring-center`

**Comment by hakandundar34coding** [comment]
What is the version of the application?

How do you select `chinese big5` encoding method?

Can you run the following command and share the output?
`system-monitoring-center`

**Comment by spiderman16888** [comment]
version is 1.43.11
<img width="351" alt="截圖 2023-09-20 下午4 30 01" src="https://github.com/hakandundar34coding/system-monitoring-center/assets/34176915/ae4d00f3-9cf3-4070-b692-f1db573859dc">
<img width="350" alt="截圖 2023-09-20 下午4 31 49" src="https://github.com/hakandundar34coding/system-monitoring-center/assets/34176915/232fa842-a052-4c77-9dd9-c62cc5083710">
I think issue is on multi-language

**Comment by hakandundar34coding** [comment]
Can you share a screenshot of the System tab of SMC?

Is there any encoding option that there are no character rendering problems for SMC?

Can you share output of the following command?
`system-monitoring-center`

**Comment by spiderman16888** [comment]
<img width="609" alt="截圖 2023-09-20 下午5 12 11" src="https://github.com/hakandundar34coding/system-monitoring-center/assets/34176915/e11bf719-fe39-4304-a796-f3de4fb2a131">

Can you share output of the following command?
--> how to show?

**Comment by hakandundar34coding** [comment]
You can share a screenshot of terminal application.

Steps:

- Run terminal application
- Run the following command: `system-monitoring-center`
- Take screenshot of the terminal application.

**Comment by hakandundar34coding** [comment]
The source code is updated. There is a minor change for Summary tab graphics. `CPU` text may be visible after this change. Other texts may be updated if it works.

Can you follow these steps?

- [Download](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/smc_v1.zip) the source code of SMC v1
- Extract it
- Open terminal application in `src` folder
- Run the following command: `python3 ./Main.py`
- Share a screenshot of the Summary tab
- Share a screenshot of terminal application

**Comment by hakandundar34coding** [comment]
It has been about 2 weeks after the last comment. There are no answers to the latest questions. I will close this issue. But you can write answers/comments.
