### ISSUE TITLE
[Feature Request] Show memory used by the page cache

### ISSUE THREAD

**Issue by gcem** [hakandundar34coding/system-monitoring-center#222]
Hi, it would be nice to see how much of the available RAM is being used for cached files.

It is given by the `Cached:` line in `/proc/meminfo`.

**Comment by hakandundar34coding** [comment]
RAM cached and swap cached values are added to Memory tab.
There will be a new version (v2.23.0) in about a few days. These new values will be visible on this version of the application.

A screenshot:
![smc_memory](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/a3ece13e-51c3-4352-8783-8829b884d159)

**Comment by hakandundar34coding** [comment]
System Monitoring Center v2.23.0 may be installable from:

- Flatpak in about 4 hours
- Other repositories in about a few hours/days.

**Comment by gcem** [comment]
Thanks a lot!
