### ISSUE TITLE
Temperature unit conversion in Sensors

### ISSUE THREAD

**Issue by kd9kni** [hakandundar34coding/system-monitoring-center#230]
Is there a way to convert the Celsius values from sensors to Fahrenheit?  This is far from critical, as issues go, but the ability to do that conversion would be very helpful for those of us who think in those units.

**Comment by hakandundar34coding** [comment]
Option for selecting temperature units is added to Sensors menu. There may be a new version in about 1 week. This version will include the feature.

You can test it by following these steps (if your distribution has GTK4):

- Download the [latest](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) source code
- Extract it and open terminal application in `src` folder
- Run the following command: `python3 ./run_from_source.py`
- Open Sensors tab test test the new option

Screenshot of the new option:

![smc_sensors](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/9e3fca3a-f68a-4416-8011-5b6a05171c9b)


I will close this issue. But you can open new issues for new features, bugs, etc.
