### ISSUE TITLE
Memory consumption increases on every cycle when GPU related columns are shown (Processes tab)

### ISSUE THREAD

**Issue by h0x32** [hakandundar34coding/system-monitoring-center#233]
Hello,
I have noticed that leaving system-monitoring-center for even 5 mins fills up memory pretty quick
I have discovered this due to  many many amdgpu_top processes being spawned every refresh cycle.
I am using version 2.24.0

![Screenshot_20231013_150444](https://github.com/hakandundar34coding/system-monitoring-center/assets/42139189/6780b63b-11ee-44ef-a398-b703c92b1afe)

**Comment by hakandundar34coding** [comment]
Does the number of `amdgpu_top` processes increase? Or is it constant?
What is the version of `amdgpu_top`? Is it built by using its latest source code (latest commit)?
Can you share a short video of Processes tab? (for viewing PIDs of some `amdgpu_top` processes)

**Comment by h0x32** [comment]
> Does the number of `amdgpu_top` processes increase? Or is it constant? What is the version of `amdgpu_top`? Is it built by using its latest source code (latest commit)?

Yes, the number increases on each refresh cycle, each new process takes more ram, and the ram usage of the application builds up over time.
I am using the latest amdgpu_top

> yay -Si amdgpu_top
> Repository                    : aur
> Name                          : amdgpu_top
> Version                       : 0.2.0-1
> Description                   : Tool that shows AMD GPU utilization
> URL                           : https://github.com/Umio-Yasuno/amdgpu_top
> Licenses                      : MIT
> Groups                        : None
> Provides                      : None
> Depends On                    : glibc  libdrm
> Optional Deps                 : None
> Make Deps                     : cargo
> Check Deps                    : None
> Conflicts With                : None
> Replaces                      : None
> AUR URL                       : https://aur.archlinux.org/packages/amdgpu_top
> First Submitted               : Sun 09 Apr 2023 07:18:09 PM EET
> Keywords                      : None
> Last Modified                 : Sun 27 Aug 2023 12:33:43 AM EEST
> Maintainer                    : Teddy-Kun
> Popularity                    : 2.135000
> Votes                         : 9
> Out-of-date                   : No

**Comment by hakandundar34coding** [comment]
Currently, the latest package version of `amdgpu_top` is 0.2.0. It does not support some new features. `amdgpu_top`>0.2.0 or its build from the source code of the latest commit is required.

**Comment by hakandundar34coding** [comment]
System Monitoring Center v2.25.1 may be downloadable in about:
- 4 hours by using Flatpak
- A few hours/days by using other repositories

**Details:**
The code for using `amdgpu_top` is disabled. Video encoding/decoding engine loads (GPU tab), GPU usage and GPU memory columns (Processes tab) are not get for AMD GPUs. They are shown as `0`.

I will close this issue. But you can write additional comments or open new issues for new features, bugs.

**Comment by h0x32** [comment]
Hello,
amdgpu_top 0.2.1 was officially [released](https://github.com/Umio-Yasuno/amdgpu_top/releases/tag/v0.2.1)
testing system-monitoring-center 2.24.0 with amdgpu_top 0.2.1
does not cause high memory usage, i think it should be safe to renable the code in 2.25.1

**Comment by hakandundar34coding** [comment]
Its developer may not want its usage by SMC. Currently, there are no plans for enabling the code for using `amdgpu_top`. GPU columns may be usable without it in the newer versions.
