### ISSUE TITLE
Brazilian Portuguese Language

### ISSUE THREAD

**Issue by eusouobn** [hakandundar34coding/system-monitoring-center#29]
I would like to collaborate with the translation to pt-br.... How could I do that?

**Comment by hakandundar34coding** [comment]
You can use one of these ways:

1) You can fork the project, translate it and send a pull request
    or
2) You can download the [system-monitoring-center.pot](https://github.com/hakandundar34coding/system-monitoring-center/blob/master/translations/system-monitoring-center.pot) file from ```/translations``` folder, translate it and send the file to me.

For translation:
You can use ```Poedit``` application.

**Comment by eusouobn** [comment]
OK I will download the file and then send it to you to check

Thanks

**Comment by eusouobn** [comment]
@hakandundar34coding I finished translating....

Do I need to put my name somewhere or just send you the file?

**Comment by hakandundar34coding** [comment]
I will add your name to ```About``` dialog of the application.

You can write your name and surname in the e-mail,
or
```eusouobn``` can be used in the translators section if you do not want to write your name and surname.

Can you also translate the following text (4 lines). Thet are in the ```.desktop``` file of the application and used for application name and explanations in the OS menus, etc.

Here is the full text of the ```.desktop``` file:

```
[Desktop Entry]
Name=System Monitoring Center
Name[tr]=Sistem Gözlem Merkezi
GenericName=System Monitor
GenericName[tr]=Sistem Gözlemcisi
Comment=Gets information about system performance and usage.
Comment[tr]=Sistem performansı ve kullanımı hakkında bilgi verir.
Exec=system-monitoring-center
Icon=system-monitoring-center
Terminal=false
Type=Application
Categories=System;
StartupNotify=true
Keywords=system monitor;task manager;center;performance;speed;frequency;cpu usage;ram usage;swap memory;memory usage;storage;network usage;download speed;fps;frame ratio;processes;users;startup programs;services;os;
Keywords[tr]=sistem gözlemcisi;görev yöneticisi;performans;hız;frekans;cpu;mib;ram kullanımı;takas belleği;bellek kullanımı;depolama;indirme hızı;fps;kare oranı;işlemler;kullanıcılar;başlangıç programları;servisler;os;is;
```

**Comment by eusouobn** [comment]
> I will add your name to `About` dialog of the application.
> 
> You can write your name and surname in the e-mail, or `eusouobn` can be used in the translators section if you do not want to write your name and surname.
> 
> Can you also translate the following text (4 lines). Thet are in the `.desktop` file of the application and used for application name and explanations in the OS menus, etc.
> 
> Here is the full text of the `.desktop` file:
> 
> ```
> [Desktop Entry]
> Name=System Monitoring Center
> Name[tr]=Sistem Gözlem Merkezi
> GenericName=System Monitor
> GenericName[tr]=Sistem Gözlemcisi
> Comment=Gets information about system performance and usage.
> Comment[tr]=Sistem performansı ve kullanımı hakkında bilgi verir.
> Exec=system-monitoring-center
> Icon=system-monitoring-center
> Terminal=false
> Type=Application
> Categories=System;
> StartupNotify=true
> Keywords=system monitor;task manager;center;performance;speed;frequency;cpu usage;ram usage;swap memory;memory usage;storage;network usage;download speed;fps;frame ratio;processes;users;startup programs;services;os;
> Keywords[tr]=sistem gözlemcisi;görev yöneticisi;performans;hız;frekans;cpu;mib;ram kullanımı;takas belleği;bellek kullanımı;depolama;indirme hızı;fps;kare oranı;işlemler;kullanıcılar;başlangıç programları;servisler;os;is;
> ```

OK I added my name in the email and also at the top of the .pot file, please check....

I sent the file to your email and also the translation of the items in the .desktop file

**Comment by hakandundar34coding** [comment]
I have uploaded the translation files.

They can be found in the ```translations/pt_BR``` folder of the project.

I have send an e-mail to you which contains a few screenshots of the application with translated text.

**Comment by hakandundar34coding** [comment]
System Monitoring Center v1.5.0 is available.

- You can download the latest package from this [link](https://github.com/hakandundar34coding/system-monitoring-center/releases).

or

- You can generate a package by using one of the packaging scripts.

or

- You can install it from the AUR. v1.5.0 may be available in AUR in 1 day.

I will close this issue but you can write additional comments about translation or you can open a new issue if there are bugs in the code.
