### ISSUE TITLE
Problems On armv7l Architecture

### ISSUE THREAD

**Issue by lukaszsobala** [hakandundar34coding/system-monitoring-center#3]
Hello, 

This may be an uncommon use case but maybe it can help with something. 

I installed the system monitorom center from git repository using pip on armv7l. Running as root. What does not work:
- all icons are blank
Performance:
- cpu tab: all system infos except architecture are "--". The graph is ok
- ram tab: capacity --. Graph and other values OK. Swap capacity ok 
- disk tab: nothing detected, probably because it's a memory card
- network tab: all values are"--", graph ok 
- GPU: no graph, all values are "--"
- sensors: OK
Users: no info there
Startup: ok
Environment variables: nothing
Processes: this does not even load
Storage: seems ok
Services: ok
System: all values are "--"

**Comment by hakandundar34coding** [comment]
Currently, System Monitoring Center supports only x86_64 architecture. I have not tested the application on other platforms. I do not have any ARM machines for improving the application on this platform.

I will try to improve the application for ARM architecture support if you help me. Some command outputs are required for this improvement and a long iteration may be required. You can send me an e-mail (you can find my e-mail from my GitHub profile) for sending/receiving required commads, outputs, etc. if you decide to help me for this improvement.

Some of the hardware information (which are supported by the application) may not be available on ARM machines.
