### ISSUE TITLE
PPA/Repo please?

### ISSUE THREAD

**Issue by BloodyIron** [hakandundar34coding/system-monitoring-center#36]
Hey so I see there are deb files for each release, thanks for that!

Could we please get a ppa/repo set up for this tool so that we can get delicious upgrades from our package manager? Pretty please? With sugar on top and cherries? And whipped cream and chocolate sprinkles? :)

**Comment by hakandundar34coding** [comment]
I do not know preparing PPA repository and preparing and updating this repository will take additional time.
Currently deb and pacman packages are available. And rpm packages can be generating by using script.

There are several package types and Linux distributions. Preparing packages for them consumes time.

The application may be added into several repositories of different distributions by package maintainers.

**Comment by hakandundar34coding** [comment]
There is no PPA repository for this application but System Monitoring Center v1.9.1 is downloadable from PYPI. Only PYPI package will be available in newer versions.

Updates can be installed from PYPI.

You can uninstall the older versions (v1.8.0 and older) and install the new version.
More information can be found in:
https://github.com/hakandundar34coding/system-monitoring-center

**Comment by BloodyIron** [comment]
This negates the point of having a package manager. A package manager ecosystem is used to track all software installed on a system, and installing though other means defeats this. The value isn't just in keeping track of what's installed, but also assisting with uninstallation, updating, tracking versions of software, and things like that. That's the premise behind asking for a PPA/Repo, so that package managers of that type can interface with them and update this software as updates come out.

**Comment by hakandundar34coding** [comment]
Maybe contributors/package maintainers prepare different types of repositories/packages for the application. I prepared three types of packages but there were also other systems which use different packaging systems. I can't prepare a lot of package types/repositories. A single type does not work on all systems.
