### ISSUE TITLE
Make it pip installable?

### ISSUE THREAD

**Issue by johann-petrak** [hakandundar34coding/system-monitoring-center#39]
If this is implemented in Python, why not make it pip installable?
That way, no sudo rights would be needed, installation would be much easier, and also, the system Python and environment would not clash with my per-user conda (or other) environment.

**Comment by hakandundar34coding** [comment]
It would be easier to install the application by using ```pip```.

But:
- Isn't it a security problem installing the application without using ```sudo```?
- How to prevent changeablity of the code of the application?

This is a system application and root privileges are required for some actions. Keeping the code in a secure directory is required.

As far as I know ```pip``` is not for distributing applications but for packages. Applications may have ```.desktop``` files for shortcuts, etc in the ```/usr/share/...``` directories.

What do you think and suggest?

**Comment by johann-petrak** [comment]
My personal answers to these questions:

* I do not understand why installing without sudo should be a security problem. On the contrary: if installation requires sudo and the installed app is malicious, the installation with sudo rights will allow the code to be even more destructive.
* as mentioned, allowing to install without sudo will make it easier for people to use the tool even if they do not have sudo rights
* Using pip install for installation makes it easy to nicely keep the requirements in a dedicated environment
* many other python packages provide commands, e.g. the `glances`  package which also shows process information. 
* the installation with pip does not need to provide .desktop files, if users want that, they can still install usign the package, but ...
* making the tool pip installable will make it easy to install it on the many linux-like systems for which no package is provided

**Comment by hakandundar34coding** [comment]
System Monitoring Center is not a malicious software. I tried to tell that a malicious code/scripts may change the source code of this application in user directories.

Using ```pip``` is easier than preparing different packages for several distributions. But I will search and look for answers for some questions.

Also updating the application by using ```pip``` easier than some packaging types. Because some of them freeze a version and applications get only packaging updates instead of getting main or sub version updates.

**Comment by hakandundar34coding** [comment]
It has been a long time since the last comment. I tried to fix several bugs for some systems.

Preparing ```pip``` package is planned and currently it has high priority. It will be only package type if it works. Some features require workarounds (such as recolored GUI images by checking system theme color).

I will close this issue. But you can write additional comments.

**Comment by hakandundar34coding** [comment]
Python packaging is completed.
System Monitoring Center v1.9.1 is downloadable from PYPI. Only PYPI package will be available in newer versions.

You can uninstall the older versions (v1.8.0 and older) and install the new version.
More information can be found in:
https://github.com/hakandundar34coding/system-monitoring-center

Can you write if there are problems?

**Comment by johann-petrak** [comment]
Great, thanks! 

Just as a remark: There is a potential installation hurdle: system-monitoring-center depends on pycairo and pycair gets locally built on my Linux system and fails unless the proper system libraries are installed first. In my case `sudo apt install libcairo2-dev` made pycair install which in turn allowed system-monitoring-center to get installed. 

Another small thing, maybe I misunderstand something, but the README says: "For current user account: sudo pip install system-monitoring-center
For system-wide installation: sudo pip install system-monitoring-center (This method can be used for preventing source code modifications.)"

Could it be that you meant to not include "sudo" for the current user account in that?

**Comment by hakandundar34coding** [comment]
I have updated README.md file (removed the first```sudo```).

About the remarked issue:

I did not install pycairo after cairo libraries. I will test the application for several cases. README file may be updated for after that. There may be other dependency problems if the system have only a few applications installed.

You can write additional comments for improvements/problems.

**Comment by hakandundar34coding** [comment]
I installed a debian based distribution, removed a lot of applications including file browser, cleared unused packages and installed the application by using pip. There was no dependency problem.

What is your distibution?

There are some system-wide dependencies which are not Python packages but they are installed on many systems. But there these depenencies will be added to README file. For example: dmidecode, util-linux, etc. Cairo libraries may be added to this list.
