### ISSUE TITLE
Switching GPU causes a high spike in the chart that lasts for a second.

### ISSUE THREAD

**Issue by govarthenan** [hakandundar34coding/system-monitoring-center#4]
As you can see in [this recording](https://ibb.co/KGnbsJj), whenever I switch the GPU, the chart displays a very high spike, that is only displayed for a second. This behavior is produced only when I select another GPU. Note that this doesn't happen when I change my active tab to GPU.

**Comment by hakandundar34coding** [comment]
FPS counter on the GPU tab is a simple FPS counter. Its accuracy may change in different situations. Currently, FPS counter gives a rough idea for GPU load if user does not play with the System Monitoring Center GUI during this observation. You can read help/explanatory information when mouse cursor is moved on area of GUI an object, for example FPS (Frame Rate) label.

Switching GPU/Graphics Card does not run FPS counter on the specific GPU card. This feature may be added in the next versions. Switch operation only resets FPS history. Also FPS counting does not continue when window is minimized or GPU tab is swithched. You can find some of these information on GUI tooltips (by mouse hover actions on GUI labels). Additional improvements may be performed in the next releases.

CPU load changes/increases when you open menus, change selected GPU/Graphics Card. Also GTK glarea widget draws extra drawings when some changes are performed on the GUI of the application. These reasons may cause counted FPS changes/spikes.

**Comment by govarthenan** [comment]
Yea I understand that my actions would cause more objects to be drawn and thus increase the FPS. What I meant was, the spike disappears and is replaced by a new line. Is that expected behavior?

**Comment by hakandundar34coding** [comment]
Does ```is replaced by a new line``` means that graph history is reset?

It is reset when GPU is switched. This is the default behavior.

**Comment by govarthenan** [comment]
Whenever you select another GPU, a spike appears. The spike disappears and then, the graph for the selected GPU appears.

**Comment by hakandundar34coding** [comment]
The spike may become smaller, because graph is scaled dynamically. You can understand this by viewing network download or disk read/write speed disk. Graph is scaled when biggest data on the screen is changed.

At the beginning a spike may be seen. But FPS counting continues and increases after a time and graph is scaled for higher FPS count.

What is CPU load during FPS counting? Can you measure it by using another task manager? You can monitor CPU usage of Python3 process. CPU usage graph on the headerbar is not visible on the video you shared.

**Comment by govarthenan** [comment]
Sorry for the delay. I monitored CPU usage while switching GPUs. It was normal. And you are right about the graph getting smaller.
