### ISSUE TITLE
Improved model info for ARM cpus

### ISSUE THREAD

**Issue by theofficialgman** [hakandundar34coding/system-monitoring-center#47]
tracking branch https://github.com/hakandundar34coding/system-monitoring-center/tree/draft:

I get this info back `ARM Cortex-A57 (ARMv8)`
I will also look into seeing if there is any ID info available on the system for these ARM cpus

**Comment by theofficialgman** [comment]
so far all I see are big tables of names/vendor IDs in other projects
I don't think there is any standard file with this info
you can see a big on here https://github.com/pytorch/cpuinfo/blob/master/tools/cpu-info.c

**Comment by hakandundar34coding** [comment]
An issue for adding arm_cpu.ids file may be opened on hwdata project page.

I added more CPU IDs into the code but I do not prefer adding all IDs into code of an application. A database is required.

Also a file such as mmc.ids would be useful for getting MMC card information by using CIDs.

Another thing about separate database ID files:
Users can update database by using a command such as: ```sudo update-pciids``` without waiting update of the application if there are new devices.

**Comment by theofficialgman** [comment]
> An issue for adding arm_cpu.ids file may be opened on hwdata project page.

I agree it should have been there from the start, but the problem with that should be obvious. Every distro would need to backport any addition of arm_cpu.ids to their own packages and that may never happen. For ubuntu and debian, an feature update such as the inclusion of arm_cpu.ids won't be included until another 4 years for a ubuntu lts or 2-4 for debian.

maybe as an inbetween we can get it added to upstream hwdata so new distros will have it, and you can provide the arm_cpu.ids file within the application package as a fallback incase the system file isn't available

**Comment by hakandundar34coding** [comment]
Current plan:
Number of ARM CPU models in the code of this application will be increased as a quick solution.
Also this solution (or a separate file) will be used as a fallback (you have already wrote this).

What will we do for hwdata? A new issue?

**Comment by hakandundar34coding** [comment]
CPU model name problem for ARM devices is fixed. I will close this issue. But you can write comments if additional improvements are required for CPU model name.
