### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by Adithyan007hack** [hakandundar34coding/system-monitoring-center#48]
Hello,
This amazing masterpiece should also release a flatpak version. Then It will be easier for various distributions to run it not only Debian based distros and it will also be able to run in older versions of Linux 

Pls consider this!

**Comment by hakandundar34coding** [comment]
I prepared a Flatpak package for one of the previous versions. But Flatpak does not support some features of this application.
For example, processes of the OS can't be listed/accessed in Flatpak environment. Only processes in the sandbox can be accessed (3-4 processes in sandbox of this application).

Processes are used for several features of System Monitoring Center. A Flatpak version will not be prepared if there is no change for this limitation.

**Comment by Adithyan007hack** [comment]
OK I clearly understand

**Comment by hakandundar34coding** [comment]
There is no Flatpak package but there is a Python package.
System Monitoring Center v1.9.1 is downloadable from PYPI. Only PYPI package will be available in newer versions.

You can uninstall the older versions (v1.8.0 and older) and install the new version.
More information can be found in:
https://github.com/hakandundar34coding/system-monitoring-center
