### ISSUE TITLE
No Window Manager detected

### ISSUE THREAD

**Issue by K0-RR** [hakandundar34coding/system-monitoring-center#53]
GNOME 41.4 with Mutter on Fedora Silverblue 35. Latest package from PyPI.
![image](https://user-images.githubusercontent.com/43277609/161448584-ccc4c26a-5670-4c9b-89ec-6c704f2bc081.png)

**Comment by hakandundar34coding** [comment]
I searched about this information several versions ago. Mutter is not a separate package on Gnome DE and it has no separate process. It is not detected.

Update:
Code is updated and ```mutter``` is shown if DE is Gnome (for versions 3, 40, 41, 42).
