### ISSUE TITLE
Better graphs - show past values when hovered over

### ISSUE THREAD

**Issue by K0-RR** [hakandundar34coding/system-monitoring-center#56]
Here is an example graph to explain better the idea:
![Screenshot from 2022-04-03 23-13-30](https://user-images.githubusercontent.com/43277609/161448947-2602095f-d207-4618-8547-512edb2f267e.png)
Currently, the user can't check previous values. This makes the graphs no more useful than to please the eyes.
![Screenshot from 2022-04-03 23-08-19](https://user-images.githubusercontent.com/43277609/161448875-8df4960c-ad75-4eaa-baa1-704a092f1d4b.png)
![Screenshot from 2022-04-03 23-08-06](https://user-images.githubusercontent.com/43277609/161448877-4cf43b25-4c31-4eab-b5f8-eaf672d0d25f.png)

**Comment by hakandundar34coding** [comment]
Interactive charts feature is added. You can install v1.11.0 for testing it.
