### ISSUE TITLE
Displaying temperature for Nvidia GPU

### ISSUE THREAD

**Issue by Hayashi-Tensai** [hakandundar34coding/system-monitoring-center#57]
Based on the screenshots, it does show temperatures for nouveau drivers, but are you able to have it display it for Nvidia proprietary drivers too by any chance?

**Comment by hakandundar34coding** [comment]
Redesigned GPU tab will be usable in the next version. GPU temperture can be get for closed sourced NVIDIA driver. It will shown on the GPU tab. The code is changed but it is not uploaded.

What is the GPU model on your system?

**Comment by Hayashi-Tensai** [comment]
Nice, will look forward to it. My GPU model is Nvida Geforce RTX 2060

**Comment by hakandundar34coding** [comment]
Can you share output of this command (single line)?

`nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics --format=csv`

It is not an old GPU. But I do not know if all of the values can be get for RTX 2000 series.

**Comment by Hayashi-Tensai** [comment]
name, pci.bus_id, driver_version, utilization.gpu [%], utilization.memory [%], memory.total [MiB], memory.free [MiB], memory.used [MiB], temperature.gpu, clocks.current.graphics [MHz], clocks.max.graphics [MHz]
GeForce RTX 2060, 00000000:09:00.0, 460.91.03, 20 %, 8 %, 5934 MiB, 5252 MiB, 682 MiB, 36, 300 MHz, 2160 MHz

**Comment by hakandundar34coding** [comment]
Source code is uploaded. Can you test it before a package is prepared?

[Link](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip) for the full source code:

If you want to test it you can download and replace these files with the files in the installation folder:
src folder:
```
Gpu.py
GpuMenu.py
Performance.py
SettingsGUI.py
```

ui folder:
`GpuTab.ui`

After replacing these files you can run the application from terminal in order to see if there are errors.
You can share a screenshot of the GPU tab if there are no errors.

**Comment by Hayashi-Tensai** [comment]
Tested the source directly, overall looks good with no errors
![Screenshot from 2022-04-19 19-15-19](https://user-images.githubusercontent.com/30492689/163991865-433886f1-3339-4590-93a8-208e95a49ed6.png)

**Comment by hakandundar34coding** [comment]
A new package will be installable in less than a week.

What is the number of GPUs on your system?

Currently it is not required but can you share file contents in the card folder?
It may be required for some new updates. I do not know which information is provided in these file for newer GPUs. For example, all of the required information can be get for AMD GPUs by reading these files.

Here is the code for getting this information:
```
grep . /sys/class/drm/card0/device/*
grep . /sys/class/drm/card0/*
```

**Comment by Hayashi-Tensai** [comment]
Here are the following outputs

`grep . /sys/class/drm/card0/device/*`
[output_device.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/8517719/output_device.txt)

`grep . /sys/class/drm/card0/*`
[output_card0.txt](https://github.com/hakandundar34coding/system-monitoring-center/files/8517723/output_card0.txt)

**Comment by hakandundar34coding** [comment]
v1.12.0 can be installed. Code changes for GPU load, frequencies, temperature, power usage, etc. information are included in this version of the application.

I will close this issue. But you can write comments if there are problems on the GPU tab.

**Comment by awohsen** [comment]
Hi, thanks for your great work. 

Installed it right now but I don't have access to at least GPU temperature and Its memory. 




> Can you share the output of this command (single line)?
> 
> `nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics --format=csv`

```
name, pci.bus_id, driver_version, utilization.gpu [%], utilization.memory [%], memory.total [MiB], memory.free [MiB], memory.used [MiB], temperature.gpu, clocks.current.graphics [MHz], clocks.max.graphics [MHz]
NVIDIA GeForce GTX 650 Ti BOOST, 00000000:08:00.0, 470.103.01, [N/A], [N/A], 1993 MiB, 1720 MiB, 273 MiB, 40, [N/A], [N/A]
```

>` grep . /sys/class/drm/card0/device/*`

https://pastebin.pl/view/raw/804f9df7


> `grep . /sys/class/drm/card0/*`

```
/sys/class/drm/card0/dev:226:0
grep: /sys/class/drm/card0/device: Is a directory
grep: /sys/class/drm/card0/power: Is a directory
grep: /sys/class/drm/card0/subsystem: Is a directory
/sys/class/drm/card0/uevent:MAJOR=226
/sys/class/drm/card0/uevent:MINOR=0
/sys/class/drm/card0/uevent:DEVNAME=dri/card0
/sys/class/drm/card0/uevent:DEVTYPE=drm_minor
```



Also, I have to mention if it would help, In [SysMonTask](https://github.com/KrispyCamel4u/SysMonTask) which is similar to your project I was able to see the all available data provided by Nvidia-smi: 

![image](https://user-images.githubusercontent.com/93778317/164913105-985a82a8-9c7d-4112-a166-400bc748d455.png)


App logs related to this: 

![image](https://user-images.githubusercontent.com/93778317/164913785-3272ef2b-ea7c-4afc-852f-b01503b6524e.png)

**Comment by hakandundar34coding** [comment]
@awohsen
GPU tab code is updated. Can you download the [file](https://github.com/hakandundar34coding/system-monitoring-center/blob/master/src/Gpu.py) and replace with the existing file in the installation directory?

**Comment by awohsen** [comment]
Great It's working now: 
![image](https://user-images.githubusercontent.com/93778317/164956236-36d28fb8-e331-4e35-ab37-d5716f371af3.png)

**Comment by hakandundar34coding** [comment]
You downloaded the latest source code manually. Also v1.12.1 is installable which includes the latest source code.
