### ISSUE TITLE
GUI images are not loaded (beta version of the distribution)

### ISSUE THREAD

**Issue by lorenzo0932** [hakandundar34coding/system-monitoring-center#58]
I'm on fedora 36, Gnome 42 and icon's won't load. 
i tried with user and superuser installation but nothing change. 
![Screenshot from 2022-04-20 19-06-42](https://user-images.githubusercontent.com/60674575/164285377-df6d0b48-39c1-46a3-8853-3e64e25a54bd.png)
![Screenshot from 2022-04-20 19-08-48](https://user-images.githubusercontent.com/60674575/164285434-d69802c7-eefa-447c-87bd-990a2c0c44a5.png)

**Comment by hakandundar34coding** [comment]
- How did you install the application?
- Can you run the application from terminal and share the output?
- What is the installation directory of the application?
- Are there any image files in this directory?
   `/home/[user_name]/.local/share/icons/hicolor/scalable/actions`

**Comment by lorenzo0932** [comment]
1. Installed via pip 
2. No output on terminal
3. Installation directory are 
For sudo installation:
-     /usr/local/bin/system-monitoring-center
-     /usr/local/lib/python3.10/site-packages/system_monitoring_center-1.11.0.dist-info/*
-     /usr/local/lib/python3.10/site-packages/systemmonitoringcenter/*

For user installation 
-     /home/lorenzo/.local/bin/system-monitoring-center
-     /home/lorenzo/.local/lib/python3.10/site-packages/system_monitoring_center-1.11.0.dist-info/*
-     /home/lorenzo/.local/lib/python3.10/site-packages/systemmonitoringcenter/*

I don't know if these are the "real" installation directory. These is what pip say to me when i try to remove the application. 

4. In that folder i have only .svg files
![Screenshot from 2022-04-20 20-18-03](https://user-images.githubusercontent.com/60674575/164296516-cbfd58eb-6683-45a8-8d79-d7b5a8c015de.png)

**Comment by hakandundar34coding** [comment]
Can you restart the system and run the application again (without uninstalling it)?

**Comment by lorenzo0932** [comment]
Done and now i have no problem with sudo but still not working in user space

![Screenshot from 2022-04-20 20-26-16](https://user-images.githubusercontent.com/60674575/164297923-d84c5e6c-8bf9-43c6-88a8-a1b2f3a11db5.png)
![Screenshot from 2022-04-20 20-26-23](https://user-images.githubusercontent.com/60674575/164297935-d5ea01bc-b6f4-45dc-a3ce-3577bed88de1.png)

**Comment by hakandundar34coding** [comment]
After the last installation another system restart may be required. It looks like some systems does not update cache immediately.
Can you restart the system again and run the application again (without uninstallation)?

**Comment by lorenzo0932** [comment]
Done and nothing change. There is a way to force cache to update?

**Comment by hakandundar34coding** [comment]
`sudo update-icon-caches /usr/share/icons/*`

You can modify the directory.

------------------------

If GUI images are not shown again:

Can you try:

- Remove all instances of the application.
- Delete `com.github.hakand34.system-monitoring-center.desktop` in `/home/[user_name]/.local/share/applications/`
- Delete svg symlinks (which start with system-monitoring-center) in `/home/[user_name]/.local/share/icons/hicolor/scalable/actions` and in `/home/[user_name]/.local/share/icons/hicolor/scalable/apps`
- Install the application for the current user.
- Run the application one time from the terminal.
- Restart the system.

**Comment by lorenzo0932** [comment]
Done, still not working. I will try on other machine with the stable version of fedora

**Comment by lorenzo0932** [comment]
i tried and as aspected everithing works without problem so i will try to trobleshoot on my own. 

PS. Sorry for my english

**Comment by lorenzo0932** [comment]
Solved!! I don't know why but updating the timestamp on the top level icons directory icons appear as espected!! 
This are the command used:

- sudo touch /usr/share/icons/hicolor ~/.local/share/icons/hicolor
- sudo gtk-update-icon-cache

Thanks for your help!!

**Comment by hakandundar34coding** [comment]
It may be a bug of the distribution (beta version).

I did not see similar problem during tests on several distributions (not beta) on virtual machines.
