### ISSUE TITLE
Just a heads up, you might be getting a lot of new users soon

### ISSUE THREAD

**Issue by theofficialgman** [hakandundar34coding/system-monitoring-center#59]
Popular linux youtuber, Brodie Robertson, has just featured your project. https://www.youtube.com/watch?v=gJLHeY36szU

I expect you might be getting an influx of users (and bug reports) soon.
Just a heads up, feel free to close.

**Comment by hakandundar34coding** [comment]
I saw the video. There are new users and some bugs. I will fix the bugs.
