### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by Pico-Dev** [hakandundar34coding/system-monitoring-center#60]
When trying to run via the terminal on Arch i get

`(system-monitoring-center:7486): Gtk-WARNING **: 18:35:52.508: Locale not supported by C library.`
`Using the fallback 'C' locale.`
`Traceback (most recent call last):`
`File "/usr/share/system-monitoring-center/src/Main.py", line 17, in do_activate`
`from MainGUI import MainGUI`
`File "/usr/share/system-monitoring-center/src/MainGUI.py", line 570, in <module>`
`MainGUI = MainGUI()`
`File "/usr/share/system-monitoring-center/src/MainGUI.py", line 26, in __init__`
`locale.setlocale(locale.LC_ALL, os.environ.get("LANG"))`
`File "/usr/lib/python3.10/locale.py", line 620, in setlocale`
`return _setlocale(category, locale)`
`locale.Error: unsupported locale setting`

but my locale is properly setup this is its output

`LANG=en_US.UTF-8`
`LC_CTYPE="en_US.UTF-8"`
`LC_NUMERIC=en_US.UTF-8`
`LC_TIME=en_US.UTF-8`
`LC_COLLATE="en_US.UTF-8"`
`LC_MONETARY=en_US.UTF-8`
`LC_MESSAGES="en_US.UTF-8"`
`LC_PAPER="en_US.UTF-8"`
`LC_NAME="en_US.UTF-8"`
`LC_ADDRESS="en_US.UTF-8"`
`LC_TELEPHONE="en_US.UTF-8"`
`LC_MEASUREMENT=en_US.UTF-8`
`LC_IDENTIFICATION="en_US.UTF-8"`
`LC_ALL=`

**Comment by hakandundar34coding** [comment]
What are the outputs of these commands?

`echo $LANG`

`locale -a`

**Comment by Pico-Dev** [comment]
en_US.UTF-8
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX

**Comment by hakandundar34coding** [comment]
Output of `echo $LANG` command is used for detecting current locale on your system. It uses C locale if a language is not installed.

It looks like there is a problem about locale on your system. I do not know what is wrong on your system.

After a quick search I saw several solutions on the web. Did you try any solutions to fix this problem?

**Comment by Pico-Dev** [comment]
yes but they did not help

**Comment by hakandundar34coding** [comment]
Can you [download](https://github.com/hakandundar34coding/system-monitoring-center/blob/master/src/MainGUI.py) the latest MainGUI.py file and replace it with the same file in the installation directory?

**Comment by Pico-Dev** [comment]
thanks it is fixed now
