### ISSUE TITLE
Comprehensive Search in Process Tab

### ISSUE THREAD

**Issue by Nicolacarrino** [hakandundar34coding/system-monitoring-center#62]
I start by saying that "System Monitor Center" is awesome and before this one I missed a GUI able to aggregate all this info together. I am currently using it for a couple of days and it has served me very well. I mainly use the Process tab to monitor CPU usage, and thread count of some python scripts I am running. 

The problem that I have encountered is in the search bar. From what I understand, it is only possible to search by the process name. This results in the following problem:
I run `python3  script.py` from the terminal and I would like to monitor the execution by searching in the Process tab by a portion of this command (e.g. script), which does not result in anything since the search is done on the process name; at the same time if I search using 'python', I get a list of all python instances currently running on the system which makes monitoring extremely difficult.

I have noticed that in the option `Details/Disk and Path`  under Path it is reported the Command Line argument, so I think most of the info is already parsed by the program.

Would it be possible to implement a more comprehensive search, allowing to specify in which field I am searching in (maybe defaulting to Name) and allowing to search over the Command Line arguments ? Another option which would be very useful is to add in the View Column related to Path not only the executable but the entire Command Line like it is done in htop and ps.

**Comment by hakandundar34coding** [comment]
Search customizations feature was available for several tabs of the application. But they were removed a lot of versions ago for:
- Simpler the GUI and code.
- Easier maintenance.
- Less number of translation texts.
- Slightly lower CPU usage on some cases.

Probably it will not be added again. There are other features/imporvements which has higher priority.

Here is a screenshot of the removed feature:
![smc_search_customizations](https://user-images.githubusercontent.com/90193017/164735154-9b21a178-c298-4a7d-a18c-529bc7f07dce.png)

I will close this issue but you can write additional comments.

--------------------

Commandline information can be shown in newer versions of the application.

**Comment by hakandundar34coding** [comment]
Commandline information can be shown by enabling a checkbutton on customizations menu of the Processes tab.

**Comment by Nicolacarrino** [comment]
Yes, I have found it by updating. Thanks
Do you plan to search over commandline in Process Tab?

**Comment by hakandundar34coding** [comment]
Currently there are no plans for search [feature](https://github.com/hakandundar34coding/system-monitoring-center/issues/62#issuecomment-1106585951) for commandline information of the processes.
