### ISSUE TITLE
system-monitoring-center: command not found

### ISSUE THREAD

**Issue by stefan-reich** [hakandundar34coding/system-monitoring-center#63]
This is on Linux Mint 19...

```
stefan@lenovo-ThinkPad-X220:~$ pip3 install system-monitoring-center
Collecting system-monitoring-center
[...]
Successfully installed PyGObject-3.42.1 pycairo-1.20.1 system-monitoring-center-1.12.0
stefan@lenovo-ThinkPad-X220:~$ system-monitoring-center
system-monitoring-center: command not found

```

**Comment by hakandundar34coding** [comment]
Can you restart the system and run the command again?

**Comment by stefan-reich** [comment]
That did it! Would be nice to have an alternative way to change the PATH too though I guess. Thanks

**Comment by hakandundar34coding** [comment]
This is a Python package and some code is running after the application run to generate links for shortcut and repaintable GUI images. Restart is required on some systems. There may be some improvements for these actions.
