### ISSUE TITLE
Add a "chart show" -> Disk usage (per disk)

### ISSUE THREAD

**Issue by gnarlin** [hakandundar34coding/system-monitoring-center#65]
I think it would be fantastic to be able to see all the disks at once, each with their own little graph, just like "chart show" -> "CPU usage (per core) does for CPU utilization. Would you please consider adding this?

**Comment by hakandundar34coding** [comment]
Latest version of the application (v1.13.0) supports plotting disk read/write speeds of all disks at the same time. You can see this [comment](https://github.com/hakandundar34coding/system-monitoring-center/issues/28#issuecomment-1113930381) for example screenshots.
