### ISSUE TITLE
Files are installed in the wrong place

### ISSUE THREAD

**Issue by yochananmarqos** [hakandundar34coding/system-monitoring-center#69]
I tried the v1.12.1 and v1.12.1-deb_for_stores tags with the same result. 

Using setup.py build / install:

```
.
├── systemmonitoringcenter
│   ├── applications
│   ├── database
│   ├── icons
│   │   └── hicolor
│   │       └── scalable
│   │           ├── actions
│   │           └── apps
│   ├── locale
│   │   ├── cs
│   │   │   └── LC_MESSAGES
│   │   ├── pl
│   │   │   └── LC_MESSAGES
│   │   ├── pt_BR
│   │   │   └── LC_MESSAGES
│   │   └── tr
│   │       └── LC_MESSAGES
│   ├── src
│   └── ui
└── usr
    ├── bin
    └── lib
        └── python3.10
            └── site-packages
                ├── systemmonitoringcenter
                │   └── __pycache__
                └── system_monitoring_center-1.12.1-py3.10.egg-info

```

Using build / installer:
```

└── usr
    ├── bin
    └── lib
        └── python3.10
            └── site-packages
                ├── systemmonitoringcenter
                │   ├── applications
                │   ├── database
                │   ├── icons
                │   │   └── hicolor
                │   │       └── scalable
                │   │           ├── actions
                │   │           └── apps
                │   ├── locale
                │   │   ├── cs
                │   │   │   └── LC_MESSAGES
                │   │   ├── pl
                │   │   │   └── LC_MESSAGES
                │   │   ├── pt_BR
                │   │   │   └── LC_MESSAGES
                │   │   └── tr
                │   │       └── LC_MESSAGES
                │   ├── __pycache__
                │   ├── src
                │   │   └── __pycache__
                │   └── ui
                └── system_monitoring_center-1.12.1.dist-info
```

**Comment by hakandundar34coding** [comment]
Same setup.py file is used for v1.2.0 nd v1.2.1. 
Also same setup.py is used for preparing a .deb package and it is installed under /usr/share folder.

Tags with `_deb_for_stores` is for system packages (such as deb). They can also be used for pacman packages.
Otherwise they are for Python pacages and they are not installed under /usr/share.

**Comment by hakandundar34coding** [comment]
What was the installation directory for v1.2.0?

**Comment by yochananmarqos** [comment]
> Same setup.py file is used for v1.2.0 and v1.2.1.

Right, that's what doesn't make any sense.

> What was the installation directory for v1.2.0?

Everything is installed in the right place.

```
.
└── usr
    ├── bin
    ├── lib
    │   └── python3.10
    │       └── site-packages
    │           ├── systemmonitoringcenter
    │           │   └── __pycache__
    │           └── system_monitoring_center-1.12.0.dist-info
    └── share
        ├── applications
        ├── icons
        │   └── hicolor
        │       └── scalable
        │           ├── actions
        │           └── apps
        ├── man
        │   └── man1
        └── system-monitoring-center
            ├── database
            ├── locale
            │   ├── cs
            │   │   └── LC_MESSAGES
            │   ├── pl
            │   │   └── LC_MESSAGES
            │   ├── pt_BR
            │   │   └── LC_MESSAGES
            │   └── tr
            │       └── LC_MESSAGES
            ├── src
            │   └── __pycache__
            └── ui
```

**Comment by hakandundar34coding** [comment]
I have controlled modifications of the some files (such as setup.py) in deb_for_stores branch. But they are not changed.

Is Python package version (from PyPI) installed on your system? You can remove it if it is installed.

Did you solve the problem?

**Comment by yochananmarqos** [comment]
> Is Python package version (from PyPI) installed on your system? 

No, I never install anything with Pip. The same thing happens building in a clean chroot as well.

> Did you solve the problem?

Nope.

**Comment by hakandundar34coding** [comment]
I do not know a lot of details about packaging on Arch Linux.
Some dependencies are removed since the last version. For example: `makedepends = rsync`.

Did you controlled the PKGBUILD file?

**Comment by yochananmarqos** [comment]
I'm the AUR package maintainer. I was only using `rsync` to copy files to the right place. I was able to do it without it, so I removed it. That's not related.

**Comment by yochananmarqos** [comment]
I ended up moving the files in their proper places manually. I shouldn't have to do that.

EDIT: Nevermind, it's broken. I reverted back to 1.12.0 and there it will stay for now.

**Comment by yochananmarqos** [comment]
Nevermind, something was wrong on my end apparently.
