### ISSUE TITLE
Graphs Are Not Displayed On Manjaro Distribution

### ISSUE THREAD

**Issue by keyiflerolsun** [hakandundar34coding/system-monitoring-center#7]
![mib](https://user-images.githubusercontent.com/57468649/144793401-f6320128-890b-4c74-847d-a794e0e83eac.png)

Ellerinize sağlık, sistemimde grafiklerin görüntülenememe sebebi nedir acaba?

![Sistem](https://user-images.githubusercontent.com/57468649/144793414-3a2b8bcb-ae51-46b8-95ea-a274593d0de9.png)

**Comment by keyiflerolsun** [comment]
> Kurulum Aşamaları;

```bash
git clone https://github.com/hakandundar34coding/system-monitoring-center
cd system-monitoring-center
makepkg -Acs
sudo pacman -U system-monitoring-center-0.1.21.beta19-1-x86_64.pkg.tar.zst
```

**Comment by hakandundar34coding** [comment]
Can you run the application from terminal and write error messages?
```system-monitoring-center```

**Comment by keyiflerolsun** [comment]
```
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

**Comment by hakandundar34coding** [comment]
Are these packages installed on your system?

```python-cairo```
```cairo```

I have installed Manjaro Linux 21.1.6 on virtual machine and installed latest version of System Monitoring Center by using pacman package.
Here is the [link](https://sourceforge.net/projects/system-monitoring-center/files/v0.1.21-beta19/system-monitoring-center-0.1.21.beta19-1-x86_64.pkg.tar.zst/download) for the package.


All graphs are displayed on this system.

**Comment by keyiflerolsun** [comment]
Evet, bu(https://pypi.org/project/pycairo) sorunumu çözdü teşekkür ederim..

**Comment by supertorpe** [comment]
Same error on Lubuntu 21.10. Solution:
sudo apt-get install python-gi-cairo

**Comment by hakandundar34coding** [comment]
@supertorpe, it has been o long time since the last message.
I have seen the same problem on other distributions (which use .deb packages). I have added ```python3-gi-cairo``` dependency for systems which use .deb packages. This change is applied to the latest code but it wil be available in the next package.
