### ISSUE TITLE
App installed from AUR no longer starts

### ISSUE THREAD

**Issue by DhruvaSambrani** [hakandundar34coding/system-monitoring-center#70]
I get a `ModuleNotFoundError: No module named 'Main` on startup.

Installed from AUR.

**Comment by damadorPL** [comment]
$ system-monitoring-center
Traceback (most recent call last):
  File "/usr/bin/system-monitoring-center", line 8, in <module>
    sys.exit(start_app())
  File "/usr/lib/python3.10/site-packages/systemmonitoringcenter/start.py", line 9, in start_app
    import Main
ModuleNotFoundError: No module named 'Main'


same error on pure arch & endeavour

**Comment by yochananmarqos** [comment]
I reverted back to 1.12.0 for now. See #69

**Comment by yochananmarqos** [comment]
It's corrected with 1.12.1-2.

**Comment by hakandundar34coding** [comment]
Are your problems fixed?

**Comment by DhruvaSambrani** [comment]
Yes, Thank you
