### ISSUE TITLE
Possible to implement an update notification?

### ISSUE THREAD

**Issue by Hayashi-Tensai** [hakandundar34coding/system-monitoring-center#72]
It would be nice to have a feature where it informs the user of an update when a new version is available, or else it will be hard to tell when a new version releases

**Comment by hakandundar34coding** [comment]
This feature is added. It waits 5 seconds after the application is run and checks for updates. There is an option on General Settings window for disabling it.

It works if the application is installed as a Python package (pip install ...). Otherwise package manager of the system updates the application (deb, pacman, etc.). It works if the application is not run with root privileges.

Here is a screenshot:
![smc_check_updates](https://user-images.githubusercontent.com/90193017/165311386-dc565ea4-d451-407f-8ccd-2661884c5352.png)

You can download and replace these files if you do not want to wait for the new package:
/src/Conf/ig.py
/src/MainGUI.py
/src/SettingsGUI.py
/ui/SettingsWindow.ui

I will close this issue. You can write if it does not work when a new version is published.

**Comment by Hayashi-Tensai** [comment]
ok noted, will check and see when a new version is released

**Comment by hakandundar34coding** [comment]
Latest version of the application (v1.13.0) is published. Update check feature is disabled by default. Some users may not want this option.

Enabling this option for one time is required to use it. You can follow these steps:

- Manually update it for v1.13.0
- Enable this option (from Main menu > Settings)
- Close the application and reopen it.

It will check for the updates after about 5 seconds.

**Comment by Hayashi-Tensai** [comment]
Regarding the update notification, I see that the latest version right now is v1.15.0 but I'm not seeing an update notification
![image](https://user-images.githubusercontent.com/30492689/168858993-90cbb56d-1c1b-4bac-aca1-bf48a5859376.png)
I have the checkbox checked as well
![image](https://user-images.githubusercontent.com/30492689/168859360-c848a7d5-e4d2-4740-810b-b57591d8dc9b.png)


I'm currently running v1.14.0 (I installed my installation using pip3)
![image](https://user-images.githubusercontent.com/30492689/168859109-c7b44c9c-1106-440e-bec0-0fbf73e26036.png)

**Comment by hakandundar34coding** [comment]
For checking the updates automatically:
The application have to be opened with this option enabled. You can close and rerun the application if you enabled this option.
It will check the updates after about 5-10 seconds.

Can you also try running this command from terminal?
`pip index versions system-monitoring-center`

If you updated to v1.15.0, you can try again tomorrow. v1.16.0 will be downloadable tomorrow. But there are no changes for **update check** code.

**Comment by Hayashi-Tensai** [comment]
Even after leaving it open for a few minutes, it still does not have the notification

`pip index versions system-monitoring-center` returns me this response `ERROR: unknown command "index`

**Comment by hakandundar34coding** [comment]
What is your pip version?
You can use this command to learn it:
`pip --version`

pip 22.0.4 is installed on my system and it works. `index` parameter is not supported by the pip on your system.

**Comment by Hayashi-Tensai** [comment]
It was indeed because I was running and older pip version, it was running on 20.3.4
After I upgraded my pip version, the command you gave me worked and update notification also does appear as well now
Thanks for your help!

![image](https://user-images.githubusercontent.com/30492689/168982293-9211de2f-6e97-42e8-8663-71c6d4f568ef.png)

**Comment by hakandundar34coding** [comment]
You can enable the option for checking the updates again after installing v1.16.0 (tomorrow) because it will reset the settings. There are some changes for the application (performance, etc.) and they require resetting the settings.
