### ISSUE TITLE
Versioning in debian/changelog

### ISSUE THREAD

**Issue by hsbasu** [hakandundar34coding/system-monitoring-center#73]
In the release tag [v1.13.0-deb_for_stores](https://github.com/hakandundar34coding/system-monitoring-center/releases/tag/v1.13.0-deb_for_stores), even though `changes.md` has been updated to `v1.13.0-deb_for_stores`, `debian/changelog` has not been updated to `v1.13.0`. Such might conflict when built in Launchpad.

**Comment by hakandundar34coding** [comment]
The application is updated (v1.14.0) and changelog in the debian folder is also updated.
