### ISSUE TITLE
No graphics after installing from pip version?

### ISSUE THREAD

**Issue by ski007** [hakandundar34coding/system-monitoring-center#74]
I installed the program via pip ... and unfortunately I have some errors, i.e. no graphics, icons in the program?
Previously it was OK if I was installing from .deb
However, I wanted to be able to do a simple upgrade ... can I somehow fix / install some packages ???
![2](https://user-images.githubusercontent.com/50265514/166486449-286150dc-052e-4c7e-aba2-a325a1e58e47.png)
![1](https://user-images.githubusercontent.com/50265514/166486574-5abecf98-ac00-4b16-a853-31a27d4066df.png)
Ps.I restarted the system ... and the option did not help either
`touch ~/.local/share/*`

**Comment by ski007** [comment]
... I reinstalled the latest version from .deb and it's OK
from here:  [https://github.com/hakandundar34coding/system-monitoring-center/releases/tag/v1.13.0-deb_for_stores](url)
but the problem remained :-(

**Comment by ski007** [comment]
I am continuing to translate the program into Polish ... not quite yet, but I will improve over time. :-)
[https://github.com/ski007/system-monitoring-center/blob/master/locale/pl/system-monitoring-center.po](url)
unfortunately, I'm not an expert and I don't know if I have to do anything else?....
greetings

**Comment by hakandundar34coding** [comment]
Closing and reopening the application and/or restarting the system fixes GUI images problem. There is an explanation about GUI images on the project [page](https://github.com/hakandundar34coding/system-monitoring-center).

The application is updated (v1.14.0) and showing GUI images requires less effort.

Can you write if the latest version of the application has GUI image problems?

**Comment by ski007** [comment]
I updated the program from the command line
pip install --upgrade system-monitoring-center
restarted LinuxMint19.3Tricia (Ubuntu18.04)
I launched the program with a command from the terminal:
system-monitoring-center
with such an effect :-(
I also typed into the terminal
`touch ~ / .local / share / *`
no improvement...
![Zrzut ekranu z 2022-05-05 15-34-09](https://user-images.githubusercontent.com/50265514/166936479-7fd5c563-502f-4ccf-82a1-81a4cc5ca291.png)
maybe these are some bugs related to my Ubuntu 18.04 based system...

**Comment by hakandundar34coding** [comment]
I have tested the application on Ubuntu 18.04 and Linux Mint 20.2 on virtual machines:

1. From the source code.
2. Installation by using .deb package.

GUI images are shown in both situations.
![smc_gui_images](https://user-images.githubusercontent.com/90193017/166951905-b35883da-8caa-414c-839f-295346fbe6fb.png)

---------------------------------

Are there any files in this folder?
`/home/[user_name]/.local/share/icons/hicolor/scalable/actions`

**Comment by ski007** [comment]
strange thing ... it's OK for me only when installing from a .deb file 
YES ... there are icon files with the extension .svg in this location

**Comment by hakandundar34coding** [comment]
Did you removed .deb version before installing by using pip?

**Comment by ski007** [comment]
Yes ! ...now i only use the version installed from pip option.
![Zrzut ekranu z 2022-05-05 17-18-03](https://user-images.githubusercontent.com/50265514/166956289-4c5fea84-80f2-454b-bda2-05e1e6e966de.png)

**Comment by hakandundar34coding** [comment]
Can you try these steps?

- Remove all versions of the application.
- Delete system-monitoring-center*.svg files in:

```
  /home/[user_name]/.local/share/icons/hicolor/scalable/actions
  /home/[user_name]/.local/share/icons/hicolor/scalable/apps
```

- Delete `com.github.hakand34.system-monitoring-center.desktop` file in:

  `/home/[user_name]/.local/share/applications`

- Install the application by using pip.
- Run the application by using `system-monitoring-center`
- Restart the system
- Run the application by using its shortcut in the system menu (or command line).

**Comment by ski007** [comment]
I did the whole procedure but to no avail.
After restarting the system, no matter how I run the program, whether from the menu or in the terminal ... the effect is the same :-)
![Zrzut ekranu z 2022-05-05 17-35-47](https://user-images.githubusercontent.com/50265514/166960363-5d5d095e-419b-4a0a-b1a6-6f2f753222f6.png)

**Comment by hakandundar34coding** [comment]
I have installed Linux Mint 19.3 on virtual machine.

Images are shown if the application is run from the source code.
![smc_gui_test](https://user-images.githubusercontent.com/90193017/166964132-6e6040dc-0257-4d70-af28-16e3144b9277.png)


This version of the Linux Mint distribution has old versions of the packages.
Were there any pycairo and pygobject build problems on your system? They are not installed during the test.

**Comment by ski007** [comment]
> Were there any pycairo and pygobject build problems on your system?

I have no idea ? ... how to check if everything is OK?
For now, I have installed the version from the .deb file ... it's OK
![Zrzut ekranu z 2022-05-05 17-53-22](https://user-images.githubusercontent.com/50265514/166964261-1b945a8b-3390-4d17-aa37-c921ba1d6ab9.png)

**Comment by hakandundar34coding** [comment]
Are there any image problems if you follow these steps?

- Remove .deb version of the application.
- Download the source [code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it.
- Run this command in `src` folder: `python3 Main.py`

**Comment by ski007** [comment]
I guess there is something wrong with my system :-(
no icons used in the program
![Zrzut ekranu z 2022-05-05 18-29-55](https://user-images.githubusercontent.com/50265514/166970244-772a4f42-991a-4659-a684-af63ee117e58.png)

**Comment by hakandundar34coding** [comment]
There was no image problem during my [test](https://github.com/hakandundar34coding/system-monitoring-center/issues/74#issuecomment-1118735664).

GUI images in the `/home/[user_name]/.local/share/icons/hicolor/scalable/...` folder are not used on your system. Images in this folder are used if the application is installed as a Python package (by using pip).

There may be a problem on your system. I do not know the details of this problem. The application worked on several distributions on virtual machines.

I will close this issue. But you can write additional comments.

**Comment by ski007** [comment]
Thanks for your help ... I'm switching to .deb :-)
I will still look for a solution ... maybe I will come across something
regrds
