### ISSUE TITLE
GPU usage not working on Intel iGPU

### ISSUE THREAD

**Issue by babam86** [hakandundar34coding/system-monitoring-center#79]
GPU Usage not working on Intel UHD G4 (i3-1115G4) and Irish Xe G7 (i5-1135G7)

Thanks.

**Comment by hakandundar34coding** [comment]
GPU usage and GPU memory information is not supported for integrated Intel GPUs.
There is a tool to get GPU load of Intel GPUs (intel_gpu_top). But this tool requires root privileges.

**Comment by babam86** [comment]
Is by installing intel_gpu_top and running system-monitoring-center as root then GPU usage can work?

**Comment by hakandundar34coding** [comment]
Using subprocess module like it is used for getting information from other CLI tools such as systemctl did not work. intel_gpu_top tool updates the information in a different way. There may be additional improvements for Intel GPU load in the newer releases. Currently it is not supported.

I will close this issue. But you can write additional comments.
