### ISSUE TITLE
Processes does not update automatically.

### ISSUE THREAD

**Issue by babam86** [hakandundar34coding/system-monitoring-center#80]
The Processes does not update automatically, for example: Run system-monitoring-center then run any program (e.g. mousepad) then the mousepad does not appear in the process list.

Thanks.

**Comment by hakandundar34coding** [comment]
Can you run the application from terminal, open Processes tab and share the terminal output?

**Comment by babam86** [comment]
There is no output on the terminal, no standard output/standard error.

**Comment by hakandundar34coding** [comment]
Are there any updates for CPU, memory usages of the current processes?
What happens if you sort processes by CPU usages and perform some operations such as web browsing?
What is your distribution?
What are Python and Gtk versions? (You can find this information on the System tab.)

**Comment by babam86** [comment]
Distro: Slackware 15.0

1. Run system-monitoring-center
2. Run any application (e.g. mousepad)
The result is no mousepad on Processes tab (sort by PID)

You have to restart system-monitoring-center then the mousepad appears in the Processes tab.

Thanks.

**Comment by hakandundar34coding** [comment]
Did you change the update interval setting?
Can you share a screenshot of the System tab of the System Monitoring Center?

**Comment by babam86** [comment]
Sorry this was my mistake, now it's working properly.

This is my first day using system-monitoring-center and I love it.

Thanks.
