### ISSUE TITLE
Don't show loop and ramdisk devices by default

### ISSUE THREAD

**Issue by babam86** [hakandundar34coding/system-monitoring-center#81]
It's better if loop devices don't show by default in Performance tab --> Disk

Loop devices /dev/loop* are usually squashfs or iso files (read only).

Thanks.

**Comment by hakandundar34coding** [comment]
This feature may be added in the newer versions of the application.

I will close this issue. You can write comments if you want to add something.

**Comment by hakandundar34coding** [comment]
There is another [issue](https://github.com/hakandundar34coding/system-monitoring-center/issues/78#issuecomment-1134834018) which contains comments about a similar feature.

**Comment by Botspot** [comment]
Copying from issue #78, a reliable way to find only valid writable drives is to filter the "Major device number"
Example command that successfully hides ram, zram, and loop devices: `lsblk -I 8,179,259 -rno NAME`

**Comment by hakandundar34coding** [comment]
This feature will be added in v1.18.0 (next week). It will be tested on different distributions.
v1.17.0 will be downloadable in a few days.

@Botspot 
Can you share output of `cat /proc/mounts` command? You can write only the lines for ram[NUMBER] disks if there is sensitive information in the output of the command.

Update: In most cases, files are used instead of CLI tools in order to obtain lower CPU usage. Because a lot of functions are called repeatedly for getting/updating the performance/usage data. CLI tools are used if there are no files to get required data. For example: for getting file system of USB disk, service information (systemctl), etc.

@Botspot, @babam86 
These two ways can be used for this feature:
1) Using `ro` information in the /proc/mounts file. But optical disk (not loop disk) may be hidden in this situation if a CD/DVD is inserted.
2) Using file systems such as iso9660, squashfs, etc. Probably this information will be used. This information can be get from /proc/mounts file.

What do you suggest? What problems can be encountered in one of these ways? Or another way to filter disks such as loop0, ram0, etc.

**Comment by babam86** [comment]
I chose to filter read-only filesystems on loop devices (iso9660, squashfs, etc)

The CD/DVD drives are writable (using a burning tool)

**Comment by theofficialgman** [comment]
> @Botspot Can you share output of `cat /proc/mounts` command? You can write only the lines for ram[NUMBER] disks if there is sensitive information in the output of the command.

/proc/mounts does not have any lines with ram# or loop#. those are only coming from your listing `/sys/class/block`

**Comment by theofficialgman** [comment]
looking at lsblk https://github.com/util-linux/util-linux/blob/master/misc-utils/lsblk.c it simply ignores values of `ram` and `loop` by default

**Comment by hakandundar34coding** [comment]
@theofficialgman 
> /proc/mounts does not have any lines with ram# or loop#.

loop# disks are listed in this file if iso files are mounted. There are no ram# disks on my system.

**Comment by hakandundar34coding** [comment]
@Botspot 
I have generated ramdisk on a virtual machine. It worked but it is not listed as a disk. They are listed as disks on your system.

Can you share output ıf this command?
`cat /proc/mounts`

**Comment by babam86** [comment]
Just filter it using the "ro" information in the /proc/mounts for loop# and ram# devices.

**Comment by hakandundar34coding** [comment]
@babam86 
Other disks may be hidden in this situation.

@Botspot 
There may be useful information in the content of the `/proc/mounts` file.

**Comment by theofficialgman** [comment]
@hakandundar34coding I have ram# disks showing in system monitoring center under the disk tab. there are no ram# in /proc/mounts, these aren't ramdisks created by me. ram# show in /sys/class/block and this appears to be normal (16 of them to be exact). the /sys/class/block/ram# are NOT mounted and all have 8MB size on my system.

<https://www.kernel.org/doc/html/v5.6/admin-guide/blockdev/ramdisk.html#:~:text=The%20RAM%20disk%20driver,or%20rescue%20floppy%20disk.>

> The RAM disk driver is a way to use main system memory as a block device. It is required for initrd, an initial filesystem used if you need to load modules in order to access the root filesystem (see Documentation/admin-guide/initrd.rst). It can also be used for a temporary filesystem for crypto work, since the contents are erased on reboot.
> 
> The RAM disk dynamically grows as more space is required. It does this by using RAM from the buffer cache. The driver marks the buffers it is using as dirty so that the VM subsystem does not try to reclaim them later.
> 
> The RAM disk supports up to 16 RAM disks by default, and can be reconfigured to support an unlimited number of RAM disks (at your own risk). Just change the configuration symbol BLK_DEV_RAM_COUNT in the Block drivers config menu and (re)build the kernel.
> 
> To use RAM disk support with your system, run ‘./MAKEDEV ram’ from the /dev directory. RAM disks are all major number 1, and start with minor number 0 for /dev/ram0, etc. If used, modern kernels use /dev/ram0 for an initrd.
> 
> The new RAM disk also has the ability to load compressed RAM disk images, allowing one to squeeze more programs onto an average installation or rescue floppy disk.

**Comment by Botspot** [comment]
> I have ram# disks showing in system monitoring center under the disk tab. there are no ram# in /proc/mounts, these aren't ramdisks created by me.

Same here.

**Comment by babam86** [comment]
This is my suggestion,

Do not show ramdisk devices.

Only show loop devices that have "rw" in the /proc/mounts

Only show zram devices that have "rw" in the /proc/mounts

**Comment by hakandundar34coding** [comment]
@babam86, @Botspot, @theofficialgman

I have updated the source code.

loop, ramdisk (ram#) and zram disks can be hidden (default). Disk names are used for determining the disks to be hidden.

Can you follow these steps if you want to test this feature?

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it and open a terminal in `src` folder.
- Run this command: `python3 Main.py`
- Open Disk tab and open customizations menu of this tab.
- Disable/enable `Hide loop, ramdisk, zram disks` option and check disk list.
- Also check the terminal window to see if there are errors.

**Comment by theofficialgman** [comment]
@hakandundar34coding latest source works as expected. there are no errors in the terminal log.
disable/enable works correctly

**Comment by Botspot** [comment]
I found a simple bug:
If "All devices" is enabled in combination with "Hide loop, ramdisk, zram devices", the full summary of these 'hidden' devices will still appear.
![2022-05-30-230904_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/171091183-8cbfd59d-0390-4b07-bf2f-db77eeb5f1ed.png)

**Comment by hakandundar34coding** [comment]
The bug is fixed and the source code is updated.
Are there any other problems?

There will be a new package (v1.18.0) in 2 days. This package will contain the latest changes.

**Comment by Botspot** [comment]
> Are there any other problems?

Not that I'm aware of. This system monitor is really slick now and it's my new go-to for most things.
Thanks for your continued work on this, @hakandundar34coding.

**Comment by theofficialgman** [comment]
I'd also like to say thank you for your continued work on this application.

while I have seen and used other linux applications that each have part of the functionality of this one, none of them have all of it. As a previous windows user (now using linux fulltime), this is an easy recommendation from me as a replacement for the windows task manager, hwinfo, and other programs we have over there.

**Comment by hakandundar34coding** [comment]
Additional information:
Some suggested ways to filter disks had some problems on some systems and after some tests they are not used. For example: system disk would be hidden on some virtual machines, etc. Currently disk names are used instead of them.

@babam86
Are there any problems when using this option?

**Comment by hakandundar34coding** [comment]
@babam86 
I will close this issue. But you can write comments if there are any problems when the option for hiding loop, ramdisk and zram devices.
