### ISSUE TITLE
AMD FX series 8 core CPU is reported as 4 (physical) - 8 (logical) cores

### ISSUE THREAD

**Issue by spsf64** [hakandundar34coding/system-monitoring-center#84]
I think my old AMD 8350 has 8 physical cores, not sure though...
See attached image
![amd](https://user-images.githubusercontent.com/1877391/170503580-8a91eabb-d99f-4681-86ff-5aa32787d841.jpeg)

**Comment by hakandundar34coding** [comment]
I have read about this CPU from several sources and it has 8 physical, 8 logical cores.

Can you share full output of this command?
`cat /proc/cpuinfo`

**Comment by spsf64** [comment]
Sure:
https://pastebin.com/LXaJxvsL

> I have read about this CPU from several sources and it has 8 physical, 8 logical cores.
> 
> Can you share full output of this command? `cat /proc/cpuinfo`

**Comment by theofficialgman** [comment]
the number of cores is correct and so is the logical cores. the way linux interprets that CPU architecture is it has 4 cores with 8 threads and thats how its scheduler uses it. AMD marketing was misleading.

you can watch a good video on the architecture of the FX cpus here: https://www.youtube.com/watch?v=PgejkSWzvNs

this is not a bug. 2 integer clusters share cache and a single FPU.

**Comment by spsf64** [comment]
Ok, thank you for your response and for this great program!

**Comment by hakandundar34coding** [comment]
@theofficialgman 
Very interesting hardware information [again](https://github.com/hakandundar34coding/system-monitoring-center/issues/82#issuecomment-1134880964).
