### ISSUE TITLE
Suggestion: Add Delete hotkey to terminate processes and allow selection of multiple processes

### ISSUE THREAD

**Issue by BowDown097** [hakandundar34coding/system-monitoring-center#88]
These would be very neat QOL features to have. I was surprised to not see them here already as most task managing/system monitoring/etc. programs have these features.

**Comment by babam86** [comment]
I have a suggestion for hotkeys,

S --> Stop Process
C --> Continue Process
T --> Terminate Process
K --> Kill Process

Thanks.

**Comment by hakandundar34coding** [comment]
@BowDown097, @babam86 
Keyboard shortcuts can be added for Processes tab.

S, C, T, K keys can be used with Ctrl key. Because single keys may be pressed unintentionally.
Ctrl + S, 
Ctrl + C, 
Ctrl + T, 
Ctrl + K.

**Comment by babam86** [comment]
@hakandundar34coding 
Yes, it's very good

**Comment by hakandundar34coding** [comment]
Keyboard shortcuts feature is added for the Processes tab. It can be used after installing the latest version (v1.20.0) of the application.

You can write comments if there are problems when using this feature.

**Comment by babam86** [comment]
@hakandundar34coding 
Does it support multiple selection?

**Comment by hakandundar34coding** [comment]
@babam86
Currently multiple selection is not supported. Some code changes are reuqired for this feature. For example, modifying multiple processes (changing priority, stopping, etc.) or opening details windows of multiple processes.

This feature may be added in the newer versions after the required code changes.

**Comment by babam86** [comment]
@hakandundar34coding 

The ability for multiple selection to kill/terminate processes is more important in my opinion.

Thanks.
