### ISSUE TITLE
Suggestion: Make it possible for temperature to be displayed in Fahrenheit

### ISSUE THREAD

**Issue by nlwGH** [hakandundar34coding/system-monitoring-center#89]
A really useful app!! Well done.

Please make it possible for temperatures to be displayed in Fahrenheit.

Kind regards,

**Comment by hakandundar34coding** [comment]
This feature may be added in the newer versions. Currently it has lower priority. Some other features/problems will be improved/fixed.

I will close this issue. But you can write comments or open a new issue if there are problems.

**Comment by nlwGH** [comment]
Thank you for your reply.
I send you all good wishes on your terrific work.
Your app is extremely useful.
 
 
-----Original Message-----
