### ISSUE TITLE
Processes not showing in Manjaro Linux

### ISSUE THREAD

**Issue by cryptolog89** [hakandundar34coding/system-monitoring-center#9]
Throws an error in the terminal:
```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Processes.py", line 369, in processes_loop_func
    username = usernames_username_list[usernames_uid_list.index(real_user_id)]
ValueError: '62582' is not in list

```

**Comment by hakandundar34coding** [comment]
I have tried System Monitoring Center on Manjaro 21.1.6 on virtual machine. There is no problems for listing processes. Can you write here (or send an e-mail to me) output of this command?

```cat /etc/passwd```

You can find my e-mail address from my GitHub profile.

**Comment by cryptolog89** [comment]
> I have tried System Monitoring Center on Manjaro 21.1.6 on virtual machine. There is no problems for listing processes. Can you write here (or send an e-mail to me) output of this command?
> 
> `cat /etc/passwd`
> 
> You can find my e-mail address from my GitHub profile.

`root:x:0:0::/root:/bin/zsh
nobody:x:65534:65534:Nobody:/:/sbin/nologin
dbus:x:81:81:System Message Bus:/:/sbin/nologin
bin:x:1:1::/:/sbin/nologin
daemon:x:2:2::/:/sbin/nologin
mail:x:8:12::/var/spool/mail:/sbin/nologin
ftp:x:14:11::/srv/ftp:/sbin/nologin
http:x:33:33::/srv/http:/sbin/nologin
systemd-journal-remote:x:982:982:systemd Journal Remote:/:/sbin/nologin
systemd-coredump:x:981:981:systemd Core Dumper:/:/sbin/nologin
uuidd:x:68:68::/:/sbin/nologin
dnsmasq:x:980:980:dnsmasq daemon:/:/sbin/nologin
rpc:x:32:32:Rpcbind Daemon:/var/lib/rpcbind:/sbin/nologin
usbmux:x:140:140:usbmux user:/:/sbin/nologin
avahi:x:978:978:Avahi mDNS/DNS-SD daemon:/:/sbin/nologin
colord:x:977:977:Color management daemon:/var/lib/colord:/sbin/nologin
lightdm:x:620:620:Light Display Manager:/var/lib/lightdm:/sbin/nologin
nm-openconnect:x:976:976:NetworkManager OpenConnect:/:/sbin/nologin
nm-openvpn:x:975:975:NetworkManager OpenVPN:/:/sbin/nologin
ntp:x:87:87:Network Time Protocol:/var/lib/ntp:/bin/false
polkitd:x:102:102:PolicyKit daemon:/:/sbin/nologin
rtkit:x:133:133:RealtimeKit:/proc:/sbin/nologin
zer0x:x:1000:1001:zer0x:/home/zer0x:/bin/zsh
systemd-network:x:974:974:systemd Network Management:/:/sbin/nologin
systemd-resolve:x:973:973:systemd Resolver:/:/sbin/nologin
systemd-timesync:x:972:972:systemd Time Synchronization:/:/sbin/nologin
geoclue:x:971:971:Geoinformation service:/var/lib/geoclue:/sbin/nologin
git:x:970:970:git daemon user:/:/usr/bin/git-shell
tox-bootstrapd:x:199:199:Tox bootstrapd:/:/sbin/nologin
tor:x:43:43::/var/lib/tor:/sbin/nologin
cups:x:209:209:cups helper user:/:/sbin/nologin
ceph:x:340:340::/run/ceph:/sbin/nologin
gluster:x:969:969:GlusterFS daemons:/var/run/gluster:/sbin/nologin
transmission:x:169:169:Transmission BitTorrent Daemon:/var/lib/transmission:/sbin/nologin
i2pd:x:619:619::/var/lib/i2pd:/bin/bash
unbound:x:966:966:unbound:/etc/unbound:/sbin/nologin
flatpak:x:965:965:Flatpak system helper:/:/usr/bin/nologin
clamav:x:64:64:Clam AntiVirus:/:/usr/bin/nologin
deluge:x:962:962:Deluge BitTorrent daemon:/srv/deluge:/usr/bin/nologin
dhcpcd:x:961:961:dhcpcd privilege separation:/var/lib/dhcpcd:/usr/bin/nologin
_easytether:x:617:617:easytether:/:/usr/bin/nologin
mpd:x:45:45::/var/lib/mpd:/usr/bin/nologin
named:x:40:40:BIND DNS Server:/:/usr/bin/nologin
sndiod:x:616:616::/var/lib/sndiod:/bin/false
lxdm:x:960:960:Lightweight X11 Display Manager:/var/lib/lxdm:/usr/bin/nologin
redsocks:x:959:959:redsocks nologin sysuser:/:/usr/bin/nologin
privoxy:x:42:42:Privoxy:/:/usr/bin/nologin
openvpn:x:958:958:OpenVPN:/:/usr/bin/nologin
brltty:x:957:957:Braille Device Daemon:/var/lib/brltty:/usr/bin/nologin
mysql:x:956:956:MariaDB:/var/lib/mysql:/usr/bin/nologin
saned:x:955:955:SANE daemon user:/:/usr/bin/nologin
systemd-oom:x:953:953:systemd Userspace OOM Killer:/:/usr/bin/nologin
tss:x:967:967:tss user for tpm2:/:/usr/bin/nologin
`

**Comment by hakandundar34coding** [comment]
There is no line for ```62582```.

I will fix this problem.

What is the name of this process of which UID is not in the ```/etc/passwd``` file?

Can you copy this Python code and paste in a file named ```process_test.py``` and run the following command to get name of this process? After that you can write output to here.

Code to run the python code:
```python3 ./process_test.py```


Python code to copy and paste into ```process_test.py```:

```
import os

pid_list = [filename for filename in os.listdir("/proc/") if filename.isdigit()]

for pid in pid_list[:]:
    try:
        with open("/proc/" + pid + "/status") as reader:
            proc_pid_status_lines = reader.read().split("\n")
    except FileNotFoundError:
        pid_list.remove(pid)
        continue
    for line in proc_pid_status_lines:
        if "Uid:\t" in line:
            real_user_id = line.split(":")[1].split()[0].strip()
            if real_user_id == "62582":
                with open("/proc/" + pid + "/comm") as reader:
                    comm = reader.read().split("\n")
                print(pid, comm)

```

**Comment by cryptolog89** [comment]
> There is no line for `62582`.
> 
> I will fix this problem.
> 
> What is the name of this process of which UID is not in the `/etc/passwd` file?
> 
> Can you copy this Python code and paste in a file named `process_test.py` and run the following command to get name of this process? After that you can write output to here.
> 
> Code to run the python code: `python3 ./process_test.py`
> 
> Python code to copy and paste into `process_test.py`:

`python3: can't open file '/home/zer0x/./process_test.py': [Errno 2] No such file or directory
`

**Comment by hakandundar34coding** [comment]
You can run the code if you open terminal in the same folder.

Otherwise run the code by using full path. For example:
```python3 /home/[username]/desktop/a_folder/process_test.py```
