### ISSUE TITLE
GPU PCI address is not detected if PCI address contains letters

### ISSUE THREAD

**Issue by adolfotregosa** [hakandundar34coding/system-monitoring-center#90]
![image](https://user-images.githubusercontent.com/7437931/172229311-9d23621d-6b6d-4b9a-9908-046865e77d4a.png)
![image](https://user-images.githubusercontent.com/7437931/172230037-28175780-bd11-4606-900c-dffed0d89a4e.png)

When I click GPU tab this happens and . What am I doing wrong ?

Thank you for your time

System info
![image](https://user-images.githubusercontent.com/7437931/172229476-4dfd0679-8534-4f66-a4b1-f5bbc19a36a0.png)

**Comment by hakandundar34coding** [comment]
Can you write output of this command (from terminal)?
`nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics,power.draw --format=csv`

Do you use some configurations to use your NVIDIA GPU from QEMU virtual machine?

**Comment by adolfotregosa** [comment]
> Can you write output of this command (from terminal)? `nvidia-smi --query-gpu=gpu_name,gpu_bus_id,driver_version,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used,temperature.gpu,clocks.current.graphics,clocks.max.graphics,power.draw --format=csv`
> 
> Do you use some configurations to use your NVIDIA GPU from QEMU virtual machine?

seams to work fine. 
![image](https://user-images.githubusercontent.com/7437931/172322023-605402dd-78c6-45c9-b3cd-bdd2f01709dc.png)

**Comment by hakandundar34coding** [comment]
Can you share output of this command?
`cat /sys/class/drm/card[CARD_NUMBER]/device/uevent`
CARD_NUMBER may be 0, 1 or a different number which depends on number of GPUs on your system.

For example
`cat /sys/class/drm/card0/device/uevent`

**Comment by adolfotregosa** [comment]
> Can you share output of this command? `cat /sys/class/drm/card[CARD_NUMBER]/device/uevent` CARD_NUMBER may be 0, 1 or a different number which depends on number of GPUs on your system.
> 
> For example `cat /sys/class/drm/card0/device/uevent`

sure.

![image](https://user-images.githubusercontent.com/7437931/172387804-c1d6b359-91c1-461c-be0d-b639f35dd91e.png)


Isn't this ""UnboundLocalError: local variable 'gpu_info_line_no' referenced before assignment" the issue?

**Comment by hakandundar34coding** [comment]
I have updated the source code. Can you follow these steps?

Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
Extract it and open a terminal in src folder.
Run this command: `python3 Main.py`
Open GPU tab.
Check the terminal window to see if there are errors.

**Comment by adolfotregosa** [comment]
> I have updated the source code. Can you follow these steps?
> 
> Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip). Extract it and open a terminal in src folder. Run this command: `python3 Main.py` Open GPU tab. Check the terminal window to see if there are errors.

Yeah, seams to work fine ! (expect resolution, should be 3840x2160)
![image](https://user-images.githubusercontent.com/7437931/172395796-a93e15ce-5245-48d2-9164-9f617ef881f4.png)

**Comment by hakandundar34coding** [comment]
How many monitors do you have?

**Comment by adolfotregosa** [comment]
> How many monitors do you have?

Just this one 
![image](https://user-images.githubusercontent.com/7437931/172396523-1e942f66-88b2-47ba-9a36-64c3482baa5e.png)
![image](https://user-images.githubusercontent.com/7437931/172396691-8325edd7-a89e-47e2-9d34-32e4f8d2d8ec.png)

**Comment by hakandundar34coding** [comment]
Can you add these lines into a file (test.py), save it and run it?
```
#!/usr/bin/env python3

import gi
gi.require_version('Gdk', '3.0')
from gi.repository import Gdk

current_screen = Gdk.Screen.get_default()
current_resolution = str(current_screen.get_width()) + "x" + str(current_screen.get_height())

print(current_resolution)
```

**Comment by adolfotregosa** [comment]
> Can you add these lines into a file (test.py), save it and run it?
> 
> ```
> #!/usr/bin/env python3
> 
> import gi
> gi.require_version('Gdk', '3.0')
> from gi.repository import Gdk
> 
> current_screen = Gdk.Screen.get_default()
> current_resolution = str(current_screen.get_width()) + "x" + str(current_screen.get_height())
> 
> print(current_resolution)
> ```

yeah, something is reporting the wrong resolution.
![image](https://user-images.githubusercontent.com/7437931/172397937-78ebe933-fd92-49fa-a482-ffdb822879d7.png)

**Comment by hakandundar34coding** [comment]
What is your Gtk version?
You can learn this information from the System tab.

**Comment by adolfotregosa** [comment]
> What is your Gtk version? You can learn this information from the System tab.

hopefully this answers you

![image](https://user-images.githubusercontent.com/7437931/172400051-d493ac36-943a-4af7-bdb5-4c1d42157ac7.png)

**Comment by hakandundar34coding** [comment]
There are some problems when GTK 3 is used for getting screen refresh rate and resolution. Some code in GTK 3 is deprecated. It detects screen resolution wrong on your system. I did not use xrandr for getting this information because GTK code was faster. xrandr is used in some situations. Currently there will not be changes for this feature.

There will be a new package (v1.19.0) in 2 days. This package will contain the latest updates. There may be some updates for screen resolution feature in v1.20.0.

**Comment by adolfotregosa** [comment]
No problem. It really is not an issue, just a comment. Thank you for your time !

**Comment by hakandundar34coding** [comment]
I will try to improve the code for the systems similar to your system. Updates for the resolution problem will be available in v1.20.0 (probably in 7-10 days).

**Comment by hakandundar34coding** [comment]
System Monitoring Center v1.19.0 can be installed. This version contains the changes for GPU tab error.

----------------------------

There may be improvements for screen resolution problems in the newer versions.

**Comment by hakandundar34coding** [comment]
I have updated the source code for the screen resolution problem on the systems with modified screen scale.

Can you follow these steps if you want to test it?

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it and open a terminal in `src` folder.
- Run this command: `python3 Main.py`
- Open GPU tab and check screen resolution.
- Also check the terminal window to see if there are errors.

**Comment by adolfotregosa** [comment]
Hi!
Seams to be working fine

![image](https://user-images.githubusercontent.com/7437931/174655584-ce1f536f-6e17-47f9-8cf6-92426c3fa849.png)

**Comment by hakandundar34coding** [comment]
A new package will be downloadable in 2 days. This package will contain the latest changes and bug fixes.
