### ISSUE TITLE
Suggestion: leftbar is too thin,too low. at disk.

### ISSUE THREAD

**Issue by hitobashira** [hakandundar34coding/system-monitoring-center#91]
nvme0n1pNNN
![2022-06-09_13-02](https://user-images.githubusercontent.com/12706780/172762127-095811a2-8832-488b-867c-f10e9453f2bc.png)
.

**Comment by hakandundar34coding** [comment]
Text fonts are very big on the screenshot. Did you change it?

There may be minor improvements for increasing the width of the device list in the newer versions.

**Comment by hakandundar34coding** [comment]
I have tested the application on a virtual machine. The system language was Japanese. Text font size was not similar to the one in the screenshot that you shared.

In v1.19.0 version of the application, Summary tab is added. Device selection list is wider when compared to the previous version.
Also `nvme0n1p13` name is visible. Disk usage percentage is visible partially but this information can be viewed buy using scrollbars of the device selection list. Also `nvme0n1p13` is a very long disk name and many NVMe disks have name such as `nvme0n1p1`, `nvme0n1p2`, etc. Therefore disk usage percent can be viewed on these systems without scrolling.

Paned window widget may be used in the newer versions of the application for changing width of the device selection list by using handles to drag and resize it.

Example screenshot (disk names are changed to `nvme0n1p13` to test the width):

![smc_disk_name_test](https://user-images.githubusercontent.com/90193017/173192310-c151cbd5-cb07-4fdf-be8b-c176faf97585.png)

I will close this issue. Currently there will be no additional changes for device selection list size in a short time.
