### ISSUE TITLE
Suggestion: Select multiple disks

### ISSUE THREAD

**Issue by theCalcaholic** [hakandundar34coding/system-monitoring-center#92]
It would be cool, if we could select multiple disks at once (should be a low hanging fruit, as the application can already display *all* disks at once).

I would prefer the plots to be drawn in different colors in the same graph though, but that's a matter of taste I suppose.

**Comment by hakandundar34coding** [comment]
Read/write speed of all disks can be shown at the same time.

But every disk may have very different graph scale because of the read/write speed. One disk may have 20 KiB/s and another disk may have 400 MiB/s. Lines of the some disks may not be visible if they have different speeds. Using different graphs per-disk is more useful. Graph scales are not fixed at 100% unlike CPU and RAM graphs.

Every graph has its disk name on the upper-left corner. In this situation, there is no need for different colors. This feature would have extra complexity.

**Comment by theCalcaholic** [comment]
Well, the single graph feature is only the less important aspect of my feature request. The reason why I want to do this, is mainly, to identify disk activity that belongs together (e.g. reading from /dev/sda, writing to /dev/sdb in a copy process). If the graphs are aligned, I can easily identify, what's my bottleneck, for example. I agree with you though, that dynamic maxima make this difficult - maybe multiple stacked graphs make more sense than one single graph (e.g. add a toggle to show all graphs in a single row)?

However, even without plots that are vertically aligned (they could also be stacked atop each other, instead of being drawn in the same graph), it would make sense to be able to select multiple disks at once.

For example, if I let it show *all* disks, that results in 18 tiny graphs displayed in a grid (with loop, ramdisk, zram disk already hidden). That's makes it harder than necessary to identify the disks I'm interested in:

![image](https://user-images.githubusercontent.com/6317548/173090142-06962965-98e6-4c94-aa15-d5d49f9df8d0.png)

Instead I'd like to only select a few of these devices

**Comment by hakandundar34coding** [comment]
Checkboxes may be added on the left side of the disk names in the disk selection list. These checkboxes can be used for showing/hiding the disks.

But this feature may be added some versions later. It requires some detailed changes. Before that some other features/problems will be improved/fixed.

**Update:**
I will close this issue. This feature requires extra complexity and currently it has very low priority when compared to other parts of the application. It is a detailed feature for an application which is designed for desktop computers.

Additional comments and latest plans may be written here if the feature is not removed from the to-do-list.
