### ISSUE TITLE
Services tab on Distros that don't use Systemd

### ISSUE THREAD

**Issue by babam86** [hakandundar34coding/system-monitoring-center#95]
I'm a Porteus user (Slackware based) and it uses a BSD-style init system.

Is it possible for SMC to support Slackware and its derivatives for the Services tab.

Or give it the ability to hide the Services tab because it's useless on Distros that don't use Systemd.

Thanks.

**Comment by hakandundar34coding** [comment]
Support for init systems other than systemd is not easy. Because I use a distribution which uses systemd. Installing other distributions with different init systems, learning them, fixing problems of them requires some time. Currently there are no plans for that.

For hiding the Services tab:
Init system of the distribution have to be checked when the application is started. This process can be performed by using systemctl program of systemd. But this operation would increase the start time (maybe two times slower) of the System Monitoring Center. Currently there will be no changes.

**Comment by babam86** [comment]
To keep things simple, add an option in the settings to hide the Services tab.

There's no need to check the init system just to hide the Services tab.
No need to use systemctl to do that.

Thanks.

**Comment by hakandundar34coding** [comment]
I have found another way for hiding Services tab automatically and its effect on start speed is negligible. The code checks name of the process with PID 1 which is used by systemd.

You can follow these steps if you want to test it.

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it and open a terminal in `src` folder.
- Run this command: `python3 Main.py`
- Check if Services tab is hidden.
- Also check the terminal window to see if there are errors.

**Comment by babam86** [comment]
Services tab is still showing/not hidden.

`python3 Main.py`

Traceback (most recent call last):
  File "/tmp/B2M/system-monitoring-center-master/src/MainGUI.py", line 255, in on_main_gui_tab_radiobuttons_toggled
    self.main_gui_tab_switch_func()
  File "/tmp/B2M/system-monitoring-center-master/src/MainGUI.py", line 489, in main_gui_tab_switch_func
    Services.services_initial_func()
  File "/tmp/B2M/system-monitoring-center-master/src/Services.py", line 179, in services_initial_func
    services_loop_func()
  File "/tmp/B2M/system-monitoring-center-master/src/Services.py", line 217, in services_loop_func
    service_unit_file_list = [filename for filename in os.listdir(service_unit_files_dir) if filename.endswith(".service")]    # Get file names which ends withs ".service".
FileNotFoundError: [Errno 2] No such file or directory: '/lib/systemd/system/'

**Comment by hakandundar34coding** [comment]
What are the process names for with PID 1 and 2? You can use Processes tab for checking this.

The source code is updated.

**Comment by babam86** [comment]
PID 1 --> init
PID 2 --> kthreadd

**Comment by babam86** [comment]
Now working great and startup is fast.

Thanks.

**Comment by hakandundar34coding** [comment]
A new package (v1.22.0) can be installed. It contains the changes for the Services tab.
