### ISSUE TITLE
Enhancement: main overview screen

### ISSUE THREAD

**Issue by EysseW** [hakandundar34coding/system-monitoring-center#96]
I don't want to spread hate, but I think the main menu needs some work; it doesn't fit in the overall theme of the application. I would like to offer my help making it look nice.

**Comment by hakandundar34coding** [comment]
Which part of the GUI requires some work? Summary tab or Main menu (it is shown when a button on the window title is clicked)? Different things are written in the title of the issue and comment.

About the Summary tab:
There may be some changes for the Summary tab ([details](https://github.com/hakandundar34coding/system-monitoring-center/commit/867b6f2b88df7d258bfb97309d561db6c00c1b51#commitcomment-75847456) at the end of the page).


> I would like to offer my help making it look nice.

What are your thoughts?

**Comment by hakandundar34coding** [comment]
It has been about 23 days after the last comment. But there is no answer.

There may be improvements for the graphs on the Summary tab in the newer versions. But it has lower priority when compared to the other parts of the application.

I will close this issue. But you can write comments.

**Comment by EysseW** [comment]
I went on vacation and kinda forgot to respond, I'm sorry. 
My problem with the summary screen is mainly the fact that it doesn't fit with themes. [This](https://imgur.com/M2TyluT) is a screenshot of my desktop with it open. You can see I use the the gruvbox theme, but the summary screen is blue.
With the offering help I meant making a design, purely. I can't code :(

**Comment by EysseW** [comment]
Are you reading this?

**Comment by hakandundar34coding** [comment]
I know it there are some visual problems (contrast) on different themes. But I have not redesigned the Summary tab. I do not want to make big changes on the graphics. Because it is not easy to draw a new graph with that details.
