### ISSUE TITLE
Error while getting IP addresses on Slackware distribution

### ISSUE THREAD

**Issue by babam86** [hakandundar34coding/system-monitoring-center#97]
On Slackware the "ip" command is only available for root.

`system-monitoring-center`
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Network.py", line 115, in network_initial_func
    network_address_ipv4, network_address_ipv6 = self.network_address_ipv4_ipv6_func(selected_network_card)
  File "/usr/share/system-monitoring-center/src/Network.py", line 242, in network_address_ipv4_ipv6_func
    ip_output_lines = (subprocess.check_output(["ip", "a", "show", selected_network_card], shell=False)).decode().strip().split("\n")
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ip'

**ip** --> **/sbin/ip**

`diff -Naur 'a/Network.py' 'b/Network.py'`
--- a/Network.py	2022-06-25 20:13:00.296840881 +0700
+++ b/Network.py	2022-06-25 20:06:16.000000000 +0700
@@ -239,7 +239,7 @@
     # ----------------------- Get network card IPv4 and IPv6 addresses -----------------------
     def network_address_ipv4_ipv6_func(self, selected_network_card):
 
-        ip_output_lines = (subprocess.check_output(["ip", "a", "show", selected_network_card], shell=False)).decode().strip().split("\n")
+        ip_output_lines = (subprocess.check_output(["/sbin/ip", "a", "show", selected_network_card], shell=False)).decode().strip().split("\n")
         network_address_ipv4 = "-"
         network_address_ipv6 = "-"
         for line in ip_output_lines:

Thanks.

**Comment by hakandundar34coding** [comment]
Are there similar errors when other tabs are opened?

Do you use `/sbin/[command]` for other commands?

**Comment by babam86** [comment]
Only Performance --> Network has error

On Slackware the "ip" is located in the /sbin directory.
A  user (non root) does not have access to /sbin and /usr/sbin, so must use /sbin/command

**Comment by hakandundar34coding** [comment]
This bug is fixed and the source code is updated. There will be a new package in a week and it will include the latest source code.

Note: Only `Network.py` file is changed for fixing this bug.

**Comment by babam86** [comment]
Thank you very much
