### ISSUE TITLE
Feature Request: A way to display performance graph of individual process

### ISSUE THREAD

**Issue by Breigner01** [hakandundar34coding/system-monitoring-center#98]
I'd like to see a new feature to somehow show graphs of resource usage for an individual process.
For example when right clicking on a process, we could click on an option that would display a window with these graphs in it.
It's really useful to track the resource usage of a process over time.

I'd be happy to contribute to this feature

**Comment by hakandundar34coding** [comment]
I thought about this feature very long time ago.

This feature would increase CPU usage. Because this feature requires tracking CPU usage of all process. This application is written in Python and Python is slower in several cases when compared to programming languages like C++ and Rust.

Alternatively, CPU usage may be recorded after the window of a process is open. But it may not be useful and the process history will be cleared after the window is closed.

**Comment by Breigner01** [comment]
My idea was not to track the CPU usage of all processes at all time, it was just to have it tracked with a graph only when you open this window.

It is really useful when you are testing multiple programs that do the same stuff to know which one is more performant or which one is using a single thread.

I didn't intend to track all processes at all time I do realize that it would be really costly.

I don't know if it would make sense to maybe allow a whitelisting by the user for the processes he'd like being watched at all time, and maybe backing up the data to a file but I believe that advanced tool on monitoring, used in the server space, would be better at this job.

**Comment by hakandundar34coding** [comment]
The application may be running for 3 minutes and the window of a process may be opened after 3 minutes. The graph will not show the history in this situation. It will show the usage after the window is opened. Isn't it a problem for you?

Also currently multiple windows of processes are not supported. Only one window can be opened. This feature may be added in the newer versions. The CPU graph feature for comparing the processes may not be useful if multiple windows can not be opened.

**Comment by Breigner01** [comment]
It wouldn't be a problem for me to not have what happened before.

It would be really nice if we could open multiple windows at the same time but I think we can start with a single window for now.

**Comment by hakandundar34coding** [comment]
CPU, Memory (RSS) and Disk (download and upload speed) graphs are added to process details window.
You can follow these steps if you want to test this feature:

- Download the latest [source code](https://github.com/hakandundar34coding/system-monitoring-center/archive/refs/heads/master.zip).
- Extract it and open a terminal in `src` folder.
- Run this command: `python3 Main.py`
- Switch to Processes tab and double click on a process (or right click and select Details on the menu).
- Switch to CPU, Memory and Disk tabs on the process details window.
- Also check the terminal window to see if there are errors.

There will be a new package (v1.25.0) in about 4 days and this package will include the latest source code and features.

Opening windows of multiple processes feature may be added in the newer versions.

I will close this issue but you can write comments.
